### ISSUE TITLE
Implement pull-up based on opponent strength

### ISSUE THREAD

**Issue by tienne-B** [TabbycatDebate/tabbycat#1025]
Somewhat related to #484, as speaks could be used as well for this.

There could be a method to pull-up the team(s) with the lowest opponent strength (summed over the previous rounds) of the lower bracket. This could try to equalize the draw strength of each team, which could be seen as fairer.

**Comment by czlee** [comment]
Is there a tournament that currently desires this, or is this a hypothetical interesting feature?

**Comment by tienne-B** [comment]
Interesting hypothetical feature (emphasis on the _interesting_ :) ).
