### ISSUE TITLE
Private URL's not working for "Adjudicator Draw Notification"

### ISSUE THREAD

**Issue by 0zlw** [TabbycatDebate/tabbycat#1050]
Hi All,

I tried adding private URL's to the "Adjudicator Draw Notification" email as per the documentation here (https://github.com/TabbycatDebate/tabbycat/blob/develop/docs/features/notifications.rst) but the private URL was not sending on the email. Screenshots as per below.

![image](https://user-images.githubusercontent.com/3196468/53802420-a82aa980-3fa6-11e9-95ef-a9a7da10f704.png)

![image](https://user-images.githubusercontent.com/3196468/53802471-c2fd1e00-3fa6-11e9-9d60-db56d3f32520.png)

As a side issue, I can't find the "Notifications" documentation on the readthedocs features list.

![image](https://user-images.githubusercontent.com/3196468/53802570-fa6bca80-3fa6-11e9-8c76-5e0400c2231d.png)

**Comment by tienne-B** [comment]
Including private urls in draw notifications is not yet released (it'll be in 2.3 LaPerm), while your site and the documentation is still on 2.2 (All the available variables are listed beneath the text field).

If you want these unreleased features, use the `develop` branch:
https://heroku.com/deploy?template=https://github.com/TabbycatDebate/tabbycat/tree/develop

**Comment by 0zlw** [comment]
Ah right - perfect thanks so much for that link - getting these private URL's in room emails is going to be a massive help for us
