### ISSUE TITLE
Releasing motion to the public should warn if no motion entered

### ISSUE THREAD

**Issue by 0zlw** [TabbycatDebate/tabbycat#1051]
On 2.3.0A (deployed yesterday) there is no warning if you release a motion without a motion actually being entered for the round under WSDC motion entry settings. (except the default warning on the enter a motion section)

![image](https://user-images.githubusercontent.com/3196468/54095102-3e792800-440a-11e9-90af-067bd8393e41.png)

![image](https://user-images.githubusercontent.com/3196468/54095120-4f299e00-440a-11e9-9337-1d61c224ef26.png)

I think the preferred functionality should either be that it prevents you from releasing the motion if there is no motion entered or that there should be a warning message added to the "Released the motion(s)" message or alternatively to the release draw textbox

**Comment by czlee** [comment]
lol, I agree, thanks for reporting 🙂
