### ISSUE TITLE
Make tournament password config field not required unless password enabled

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#106]

**Comment by tienne-B** [comment]
What is being talked about here? This task is stale and might be moot now...

**Comment by czlee** [comment]
lol, it's low priority, but the described behavior is still there. If you go to Configuration > Data Entry and clear the "Password for public submission" field, it won't let you submit the form. This doesn't really make sense if the password isn't enabled in the first place ("Require password for submission").

This is really just another issue with preferences "aligning" with each other: the django-dynamic-preferences library has built-in support for validation of a single preference, but not cross-field validation. Though, at the time, we didn't really think of it like that.
