### ISSUE TITLE
Draw strength doesn't work for BP

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#1071]
The current method of computing draw strength relies on `populate_opponents`, which assumes that each debate-team only has one opponent. It'd be nice if it could be updated to grab all opponents. Since the existing code doesn't use the opponent for anything other than its team ID, there should be a single (complicated) query that can grab this directly (then look it up in `points_queryset` as defined in the existing code, as it does currently).

https://github.com/TabbycatDebate/tabbycat/blob/fbdabf141d9e39c049fb3234159296abba287437/tabbycat/standings/teams.py#L214-L231

Possible gotcha: If A faces B twice, then they should count for each other twice. In other words, don't use `.distinct()`, and the queryset should be by debate-team, not by team.

I think it's not ideal to change `populate_opponents` itself, since that's often used in contexts specific to two-team formats, and it'd be annoying to have to always deal with a list when most of the time it's just one team.

**Comment by mpopst** [comment]
Any progress?

**Comment by czlee** [comment]
Replied on Facebook, but the answer is no, sorry.

**Comment by danielnrocha** [comment]
Hi, there! In Brazil we use draw strength as the standard tiebreaker criteria, but we do not consider the sum of the number of wins of every team this team has faced so far. Rather, we consider the sum of the number of **points** of every team this team has faced so far. Is it possible to also include this metric? Brazil has an emerging debate circuit, and would be extremely helpful if this metric were available on tabbycat. Thanks in advance!

**Comment by tienne-B** [comment]
Points as in speaker points? That is included in the next version.

**Comment by danielnrocha** [comment]
Points as team points, actually

**Comment by tienne-B** [comment]
Oh, yes. How does team points differ from win/loss (1 point for winning, none for losing) in a non-BP style? It may be equivalent, or I'd be happy to add a new metric for you.

**Comment by danielnrocha** [comment]
We use BP too. Thinking better, it is equivalent as the team ranking is determined by the sum of speaker points. Glad to know this update is in progress! Any estimate of release date?

**Comment by czlee** [comment]
The implementation currently on the development branch computes the sum of team points of every opponent of a team, that was what #1150 changed 🙂

**Comment by tienne-B** [comment]
Hopefully soon. We are just quite busy and have a few big changes to revise (creating an API to connect to other software, and an overhaul of the results framework) before releasing a new version.

**Comment by danielnrocha** [comment]
> The implementation currently on the development branch computes the sum of team points of every opponent of a team, that was what #1150 changed 🙂

But it counts all the team points of every opponent of a team (including points from second and third place) or it only counts only the wins of every opponent of a team (i.e. 3 points)?

**Comment by tienne-B** [comment]
The former (including points from second/third)
