### ISSUE TITLE
Motion stats don't show unselected topics

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#1074]
In formats with motion selection, the motions that are not selected do not get shown on the motion stats page (at least for out-rounds; haven't checked for in-rounds). This is probably not desirable as it then essentially hides information about who vetoes that topic.

**Comment by czlee** [comment]
Just gonna keep highlighting relevant bits of code for anyone who wants to give it a crack:

https://github.com/TabbycatDebate/tabbycat/blob/8b4645aa2707585841439c1bc1088f1a63a18588/tabbycat/motions/statistics.py#L44-L62

It currently filters for confirmed ballots, hence the behaviour described above. I think it was originally written before the `filter=` keyword argument for `Count()` was introduced by Django, so this was the way to perform the counts you see in lines 46 and 56. The `'ndebates'` statistic might be able to be rewritten using this argument to avoid the filter filtering out all motions without results.

**Comment by tienne-B** [comment]
See also: #739

**Comment by philipbelesky** [comment]
Could anyone double check 121aea8535013a45e2b2212342ac3376a09d9b4c? It seems to exhibit the right behaviour but I don't completely remember the mechanics.

**Comment by czlee** [comment]
That filters for any motion attached to a round with at least one debate that has at least one ballot submission that's confirmed, so it probably works a lot of the time. At first glance it might risk double-counting motions that were multiply selected without a `.distinct()` on it, but I can never figure out this stuff without trying it.

That said, do we need to filter at all? If our intention is just to show information about all motions in the system, can we just drop the filter entirely?

We might want to then add a filter to make sure that it only shows completed rounds, but we have a field for that, we don't need to use confirmed ballots as a proxy, unless there's something I'm missing.
