### ISSUE TITLE
Team partial check-in indicator doesn't work with 2+ speaker-teams

### ISSUE THREAD

**Issue by viranweerasekera** [TabbycatDebate/tabbycat#1091]
The team's partial check-in indicator (where the box on the 'check-ins' page has green and grey stripes) displays when only 1 speaker in a team is checked-in, but then turns grey again when more than 1 speaker is checked-in but the entire team is not checked-in.

**Comment by philipbelesky** [comment]
Hey thanks for the bug report. After @tienne-B fixed the issue, I added a quick extra tweak:

- In 3-person formats there is now a blue stripey state for when only one person is checked in
- In 3-person formats the green stripey state is for when two people are checked in
- In 2-person formats the green stripey state occurs when only one person is checked in 

The intent of the blue vs green states is that a team with any green (whether a stripe or a full block) is not going to hold up beginning a round (i.e. if need be they can iron-person). Ill close this for now, but let me know if that idea is unclear or could use further tweaks.
