### ISSUE TITLE
Motion info-slides should have customizable formatting

### ISSUE THREAD

**Issue by tienne-B** [TabbycatDebate/tabbycat#1106]
It would be nice if images could be inserted in info-slides, as is sometimes done in PowerPoints in tournaments.

Quite easy as a task, as the Summernote widget could be used for the input. However, the display would also need some modifications for this purpose.

**Comment by philipbelesky** [comment]
Yea, I think the tricky part here is that we try to scale the text size so that it is as large as possible given the length of the string. Adding extra formatting tags might complicate that process.

**Comment by tienne-B** [comment]
Fixed with 430798f5b14348b0cfe1188f6f66e792f5ad00b5 (#2229).
