### ISSUE TITLE
Email draw/custom email/motions page formatting error

### ISSUE THREAD

**Issue by 0zlw** [TabbycatDebate/tabbycat#1177]
Running the latest develop branch v2.3.0A.

The message box on the email draw/custom email motions page is obscured/broken as per the picture running Windows 10/Google Chrome. 

Error reproduced on a Mac/Google Chrome. 

![image](https://user-images.githubusercontent.com/3196468/62782659-cfb20f00-bb0e-11e9-92a2-915ee0cb558d.png)

**Comment by tienne-B** [comment]
The patch #1178 will solve the problem
