### ISSUE TITLE
Update translations into release branch

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#1228]
Hopefully this should mean a decent increase in coverage relative to 2.2?

**Comment by tienne-B** [comment]
Just a note: Crowdin is de-wrapping the messages, so when running `dj makemessages`, use the `--no-wrap` option. Also, this was an intensive merge; I hope it's a one-off for the first sync.

**Comment by philipbelesky** [comment]
Great, thanks! To finish this off I assume we need to compile the messages; I just had a go but noticed there were a few errors. Did you want to handle those, or should I?

**Comment by tienne-B** [comment]
Ran `compilemessages`. The error you were getting was not from Tabbycat but from Sphinx. You need to run the command in the `tabbycat` subdirectory for the command to work.
