### ISSUE TITLE
Cannot view draw links for draws other than current

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#1239]
To reproduce:

- Go to the admin draw display area for a completed round
- Click any of the display links
- Links go to current round rather than the specific round

I assume this was a result of moving to the completed round system?

**Comment by tienne-B** [comment]
This behaviour is written in the links: "Display Draws for *All Current Rounds* ordered by ___" when the round is marked as completed. It seems intentional (there are round-specific links after those)
