### ISSUE TITLE
Trouble loading vue build

### ISSUE THREAD

**Issue by nickdbush** [TabbycatDebate/tabbycat#1262]
On a local Windows installation, after running ```npm run build``` and ```dj collectstatic```, the ```staticfiles/vue``` directory looks like this (in development mode):

![image](https://user-images.githubusercontent.com/10998201/66222334-d69d6e00-e6c8-11e9-87de-065ad465e7c2.png)

This means, when running ```dj runserver```, the main ```app.js``` file cannot be loaded as it is expected to be in the ```js``` directory:

https://github.com/TabbycatDebate/tabbycat/blob/1b1f11f05254b8f5aab62c9d60eb46b4eb13fd53/tabbycat/templates/base.html#L193

Chanigng this to ```vue/app.js``` fixed the problem, however there feels like there is a larger issue at hand, although I am not sure what that is.

**Comment by tienne-B** [comment]
Are you using the Linux subsystem installation method? If not, you probably should use `npm build-windows`, which also runs the commands to move the files in place. Does it work using that command?

**Comment by nickdbush** [comment]
I used the ```npm build-windows``` command. (I understand now why there's a move towards dropping native Windows support!)

**Comment by tienne-B** [comment]
It won't solve the underlying problem, but to get up-and-running, try using live-updating Vue? Instructions on how to set it up are here: https://tabbycat.readthedocs.io/en/latest/about/contributing.html#getting-started-with-development

Sorry, I normally use macOS, and @czlee who uses Windows is experiencing hardware difficulties for the moment.

**Comment by philipbelesky** [comment]
Hi @nickdbush, thanks for the report. I thought I got this in 6c276c696e446cfbe570b9ca61b5a41b97cbb24c but it looks like just adding the path isn't enough; for whatever reason the output of the vue compilation differs between windows and *nix. I've added a new step to `windows-build` that should copy the compiled folder over. I tested this with a fresh install, but please let me know if it doesn't work with your setup.

**Comment by philipbelesky** [comment]
Oh, and as etienne mentioned, if you ever find yourself needing to edit any of the Vue components its definitely worth checking out the live-updating option!
