### ISSUE TITLE
Changing language crashes on user creation form

### ISSUE THREAD

**Issue by tienne-B** [TabbycatDebate/tabbycat#1269]
In `BlankSiteStartView` in local/development installation, trying to change the user languages results in a 400 ERROR (`django.security.SuspiciousOperation`) with message: "The request's session was deleted before the request completed. The user may have logged out in a concurrent request, for example."

**Comment by philipbelesky** [comment]
@tienne-B this occurred when running on Heroku right?

**Comment by tienne-B** [comment]
Occurred locally.

That's odd; it works now.
