### ISSUE TITLE
Adjudicator allocation interface shouldn't re-sort when importance changes

### ISSUE THREAD

**Issue by 0zlw** [TabbycatDebate/tabbycat#1275]
This is probably closer to a feature request than a bug, but on the latest develop branch (v2.4.0A) currently after "sort by importance has been selected", when the importance of any debate is changed, the interface will re-sort the list in what (beyond importance) appears to be in a random fashion (or at least alternating). 

For example you can see in the screenshots below, I lower the importance of each debate 1 by 1 and the debate at the top of the list is alternating. 

![tabbycat1-1](https://user-images.githubusercontent.com/3196468/66834138-96d46180-efb9-11e9-8d79-72a28783ddd8.PNG)
![tabbycat1-2](https://user-images.githubusercontent.com/3196468/66834134-95a33480-efb9-11e9-8ce8-9c5c96c80e82.PNG)
![tabbycat1-3](https://user-images.githubusercontent.com/3196468/66834135-963bcb00-efb9-11e9-81a8-69e639863e18.PNG)
![tabbycat1-4](https://user-images.githubusercontent.com/3196468/66834136-963bcb00-efb9-11e9-8ae9-7032dec8b298.PNG)
![tabbycat1-5](https://user-images.githubusercontent.com/3196468/66834137-96d46180-efb9-11e9-9dee-91a4625bc954.PNG)

Usually after selecting "sort by importance" I would review the importance debate by debate and make any appropriate changes. With the interface choosing to randomly re-sort the debates after each change this makes it difficult as the debates don't stay in the same order which I think to some extent defeats the purpose of this setting. 

Proposed alternatives would be:
1. That it is sticky and selecting "sort by importance" only sorts when "sort by importance" is clicked.
2. That the altered debate changes positions but all other debates remain in the same order as best as possible.

My preferred alternative would be option 1 as I think this allows for faster workflow when making changes. I also think this is consistent with user expectations, for example if you sort on a filtered spreadsheet and then make a change, the order of the items remains sticky despite the sort being incorrect. 

Thanks for your continued hardwork with Tabbycat.

This also occurs in earlier versions as shown with a larger set of debates below. 

![tabbycat2-1](https://user-images.githubusercontent.com/3196468/66834483-309c0e80-efba-11e9-876a-54247dc1da1a.PNG)
![tabbycat2-2](https://user-images.githubusercontent.com/3196468/66834480-309c0e80-efba-11e9-9a2d-6e004e8b01a5.PNG)
![tabbycat2-3](https://user-images.githubusercontent.com/3196468/66834481-309c0e80-efba-11e9-82a1-94676853a3dd.PNG)

**Comment by philipbelesky** [comment]
Hey thanks for the detailed report. 

Option 2 seems like it can definitely be fixed - I think it just needs a secondary sorting characteristic that is fixed (like the name of the first team) so that the order is consistent beyond the importance value. 

Option 1 might be trickier, partly due to the implementation and partly because I think there are cases where you want automatic sort updates. If the desire is for a consistent ordering, does sorting by bracket not provide this? Open to adding separate options for a one-off sorting by importance rather than having it be maintained automatically though.

**Comment by 0zlw** [comment]
Hey thanks for the reply, I think option 2 would fix most of the problem and sounds like it would be relatively simple to implement. 

The desire for a consistent ordering is more in terms of workflow, so for example if you are reviewing the importance of the debates, you might sort by importance and then work your way down making changes. Option 2 would still be a significant improvement for this on the status quo.
