### ISSUE TITLE
Admin version of the Add Feedback form does not enforce required answers

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#1280]
As described in the title, although note that it does enforce answering who the feedback is about and what their score is. It just doesn't add the required attribute for any of the user-defined questions.

**Comment by czlee** [comment]
This is intentional behavior though? The idea is that the admin interface can override admin-specified requirements like this.

**Comment by philipbelesky** [comment]
Closed as its pre-existing intentional behaviour
