### ISSUE TITLE
Enable translation of manual

### ISSUE THREAD

**Issue by tienne-B** [TabbycatDebate/tabbycat#1357]
To improve our i18n/l10n efforts, the documentation of Tabbycat should also be translatable, to have better reach. Sphinx [supports](http://www.sphinx-doc.org/en/master/usage/advanced/intl.html) i18n, as well as [ReadTheDocs](https://docs.readthedocs.io/en/stable/localization.html#project-with-multiple-translations). The links are to pages explaining how, and it doesn't seem that complicated. The translatable messages could then be added to the Crowdin project under low priority.

**Comment by czlee** [comment]
This seems to be done?

**Comment by tienne-B** [comment]
Yes, but now ReadTheDocs settings need to be updated (and translations added here). This task is a reminder for that.

**Comment by czlee** [comment]
Ah, gotcha. Is this still a Maine Coon thing? Or do we want to hold off changing Read the Docs until after?

**Comment by tienne-B** [comment]
We could do this when pulling translations for Maine Coon.

**Comment by czlee** [comment]
Closing now that we know how to do the ReadTheDocs things, even though we've only really done it for one language so far.
