### ISSUE TITLE
Weighted feedback score based on Team Ranking

### ISSUE THREAD

**Issue by jacklishufan** [TabbycatDebate/tabbycat#1394]
Some CAs may want to adjust the weight of a feedback entry based on the result. For example, Teams who are placed first should have a higher weight than those who are placed fourth.

**Comment by czlee** [comment]
Ah, yes, this is one of many feature requests that are in our "too much for a tab system, someone who wants all these features should write a third-party feedback system and we should interface it via API" list. By itself it's not much, but it adds up with all other feature requests I've had of this nature of similar applicability and usefulness to be too much for the fairly basic feedback system that we have.

This particular feature is mercifully nearer in the API road: it would be covered by one of the higher-priority use cases I hinted at in https://github.com/TabbycatDebate/tabbycat/issues/1356#issuecomment-570155619, specifically, adjudicator score updates. (Feedback weighting doesn't affect any data collection, so an external script with access to all feedback and an ability to update adjudicator scores could implement it.) So I'd suggest that we fulfil the needs of a CA team who'd like this, by finishing the adjudicator score and feedback part of the API 🙂
