### ISSUE TITLE
Allow printing of adjudicator PrivateURLs only

### ISSUE THREAD

**Issue by cm319** [TabbycatDebate/tabbycat#1399]
The current system makes it so all of the PrivateURLs are exported to a PDF and prepared for printing. This can be very problematic when only the ones for the judges are needed and the competition has many participants. Could an option be added to select which ones should be sent to be printed, the same way it is done for sending e-mails?

Thanks!

**Comment by philipbelesky** [comment]
Hey, thanks for adding this issue. We've been aware of this as a pain point and will try to bundle this in to an upcoming release.
