### ISSUE TITLE
Emails

### ISSUE THREAD

**Issue by TabbyKat123** [TabbycatDebate/tabbycat#1419]
Debater and adjudicator URL  emails are not being sent. A message saying "e-mails queued" is what shows.

**Comment by tienne-B** [comment]
Hello!

There isn't much detail to this problem you're stating, so the main reason emails do not get sent is that your SendGrid account (which is created with Tabbycat) got disabled.

In https://dashboard.heroku.com/apps , click on your site. Then "SendGrid" should be under "Installed add-ons" Click that, and it'll show you the SendGrid account. That site will indicate if the account is suspended. Don't know why it sometimes deactivates, but you'd have to wait for it to reactivate. In that case, sorry; we don't manage the email delivery system.

Feel free to re-open the task if your SendGrid account isn't suspended; that would indicate a problem here that we can fix.

**Comment by tienne-B** [comment]
https://www.facebook.com/groups/tabbycat.debate/permalink/1195033653997923/ for more discussion/details
