### ISSUE TITLE
Internal server error after i reseted Database of my postgres

### ISSUE THREAD

**Issue by sam-wikwiki** [TabbycatDebate/tabbycat#1427]
TabbyCat is showing me an internal server error after I reset the Postgres database.
![postgres](https://user-images.githubusercontent.com/25524981/77237927-6773f180-6bf6-11ea-8def-1054c940a2f3.PNG)
![error](https://user-images.githubusercontent.com/25524981/77237933-6b077880-6bf6-11ea-8fb1-5498c944c006.PNG)

**Comment by tienne-B** [comment]
The reason there is a server error is that the database schema of Tabbycat is non-existent after a reset. This is not a situation we envision users having, as the schema is created during the deployment of an instance. This would be an issue if it wasn't being done at that time.

To fix it for specific instances, go to that instance's shell and type `dj migrate`.
