### ISSUE TITLE
Add venue information field

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#1430]
The idea is to add a "venue information" field to the [`Venue` model](https://github.com/TabbycatDebate/tabbycat/blob/af5f10b9cd3e37c28b2b3790106d80af262a30fe/tabbycat/venues/models.py#L7-L15), which would contain additional information about the venue. The first motivation is to help support online tournaments, but the field should be able to be used more generally. For example, it might contain:
* in an online tournament, a link to an online virtual room
* a link to a pin drop in Google Maps
* an image of a map
* special directions to avoid confusion, for example, "take the stairs on your left as you walk in, not the one on your right"
* detailed information about accessibility

Minimum implementation I have in mind:
1. Add an `information` field to `Venue`. I suggest making it a [`TextField`](https://docs.djangoproject.com/en/3.0/ref/models/fields/#textfield).
2. Add code to [`BaseTableBuilder.add_debate_venue_columns.construct_venue_cell`](https://github.com/TabbycatDebate/tabbycat/blob/af5f10b9cd3e37c28b2b3790106d80af262a30fe/tabbycat/utils/tables.py#L709-L739) to display this information.
    * `cell['popover']['content']` (line 737) is a list of dicts. Another dict should be added to this list for the venue information.
    * Django normally escapes HTML characters for security reasons, so in order for the venue information field to support HTML, the string should be marked safe using [`mark_safe`](https://docs.djangoproject.com/en/3.0/ref/utils/#django.utils.safestring.mark_safe).
    * If the field is blank, and there's nothing else to display in the popover, it should not display the popover at all

This implementation doesn't address how to input the information data, but for now that can be done through the Edit Database area.

Flagging potential conflicts with #1382, but so long as this is done on the `develop` branch I think it should be fine. That said, if we want to escalate the urgency of this patch, we might want to think about how it affects our release cycle.

**Comment by MagicDebate** [comment]
I really want to make an online version and I'm a cat

**Comment by philipbelesky** [comment]
Hi @MagicDebate, how were you going with this? I think we would like to roll a new release soon and ideally include a basic version of this.

Also, I've thought about the implementation, some quick notes:

- Relying on Popovers too heavily is not ideal. They are hard to trigger on touch devices and have limited space available — likely too little to display an image or a map. They also wont show in many places outside the draw
- From a UX perspective for online tournaments, it is probably ideal if the venue name itself just was a link. Even outside of an online context, that link could fulfil something of the same function, e.g. by pointing to a map.

A proposed tweak to the implementation would thus be:

- A `venueURL` text field. If set, most instances of the venue name in the UI become links
- A second venue info field that behaves as described by @czlee
