### ISSUE TITLE
Show only active tournaments

### ISSUE THREAD

**Issue by ngxson** [TabbycatDebate/tabbycat#1435]
Hi. Can we add `filter(active=True)` to [tabbycat/tournaments/views.py](https://github.com/TabbycatDebate/tabbycat/blob/develop/tabbycat/tournaments/views.py#L57), so we can only see active tournaments on home page?

**Comment by tienne-B** [comment]
We're looking into it ;) The discussion is in #1384, where the sticking point is how to expose inactive tournaments, as they would be undiscoverable if they get excluded. We'll probably end up making another page "Inactive Tournaments" to list them.

Merci pour la suggestion !

**Comment by ngxson** [comment]
That sounds great. Thank you!

**Comment by tienne-B** [comment]
Will be in the next release!
