### ISSUE TITLE
Adjudicator Allocation Page

### ISSUE THREAD

**Issue by 0zlw** [TabbycatDebate/tabbycat#1437]
Currently when sorting the Adjudicator Allocation page by importance it secondarily sorts by bracket in ascending order. My suggestion is that it would be preferable for the secondary sort to be by bracket in descending order. This better conforms to the default sorting which is bracket in descending order.

**Comment by tienne-B** [comment]
Looks good as a quick modification. Currently, there is no sorting by bracket after importance, but it could be added somewhat quickly.

**Comment by 0zlw** [comment]
Thanks! This is what it looks like for one of my tournaments at the moment

![image](https://user-images.githubusercontent.com/3196468/80558322-12fe3600-8a2e-11ea-9af0-095e4482affa.png)

**Comment by tienne-B** [comment]
A fix should be in the next version :)

**Comment by 0zlw** [comment]
Thanks that was quick!
