### ISSUE TITLE
Fixing a potentially misguiding documentation.

### ISSUE THREAD

**Issue by jacklishufan** [TabbycatDebate/tabbycat#1450]
> Tabbycat is a Django project, so can be installed in any manner that Django projects can normally be installed. For example, if you prefer some SQL system other than PostgreSQL, you can use it so long as it’s Django-compatible. Just be aware that we haven’t tried it.

I am trying to deploy an instance on my own server and I discovered that this project is dependent on PostgreSQL because the JSONField is employed in the data model, and django only has PostgreSQL support for this field [see here](https://docs.djangoproject.com/en/3.0/ref/contrib/postgres/fields/#django.contrib.postgres.fields.JSONField)

Therefore, I think this compatibility issue should be clearly flagged out in the documentation.

**Comment by tienne-B** [comment]
On what page(s)? The message has already changed for the next version, becoming

> If you wish to use an SQL engine other that PostgreSQL, most of Tabbycat should work, but a few features rely on SQL functions that aren't supported by all engines. To configure Tabbycat to use a different engine, set the ``DATABASES`` [Django setting](https://docs.djangoproject.com/en/2.2/ref/settings/#databases) accordingly.

Would this new language work? If you're in the docs, you can choose the `develop` branch on the lower-left of the page, rather than the default `master`.

**Comment by czlee** [comment]
Hmm, that statement was written many years ago, so I wouldn't be surprised it's now outdated. I don't mind removing it completely and just staying we only support PostgreSQL. Or the message currently on develop (as @tienne-B quoted) works too.

**Comment by tienne-B** [comment]
Fixed in 7ce6d74a72536d3557f96e0340c153b18043e24a.
