### ISSUE TITLE
Preformed panels supporting outrounds

### ISSUE THREAD

**Issue by 0zlw** [TabbycatDebate/tabbycat#1452]
I have been having a play with preformed panels and from my quick attempt to generate them for outrounds, it seems to generate preformed panels as if it was generating panels for an additional preliminary round rather than a break round. 

For example this is the preformed panels that generated when I generated preformed panels for quarter finals for one of our tournaments.

![image](https://user-images.githubusercontent.com/3196468/81673981-97c26880-94a0-11ea-8197-2a018682d9bf.png)

We did end up changing some thing to do with the round sequence for these rounds (we added 2 additional in rounds, deleted the octo finals and edited the sequence numbers, but this round is set up as per the settings below:

![image](https://user-images.githubusercontent.com/3196468/81674165-df48f480-94a0-11ea-873d-6239181c248d.png)

**Comment by tienne-B** [comment]
Good catch! Yes, the preformed panels does not count the number of debates in elimination rounds.
