### ISSUE TITLE
Creation of preformed panels stalling

### ISSUE THREAD

**Issue by 0zlw** [TabbycatDebate/tabbycat#1453]
I have been playing with preformed panels and while they generated almost instantaneously at aosd-2020.herokuapp.com running v2.3.2, when I attempt to create them at asd-2020-premier.herokuapp.com also running v2.3.2 the window stays at "loading" and never creates the preformed panels (even after waiting 5 minutes). 

![image](https://user-images.githubusercontent.com/3196468/81675044-4915ce00-94a2-11ea-96cd-9d65fd9db5cd.png)

The tournament where they generated successfully had completed round 5 and had an existing draw for the QF (see previous issue). The tournament where they did not generate had completed round 1 and I attempted to unsuccessfully generate preformed panels for rounds 2 and rounds 3.

**Comment by tienne-B** [comment]
Interesting problem. As the first steps, in your Heroku dashboard, make sure the `worker` dyno is present and active. You may also want to restart it or the whole application. The button for that is in the "More" dropdown in the top-right. The button is called "Restart all dynos".

**Comment by philipbelesky** [comment]
As a side note: I think there’s a broader issue that the worker dynos aren’t submitting error reports, so cases where it fails like this are probably more prevalent than we think.

**Comment by 0zlw** [comment]
Thanks for those troubleshooting steps. It turns out that we had the worker dyno off as I was trying to save money while our season was suspended.
