### ISSUE TITLE
Break round adjudicator allocation page should show and sort by room rankings

### ISSUE THREAD

**Issue by 0zlw** [TabbycatDebate/tabbycat#1454]
The break round adjudicator allocation page appears to sort rooms arbitrarily by default. This should by default show and sort by "room rank" as shown on the draw page for outrounds (or equivalent) by default and to ensure consistency.

![image](https://user-images.githubusercontent.com/3196468/81762619-38f10380-9521-11ea-96f9-ee97dc3c10fd.png)

![image](https://user-images.githubusercontent.com/3196468/81762629-3ee6e480-9521-11ea-9899-c64ee5c30818.png)

**Comment by philipbelesky** [comment]
This make sense, good catch. I’ve just done some work on sorting so should be able to add it in easily enough.

**Comment by philipbelesky** [comment]
Done! Should be there in next major release.
