### ISSUE TITLE
Break elligibility sort by number of speakers not working

### ISSUE THREAD

**Issue by 0zlw** [TabbycatDebate/tabbycat#1469]
Tabbycat Break Eligibility page on v2.4.0A is not allowing sorting by ESL speakers.

Initial View:

![image](https://user-images.githubusercontent.com/3196468/83277974-f456af00-a226-11ea-98bd-7f63c809df47.png)

After click ESL Speakers once:

![image](https://user-images.githubusercontent.com/3196468/83278007-01739e00-a227-11ea-9161-c302c4020d35.png)

After clicking ESL speakers twice:

![image](https://user-images.githubusercontent.com/3196468/83278031-0c2e3300-a227-11ea-80e0-0f992ff28533.png)

**Comment by philipbelesky** [comment]
Thanks for the report! We've fixed this and another sorting issue on that page.
