### ISSUE TITLE
Ballot Entry page should show debate venue 

### ISSUE THREAD

**Issue by 0zlw** [TabbycatDebate/tabbycat#1472]
The ballot entry page does not show the debate venue on it. Showing the venue can be helpful when locating where the ballot is, whether physically or online in this case (for this tournament, ballot are being submitted in a discord channel specific to a room but I need to go back to the main results entry page to work out where to find the mark sheet for the debate).

If I am not mistaken the old ballot entry page did show this?

![image](https://user-images.githubusercontent.com/3196468/83326144-a2189b00-a2c5-11ea-8773-3c20015e622e.png)

**Comment by philipbelesky** [comment]
It probably did show it. Definitely useful information to have, thanks for the report.
