### ISSUE TITLE
Improve feedback introduction/explanation

### ISSUE THREAD

**Issue by 0zlw** [TabbycatDebate/tabbycat#1475]
The current feedback introduction/explanation field only allows you to enter a "single" line of text rather than a paragraph of text.

It would be preferable to provide a richer text editor here to allow more instructions to be provided.

An inter-related issue would be allowing the judge feedback scale to be inserted directly into the feedback form. This is helpful as often people are not familiar with the judge feedback scale and have to refer back to the original briefing slides/information. This would also preferably be in the form of a rich text editor.

The feedback scale could be solved by a richer text editor but also can be its own separate field displayed inline with the score question. 

The following gives an example of how I am currently implementing this.

![image](https://user-images.githubusercontent.com/3196468/83340169-0caef280-a329-11ea-81b6-ce0501049108.png)

**Comment by philipbelesky** [comment]
Thanks for noting this. I don't think its documented, but HTML is valid in that textarea so you can use linebreaks and the like. A rich text field would be much better though.

**Comment by philipbelesky** [comment]
It turned out to be quite easy to make it a rich-text field, so this should be in the new version.
