### ISSUE TITLE
Indicate speaker redactions on admin standings

### ISSUE THREAD

**Issue by 0zlw** [TabbycatDebate/tabbycat#1480]
Hi, not sure if there is another way to see this but, admin speaker standings to not have any indication when a speaker is redacted. This means that you have to cross reference the redactions when using the admin speaker standings to announce speaker awards.

I didn't notice one of the speakers getting a top 10 speaker award today was meant to be redacted so they ended up being announced as part of prizegiving (but were redacted on tab release).

**Comment by philipbelesky** [comment]
Heh, back when we implemented it the expectation was that redaction would only be applied to the published tab, not to any announcements listed as part of the tournament. It can't hurt to add in some sort of indicator here though.

**Comment by 0zlw** [comment]
Thanks, completely understand re the original intention - it seems we've come a bit of distance with the way we now handle redactions in the community.
