### ISSUE TITLE
Internal server error report

### ISSUE THREAD

**Issue by AntonellaLuque** [TabbycatDebate/tabbycat#1490]
I hit an internal server error while trying to load this URL:
https://sdjad.herokuapp.com/internojad2019/admin/

Please describe what you were doing when the error happened, along with any other useful information:

**Comment by tienne-B** [comment]
Seems that the error is that the Redis Labs (used for caching) link cannot be found. Go to your Heroku dashboard, click on Heroku Labs. What shows up?
