### ISSUE TITLE
Use ORM for metric rankings

### ISSUE THREAD

**Issue by tienne-B** [TabbycatDebate/tabbycat#1491]
SQL window functions allow queries to have fields which reference other records, which can be used to get statistics like the percentile of the value in the row in the distribution of all in the partition. Django supports these annotations natively in its ORM.

The window function that seems useful is `RANK()`, which assigns an order on the records. This function could be used in standings to defer rank calculations to SQL for rankings and subrankings.

**Comment by czlee** [comment]
I think I looked at this once, then decided that for more complicated ranking annotations like subranks it was too obscure and unmaintainable to be worth the effort. Will be happy if there's a clean way to do it, analogous to `TeamScoreQuerySetMetricAnnotator`, though.

**Comment by tienne-B** [comment]
Subranks could be accomplished by using the ranking criteria as partitions (`ORDER BY` becomes `PARTITION BY`)
