### ISSUE TITLE
Internal server error report

### ISSUE THREAD

**Issue by Abod-98** [TabbycatDebate/tabbycat#1494]
I hit an internal server error while trying to load this URL:
https://trinityopen2020.herokuapp.com/database/adjfeedback/adjudicatorfeedbackquestion/add/

Please describe what you were doing when the error happened, along with any other useful information:

I was trying to input feedback questions for the tournament and every time I clicked save, it led to an internal server error

**Comment by tienne-B** [comment]
The problem is that the sequence numbers of the questions must be unique within tournaments, and so you can't have two first questions. For now, you have to keep track of the numbers used, but yes, we hope to improve the experience of adding questions.

**Comment by Abod-98** [comment]
Thank you!
