### ISSUE TITLE
Upgrade Heroku stack to Heroku-18

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#1503]
At a first glance, I think our stack can be upgraded without any issues.

Originally, we had to hold it back at Heroku-16 because the NGINX buildpack didn't support Heroku-18: 4912b94b4e0c85238bb8d0c1eb84e23154a87cfb

But then in their release 1.1, they added support, just a month after we held it back: https://github.com/heroku/heroku-buildpack-nginx/releases/tag/1.1

So I think we're good to upgrade to Heroku-18 now?

**Comment by tienne-B** [comment]
I have set `heroku-18` on a few sites (liduc-tabs for one) without problem for a few months now.

**Comment by philipbelesky** [comment]
NINGX was the only delay I recall, so should be good to go!
