### ISSUE TITLE
Summernote boxes don't show

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#1517]
I've had this happen a few times today, not sure if reliably reproducible yet. Only affects develop branch. Master branch works fine. Probably a dependency issue. Making a note so we remember to do something about it before Nebelung.

![image](https://user-images.githubusercontent.com/1725499/85212714-5d9f7e80-b30a-11ea-8f0f-362b7f7b8706.png)

![image](https://user-images.githubusercontent.com/1725499/85212739-8b84c300-b30a-11ea-9fdd-bbcab720f3f4.png)

Browser shows error:

> Refused to display 'https://hidden-caverns-06472.herokuapp.com/summernote/editor/id_tournament_staff/' in a frame because it set 'X-Frame-Options' to 'deny'.

**Comment by czlee** [comment]
Okay, it's a Django 3.0 thing.
https://docs.djangoproject.com/en/3.0/releases/3.0/#security
> `X_FRAME_OPTIONS` now defaults to `'DENY'`. In older versions, the `X_FRAME_OPTIONS` setting defaults to `'SAMEORIGIN'`. If your site uses frames of itself, you will need to explicitly set `X_FRAME_OPTIONS = 'SAMEORIGIN'` for them to continue working.

Readme file at https://github.com/summernote/django-summernote:
>5. If you're using Django 3.x with default SummernoteWidget, then
>     - Do not forget to set X_FRAME_OPTIONS = 'SAMEORIGIN' in your django settings.
>     - [Clickjacking Protection](https://docs.djangoproject.com/en/3.0/ref/clickjacking/)

We could just set `X_FRAME_OPTIONS` to `SAMEORIGIN`, though I sort of think it should be set just for pages from the django-summernote app, if that's possible.

**Comment by philipbelesky** [comment]
Looking [at the threat model](https://docs.djangoproject.com/en/3.0/ref/clickjacking/) I think `sameorigin` wouldn’t be a concern although a per-page setting would be nice.

**Comment by czlee** [comment]
Yeah, I agree with that assessment.

I opened https://github.com/summernote/django-summernote/pull/405, will see what the developer thinks 🙂

**Comment by mitchellpalmer** [comment]
Hi guys. I've been looking at #1106 (seems like low-hanging fruit to start contributing with) and I've run into this problem too. Did we find a conclusion to this issue apart from setting a site-wide `sameorigin`?

**Comment by philipbelesky** [comment]
Hi @mitchellpalmer, it looks like @czlee's PR upstream isn't going anywhere fast. Given that I thing it would be great to add in the change to the site wide config. We can always walk it back if we are able to take a more targeted approach.
