### ISSUE TITLE
Emails are not sent 

### ISSUE THREAD

**Issue by adrianoduque97** [TabbycatDebate/tabbycat#1545]
Check on SendGrid and just 33% was actually delivered
![image](https://user-images.githubusercontent.com/47148409/86503114-78450f00-bd70-11ea-883d-7d1742a6a0ac.png)

**Comment by tienne-B** [comment]
Refresh and scroll up? Is your account deactivated/disabled? SendGrid often does this, but we have a guide that may help: https://tabbycat.readthedocs.io/en/stable/install/heroku.html#sendgrid-account-details
