### ISSUE TITLE
Email exception handler crashes with undefined method

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#1547]
When the email consumer hits a connection or sending error, the exception handler crashes with

> 'NotificationQueueConsumer' object has no attribute 'send_error'

https://github.com/TabbycatDebate/tabbycat/blob/67bfe97290c4759caa65fbb200a72175a5d3c8fc/tabbycat/notifications/consumers.py#L33-L43

The method `send_error` is defined in `tournament.mixins.TournamentWebsocketMixin`. I'm not sure if that's meant to be a mixin for this class. Something similar seems to have been removed by fa3f9e828b1dafdd3947c5d74843a5d46ab8cd19.

**Comment by tienne-B** [comment]
That code was removed in https://github.com/TabbycatDebate/tabbycat/commit/cd2f92f61c307018c60981d3b64988a6d6373578
