### ISSUE TITLE
Drop requirement for teams to have institutions

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#155]
Nice-to-have, also probably a lot of work as I think current code base assumes all teams have institutions.

**Comment by philipbelesky** [comment]
Just a note/thought on this: cross institutional teams in many cases still need conflicts pointing to their original teams. So if this ever is refactored, the option to have multiple Institutions is something to consider.

Alternately, `Institution` could be a property of each speaker, and each speaker could have multiple institutions (or an institutional history ala tabbie).

**Comment by czlee** [comment]
Hmm, speaker institutions might not be a bad idea. We'd just have to make all institution fields optional, which would make for fun times writing any code that handles institutions.

**Comment by czlee** [comment]
Even if we do speaker institutions I suppose if we're being strictly correct we should allow for more than one? Though in the status quo I guess we expect users to make all these things as conflicts. In fact, doesn't our code separate the two entirely, so that (primary) institutional conflicts only count if they're actually marked as `AdjudicatorInstitutionConflict` objects?

**Comment by philipbelesky** [comment]
Mental note: this should extend to adjudicators also

**Comment by philipbelesky** [comment]
@czlee how viable do you think this is to implement (the dropping institutions from adjs/teams part; not the individual speaker institutions part). While this is less of a strict issue with BP draws, it is still quite annoying in the context of IVs and things where institutions are not required and are a hassle for data entry.

If a structural solution is too challenging for now, I wonder if there could be a data entry convenience during the importer that, when toggled, automatically creates a new institution just for that team.

**Comment by czlee** [comment]
I can't see any structural challenges. We'd just have to modify code that would crash or malfunction if an adjudicator's institution is `None`. One approach could be just to do it, and then fix pages that crash as we encounter them.

**Comment by czlee** [comment]
Oh, actually, for teams I'd have to examine the uniqueness constraints, since I think uniqueness isn't checked on null values. And possibly the `short_name`/`long_name` construction code. But I'm sure it can be done, somehow.

**Comment by czlee** [comment]
Non-exhaustive list of things that will break, that I propose we ban rather than modify:
- One-up-one-down. Since it just compares institutions, two teams both without institutions will look like they have the same institution.
- AIDA institution caps. Again, since it just compares institutions, all teams without institutions will look like they have the same institution.

I guess we'll need to add error messages or something like that.

**Comment by philipbelesky** [comment]
True. When you say ban what is the expected behaviour? Like if there is a 1-up-1-down does it refuse to generate the draw? Or temporarily pretend that the teams are from different institutions?

Fwiw, while it's not unheard of to have a cross-institutional team at Australs enforcing these rules strictly seems like it's an edge cases that could be handled pretty loosely if need be.

**Comment by czlee** [comment]
I haven't actually tried it, but I think it will pretend that two institution-less teams will be from the same institution, because `None == None`. Same for the cap—if four institution-less teams break, the last will be capped out.

On second thought, I think you're right, banning (refusing to generate) is a bit overkill. If we want to do it properly, a warning message would probably do the trick. Though, I guess, putting in place a warning message introduces probably about the same amount of clutter as handling the cases properly.

I'm also fine with just not handling the edge case, to be honest—so long as people check the draw and break, it should be fairly obvious that it happened.

**Comment by philipbelesky** [comment]
Yea, the odds of two cross-institutional teams breaking in a manner that applies the cap, and/or hitting each other as pull ups should be pretty low. You could probably make the argument cross-teams should even be subject to the same rules as two teams of an actual institution anyway.

**Comment by philipbelesky** [comment]
@czlee should we consider this closed? I ran ABP with one team set as institution-less without issues.

**Comment by czlee** [comment]
Umm, it depends on whether we want to handle those Australs edge cases. I'm fine with not handling them at all (since they won't crash, they'll just do weird things), if you're also comfortable with that.

**Comment by philipbelesky** [comment]
Yea, that sounds good. Maybe to close this we should:

- [ ] Add a note to the documentation about using institutions without teams. I assume this should include advice that for Minis/IVs having all (or a large portion of teams) without institutions, that they should disable rules that prevent matching similar institutions and use break rules that don't take into account institutional caps.

**Comment by philipbelesky** [comment]
Oh and also: 

- [ ] Add methods (and potentially warnings) to the simple importer for adding teams without institutions

**Comment by philipbelesky** [comment]
Any idea on how to allow for institution-less teams or adjudicators in the simple importer? Should I hijack the institutions_list with a 'fake' institution and then catch it at the end? Or would this be better handled by creating a seperate form just for this purpose (that could inherent from the main one and override as needed)?

**Comment by czlee** [comment]
Hmm, the latter option would be easier to code, I guess, but we probably want to include it on the same form. I wonder if we can do it so that it's not so much a fake institution as it is just a field on the same form that we handle specially.

**Comment by philipbelesky** [comment]
Yea, I presume the interface would present 'Institution-less' as an option in the list of existing institutions and the subsequent screen would act as normal. I'll have a look and see if I can adapt the existing forms to handle this.

**Comment by philipbelesky** [comment]
- Allow Simple Importer to add teams/adjudicators without institutions
- Update documentation to specify you can add without institutions + note any draw complications

**Comment by philipbelesky** [comment]
@czlee quick heads up:

- Modifying the existing form(s) was easier than I was expecting and the implementation seems to work fine. The one part I was unsure about was the code under `if institution_id is None` modified in [this commit](https://github.com/czlee/tabbycat/commit/b5f5cdee53d73212f53085afac70cc457e73ffee). I wasn't sure under what circumstances `institution_id` would be None outside of this (new) circumstance where it is passed as such from the previous step.
- Note [this note](https://github.com/czlee/tabbycat/commit/c67ade1db071c20b25740819c9c4627b3f95994b) added to the docs about importtournament; if it (or your new importer) does allow for importing institution-less teams/adjudicators we will need to update it.

Let me know if there was anything I missed or should test, otherwise I think this can be closed.

**Comment by czlee** [comment]
Oh, the command-line importer totally supports institution-less teams. You just leave the institution field blank, and it'll assume it's None. At least this is the case for the Boots importer, I haven't tried this with Anorak but I'd be surprised if it doesn't work (or it should be easily fixable).

This isn't unique to this case by the way - in general, all command-line importers will always interpret _any_ blank field as None. If the field in question doesn't allow nulls, then it'll raise an error during model validation.

**Comment by philipbelesky** [comment]
Anorak definitely chokes on importing teams/adjudicators without institutions. I'm not sure how to replace the `pm.Institution.objects.lookup` call to fix this; could I leave that to you? We can then remove that note from the docs.

**Comment by czlee** [comment]
Ah, right, I see. I implemented a better framework for stuff like this in the base class, will upgrade Anorak when I get a chance. If you want to push this soon, I'm fine with saying that Boots supports institutionless teams but Anorak doesn't (if we want to add Boots to the docs).
