### ISSUE TITLE
Sendgrid not working from heroku

### ISSUE THREAD

**Issue by adrianoduque97** [TabbycatDebate/tabbycat#1550]
When trying to enter the addon I receive this, not sure if it a matter of heroku or tabbycat install

![image](https://user-images.githubusercontent.com/47148409/87227780-c35bb500-c362-11ea-9910-07e6dc92a8c5.png)

**Comment by adrianoduque97** [comment]
![image](https://user-images.githubusercontent.com/47148409/87227828-fbfb8e80-c362-11ea-9caf-7fe03baf68aa.png)

**Comment by tienne-B** [comment]
Link to #1545. Did you try contacting SendGrid? This is not caused by Tabbycat itself.
