### ISSUE TITLE
Feedback overview difference sorting

### ISSUE THREAD

**Issue by 0zlw** [TabbycatDebate/tabbycat#1553]
Currently when you order by "difference between an adjudicators base score and current score it orders by absolute magnitude (not maximum positive to maximum negative). While I understand what the original intent for this is, I think it might be more helpful to sort by maximum positive to maximum negative as this allows you to separately analyse the judges performing significantly above base and below base (which require different actions by adj core)

**Comment by tienne-B** [comment]
Fixed in bf757cdae2d782b93692a6465f097ec96d27ae48
