### ISSUE TITLE
Email notification of the draw by teams

### ISSUE THREAD

**Issue by moshpirit** [TabbycatDebate/tabbycat#1562]
It would be fantastic getting an automatic mail when the draw is released saying the draw of my team (positions, room, teams of my room and judges) something like:

The draw of the round {round} of {Tournament} has been released:
OG: {Team OG}
OO: {Team OO}
**CG: {Team CG}** # My team is showed bold
CO: {Team CO}
The panel will be: {Judges}

**Comment by tienne-B** [comment]
We do have emails that indicate that the draw is released, with team/adj highlights. However, they are not automatic, but on the admin draw display page. This was seen as preferable to automatically sending messages as it offers the admins more control over who gets the messages, there are fewer chances for changes to be made, and doesn't require the draw to be publicly posted.
