### ISSUE TITLE
Deployment error

### ISSUE THREAD

**Issue by 0zlw** [TabbycatDebate/tabbycat#1585]
Attempting to deploy Tabbycat to Heroku - this was the development branch, but also occurred on main last night.

![image](https://user-images.githubusercontent.com/3196468/90209163-b426c600-de3e-11ea-9655-b00780d71292.png)

**Comment by tienne-B** [comment]
SendGrid is getting quite annoying. For now, try this link to deploy the current stable but without SendGrid: https://heroku.com/deploy?template=https://github.com/tienne-B/tabbycat/tree/no-sendgrid

**Comment by 0zlw** [comment]
Deployed fine using the no-sendgrid option, thanks!
