### ISSUE TITLE
Add support for negative team prep rooms

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#161]

**Comment by tienne-B** [comment]
Aside: In Quebec (at least), the affirmative team is the one who leaves the room :)

More details here? For one, would these rooms be included with the debate rooms (just with a different flag or category), and specifically assigned to the other team(s)?

**Comment by czlee** [comment]
Oh, yeah, there's a context to this, and possibly one that's less generalizable than it should be.

In some tournaments (well, smaller ones in New Zealand at the high school level, where prep time is one hour and there are enough rooms to support this), the negative team is assigned a different room to prepare in, so they don't have to prepare in the corridor. So the idea here would be to provide some way to indicate which room that is.

It's not as if this isn't possible now: you can just add the negative prep room to the venue name, e.g. "G04 (neg prep G05)". I think at the time, I was thinking it'd be nice to have a better mechanism for this, but I wasn't sure what. I'm now no longer of the opinion that we should bother.

**Comment by tienne-B** [comment]
Close this task?

**Comment by czlee** [comment]
Yeah… why not 🙂 We can reopen later if we change our minds again.
