### ISSUE TITLE
Add proper support for unknown sides

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#163]
Succeeds #158.

At the moment, most of the code base assumes that there is always an affirmative team and always a negative team in every debate. This assumption doesn't always hold. Sometimes there are just two teams in a debate, and you don't know which is which. The code base needs to be modified to remove this assumption.

The assumption also necessitates some ugly hacks, like the `and self.ballots.pk is not None` in forms.py:

``` python
        # HACK: Check here to see if self.ballots has been saved -- if it's not,
        # then it's a new ballots form, and choose_sides should not be populated
        # with an initial value.
        if self.choosing_sides and self.ballots.pk is not None:
            try:
                initial['choose_sides'] = str(self.debate.aff_team.id) + "," + str(self.debate.neg_team.id)
            except DebateTeam.DoesNotExist:
                pass
```

**Comment by czlee** [comment]
This could also be applied to break rounds, so it'd be useful to do it properly, but it might take some thought about which apps this would affect and how.

**Comment by philipbelesky** [comment]
Given that #376 is closed, I think the part of that issue that discussed front end changes to the results form still has value: that there should be the option to assign or edit sides within the results form. The most obvious use case here is for the NZ formats where sides are not specified in advance. It would also be good for break rounds when you don't want to handle the hassle of doing the coin flip data entry.

**Comment by czlee** [comment]
Agreed, I also think the back-end part of this issue still has value, for the same reasons. That is, I'd prefer for support not to be based around masking "true" database positions in the UI.

**Comment by czlee** [comment]
I bumped this down a release to try and spread work out a bit, I think this is worth doing and is definitely not low-priority but I think other refactoring efforts are a bit more pressing. If I'm missing something then feel free to bump back.

**Comment by philipbelesky** [comment]
Is this still going in to 1.4?

**Comment by czlee** [comment]
Probably not, didn't end up doing it.

Le 12 juil. 2017 22:49, "Philip Belesky" <notifications@github.com> a
écrit :

**Comment by czlee** [comment]
Some notes in relation to line comments at https://github.com/czlee/tabbycat/commit/39d83eb10c763bd1969a4a9ddda102e289ed1411#commitcomment-24171725 and https://github.com/czlee/tabbycat/commit/41037c2201713fbf3a2dc2ff43bd13b9af2092ed#commitcomment-24179626:

## Option 1
Have a `SIDE_UNALLOCATED` value, and assign teams to it when they don't yet have sides.

Pros | Cons
-----|-----
Semantically correct | Hard to implement
Allows space for only some debates in a round to have allocated sides | UI would need to know how to deal with unallocated sides everywhere
Probably less confusing for tab directors | Edit matchups would need to be redesigned to allow this
Failure of UI to account for this would fail fast | Can't enforce debate-side uniqueness, since multiple sides might be unallocated

## Option 2
Assign all teams sides as usual, and have a `BooleanField` in `Round` that indicates whether sides are "correct" for the round. This field would then change the public and briefing room views to display either "team 1, team 2" or "affirmative, negative".

Pros | Cons
-----|-----
Easiest to implement | Semantically nonsense
Probably easier for tab directors to control | Probably harder for tab directors to learn
No change to edit matchups | Either all debates in a round are side-allocated, or none are
Can enforce debate-side uniqueness at database level, simplifying some code | Harder to cover all bases, e.g., participant record pages also need to handle appropriately

## Option 3
Assign all teams sides as usual, and have a `BooleanField` in `Debate` that indicates whether sides are "correct" or not.

Pros | Cons
-----|-----
Semantically not stupid | except that teams marked "affirmative" might not actually be affirmative
Not crazy to implement | but UI would need to check every debate individually, and aggregate to decide column headings
No concept of partially allocated within a debate—either the debate is allocated, or it isn't | Still need to cover all bases, e.g., participant record pages
Only a single checkbox column needs to be added to edit matchups | Doesn't really allow for possibility that different ballot submissions for a single debate might conflict (without extra work)
Can enforce debate-side uniqueness at database level, simplifying some code | 

I originally thought option 3 might just be a compromise option but now that I've typed this out it actually might be sensible…

**Comment by philipbelesky** [comment]
Yea, 3 does seem relatively effective in that it mostly seems to involve UI changes to highlight the fact that a side is currently unknown. Column headings could perhaps even be unchanged, and the indicator of "unknowness" could be shifted to an in-cell representation.

Also whats the priority for this? Is the plan to put it into the next major release given the other changes to sides there? Is it still somewhat speculative? For break rounds it seems like it could offer a nice visual indicator, but isn't especially critical given you'd need to Edit Matchups anyway for draw display purposes.

**Comment by czlee** [comment]
I don't really know. The main reason I've been putting it off is because it's hard. If option 3 promises an easier way to do it, then I might consider getting it out of the way.

For break rounds the main advantage of doing this properly is that you don't feel bad about releasing the draw before sides are assigned.

**Comment by czlee** [comment]
Just a heads-up, I added an admin action to allow debates to be set to sides confirmed/not confirmed in bulk, and merged the feature branch in, since with the admin action it's now usable, albeit not user-friendly.

**Comment by philipbelesky** [comment]
Should this be closed now?

**Comment by czlee** [comment]
Yes, the last thing was the confirmed/unconfirmed checkboxes in Edit Matchups.
