### ISSUE TITLE
Adjudicator allocation screens should sort by room rank

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#1643]
The panels on the adj allocation page are sorted by bracket rather than by room rank. 

This affected #1642 as follows: In the scenario we had, the original preformed panels for round 8 had been created before round 6 results were finalized, so all of the `bracket_min` and `bracket_max` fields were 0. Moreover, for a presumably undocumented reason (like, database order), the actual order was the _inverse_ of room rank, i.e. rooms from "lowest" to "highest". This meant that the panels the CA team member created were "out of order", so if we were to "create panels" to refresh the brackets and liveness, the brackets wouldn't just run from top to bottom (as shown in the UI) like one would expect.

More generally, though, the primary purpose of the room rank field, in both debates and preformed panels (and other than in elimination rounds), is to provide a consistent unique ordering for rooms, independent of bracket, liveness and importance—for various reasons, none of those provide a satisfactory ordering for rooms. We should be ranking by room rank instead.

This also goes for the main adjudicator allocation page—currently, debates show in an order that may be inconsistent with the main draw page, because debates are arbitrarily ordered within bracket. Sorting by room rank would resolve this issue.

**Comment by philipbelesky** [comment]
Quick note that f61c63595ecf817d796cc4619f61a9fe83bf1092 and cf6e7c0887d859ec9f4d35de9bb3e6157bd161d0 enable this in a very weak fashion by changing the default sort and showing the option to re-force the sort outside of elim rounds. Not sure if that's sufficient to close this - we may want to roll the behaviour into the bracket sort or add some documentation about why an ordinal sorting is needed.

**Comment by tienne-B** [comment]
Seems fixed in 1ce9039d4df7f4b1c728009b3cb01f64fd19f428
