### ISSUE TITLE
Change round start time to DateTimeField

### ISSUE THREAD

**Issue by tienne-B** [TabbycatDebate/tabbycat#1666]
This would be a somewhat big change to a small feature, but it could be useful for the round start time to have a date associated with it, which could then be used to timestamp when was the tournament held, which might not be shown otherwise. The input of the time could then be an interval with some JS to preview the resulting time. The full date could be shown after the tournament, or when the date does not correspond with today's.

For migrating, the date would be most likely found by the date of the first ballot submission for that round (edge case very early morning)

**Comment by czlee** [comment]
Yeah, sure, as the person who added this feature back in 2014, I'd be happy to see this extended.

I think the existing field is timezone-naive, so the migration might have to take care with the conversion. Making it timezone-naive made sense given the use case in 2014, but it might be a bit of a nuisance now.

**Comment by tienne-B** [comment]
Yes, the existing field is timezone-naive; `TimeField` cannot be timezone-aware.
