### ISSUE TITLE
Internal server error report

### ISSUE THREAD

**Issue by MagicDebate** [TabbycatDebate/tabbycat#1669]
I hit an internal server error while trying to load this URL:
https://schooldebate2020.herokuapp.com/Zima2020/admin/draw/round/2/create/

Please describe what you were doing when the error happened, along with any other useful information:

**Comment by czlee** [comment]
The error message we're getting is:
> ValueError: Invalid option for odd_bracket: intermediate2

I think you have an odd bracket resolution method that's intended only for use with pre-allocated sides. It's under Configuration > Draw Rules > Odd bracket resolution method.

You probably want to change the odd bracket resolution method to "Intermediate brackets".

If you intended to use pre-allocated sides (as in, teams are assigned affirmative or negative before the competition starts), then you need to set the "Side allocations method" (same screen) accordingly.

**Comment by tienne-B** [comment]
I've added a warning with https://github.com/TabbycatDebate/tabbycat/commit/603eba7445efa75fabc9b7b15d6bb8f780bc70f3 to show the problem.
