### ISSUE TITLE
Internal server error report

### ISSUE THREAD

**Issue by IktaS** [TabbycatDebate/tabbycat#1682]
I hit an internal server error while trying to load this URL:
https://pim-unair.herokuapp.com/kdmi2020/admin/standings/round/1/team/

Please describe what you were doing when the error happened, along with any other useful information:
- I was checking around in the standings, and saw this happend on my team standings page, there shouldn't be any debate data nor score data, but it returned 500 Internal Server error

**Comment by tienne-B** [comment]
Odd problem; do your `TeamScore` objects have a "votes possible" field that is 0?

**Comment by IktaS** [comment]
@tienne-B TeamScore Object as in in /database/results/teamscore? There's no TeamScore object, no debates have occured. Additional info: previously I tried generating draw for R1, then deleted said round, then remade round 1, then this problem occurred, does that have to do with anything?

**Comment by IktaS** [comment]
I upgraded to v2.5.1 in heroku but problem persist, any help in fixing this problem?

**Comment by IktaS** [comment]
Found the error in the application log
`2020-12-05T10:06:27.757769+00:00 app[web.1]: 10:06:27 wsgi.1  |     cast = int if all(t.num_adjs == int(t.num_adjs) for t in queryset) else float

2020-12-05T10:06:27.757964+00:00 app[web.1]: 10:06:27 wsgi.1  | TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

**Comment by tienne-B** [comment]
Try upgrading again to the `develop` branch; changed the fix in 8fb38b703a9ec35a61e703c619a9c2d01051d84f

**Comment by IktaS** [comment]
all right, it's fixed now
