### ISSUE TITLE
Internal server error report

### ISSUE THREAD

**Issue by altynayabdizhamil** [TabbycatDebate/tabbycat#1686]
I hit an internal server error while trying to load this URL:
https://adu-wgm.herokuapp.com/wgm2020/admin/draw/round/5/create/
![image](https://user-images.githubusercontent.com/59067983/101284240-33367480-3809-11eb-9dba-81493f30dc18.png)

Please describe what you were doing when the error happened, along with any other useful information:

**Comment by tienne-B** [comment]
Update the version of Tabbycat you're using: https://tabbycat.readthedocs.io/en/latest/install/heroku.html#upgrading-an-existing-heroku-app

The bug was fixed in e9cd476609055316c86ef7d7247492c6fcac9798.
