### ISSUE TITLE
Edit sides/matchups screen doesn't save more than one change

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#1689]
After the first change, browser console shows error:
> WebSocket is already in CLOSING or CLOSED state.

Relates to: [BACKEND-3WN](https://sentry.io/organizations/tabbycat/issues/1876870822/), which was resolved by 6839ca5b041470dbbbbb3b5ae909e31d5ae59b68. That was on adj allocations, the issue persists in sides/matchups.

Thanks to @willsilberman for reporting.

**Comment by czlee** [comment]
Okay, that was just a repeat of 6839ca5b041470dbbbbb3b5ae909e31d5ae59b68, I hadn't fixed everything then. I think that's everything now, I ran `git grep "del content"` to check.

**Comment by tienne-B** [comment]
Wait, did we show the former fix actually worked? Thought it was just taking a shot at solving the problem.

**Comment by czlee** [comment]
Oh, lol, well, the original fix was live in 2.5.0. I can say now that it works, because @willsilberman tried out this hotfix.

The question that's probably still open is whether this is the correct fix or whether there's some deeper problem with how we've structured this code.
