### ISSUE TITLE
Internal server error report

### ISSUE THREAD

**Issue by Josh-Cena** [TabbycatDebate/tabbycat#1694]
I hit an internal server error while trying to load this URL:
https://oridebate.herokuapp.com/oridebate2020/admin/draw/round/2/create/

Please describe what you were doing when the error happened, along with any other useful information:

This is a debate tournament with pre-allocated sides and 6 teams out of 9 were marked as available. (Everything was in fact pre-determined and we were solely using tabby for results display.) 3 rooms and 3 adjudicators were also checked in. There were no conflicts set. When attempting to generate the draw, the server returned a 500 error.

**Comment by tienne-B** [comment]
There seems to have been a few different problems:
* If using preallocated sides, a preallocated sides odd bracket resolution method has to be used (in Draw Rules)
* Preallocated sides requires the manual creation of `TeamSideAllocation` objects
* A second metric is needed to be able to tiebreak. In your case, you could keep the draw method as random or manual so that the draw generator doesn't look at standings.

**Comment by Josh-Cena** [comment]
> There seems to have been a few different problems:
> 
> * If using preallocated sides, a preallocated sides odd bracket resolution method has to be used (in Draw Rules)
> * Preallocated sides requires the manual creation of `TeamSideAllocation` objects
> * A second metric is needed to be able to tiebreak. In your case, you could keep the draw method as random or manual so that the draw generator doesn't look at standings.

Thanks for the advice. I tried:

- Setting the odd bracket rule to "intermediate 1";
- Setting pairing method to "random".

That didn't seem to solve my problem. In fact the preallocated sides were balanced (3 props and 3 opps), so there were no odd brackets present. 

On the `TeamSideAllocation` object. I allocated sides through the Django interface--this app was directly deployed to Heroku and it was not installed locally. I wonder how I would be able to create such an object, and how it differs from the `TeamPositionAllocation` object specified in the documentation for preallocating sides. 

Is there a way to view more detailed error messages? Do I need to clone the app to my local environment?

**Comment by tienne-B** [comment]
Did you set all rounds to be random?

**Comment by Josh-Cena** [comment]
> Did you set all rounds to be random?

How do I do that? I just changed pairing method to random in the configuration. I thought that would be automatically applied to all rounds.

**Comment by tienne-B** [comment]
Oh, so in the Edit Database area under "Tournaments" -> "Round", each round has a "Draw type" to set to "Random" rather than power-paired.

**Comment by Josh-Cena** [comment]
Okay it worked. Thank you so much!

I guess the system can benefit from some more user-friendly error messages if ever applicable. I wonder why this only comes through as a 500 error...
