### ISSUE TITLE
Team API endpoints should return code_name as short_name when codenames are in use

### ISSUE THREAD

**Issue by CreatedBySeb** [TabbycatDebate/tabbycat#1695]
The `short_name` field in the API docs is described as the name shown in the draw, which would indicate that this should be the `code_name` value if the tab is configured to use codenames on the draw. I think that if the short_name value is meant to represent exactly what would be publicly visible, it should be the code_name in this case, otherwise this should probably be documented as it is unintuitive given the current description of the field.

**Comment by tienne-B** [comment]
This isn't just an API issue, as the API takes the descriptions for most fields from the model directly, including for `short_reference` and `short_name`. It would be fine to add a qualifier like "decoded" to the descriptions, but returning values for other fields would bring consistency problems (like between authenticated/public access) and would add too much complexity.

**Comment by tienne-B** [comment]
Changed descriptions in 7e8f8018898b858034374553fa8e3c99243c21b4.
