### ISSUE TITLE
Room constrainee ID dropdown doesn't list options

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#1722]
This field is meant to show the constrainees that match the constrainee type (i.e., `subject_content_type`), but it doesn't.
![image](https://user-images.githubusercontent.com/1725499/105571015-9587fd80-5d01-11eb-8f51-7789963ece01.png)

Thanks to Will Reilley Silberman for bringing this to my attention.

## Diagnosis work so far
- The data list is present and correct, but all of the options in the data list appear always to be disabled, even when you change the constrainee type. Disabled options aren't included in the dropdown, so this means the dropdown is always empty. https://github.com/TabbycatDebate/tabbycat/blob/a72e905a449048c71d97625a4d560579bf80ff7f/tabbycat/venues/templates/venue_constraints_edit.html#L32-L42
- The JavaScript in venue_constraints_edit.html that modifies the data list filter does so by checking if the name of the type (e.g., "team") is case-insensitively contained within the option label (e.g., "Bree HC (Team)").
- However, currently, the content type label is "participants | team" (etc.) rather than just "team". This means that the type label is never contained within constrainee label, so no constrainee passes the filter for any type.
- This appears to be a change in Django that first appeared in Django 3.0: https://github.com/django/django/commit/48c17807a99f7a4341c74db19e16a37b010827c2, https://github.com/django/django/pull/10776. The change is sensible, but unfortunately it breaks our assumptions.
- We first upgraded to Django 3.0 in Nebelung (2.5): https://github.com/TabbycatDebate/tabbycat/commit/becabef7a077e855acd0540a92ed718f76b7a521. So presumably issue is new in that version, which we released just a couple of months ago.

## Unsuccessful fix efforts so far
All we want to do is revert the content type labels to their old behaviour, which is just the `ContentType.name` field.
- Specifying `choices` in the `Select()` constructor in venues/views.py doesn't seem to help, the choices seem to be overridden by the queryset for `ContentType`, regardless of whether `ForeignKey.limit_choices_to` is specified. https://github.com/TabbycatDebate/tabbycat/blob/a72e905a449048c71d97625a4d560579bf80ff7f/tabbycat/venues/views.py#L116-L119
- Is there a method we can override to specify how to get option labels, maybe, so that it'll take `content_type.name` rather than `str(content_type)`?

**Comment by tienne-B** [comment]
Yes, we can specify how to get option labels by subclassing `ModelChoiceField` with a custom `label_from_instance(self, obj)` method, returning `obj.name`.

**Comment by czlee** [comment]
Ah, that's it, thanks. Then the next fun question is how to pass that via `formset_factory_kwargs` 😅

**Comment by tienne-B** [comment]
We might as well split the page into 3; one for each type of constraint. I think I did it in #926.

**Comment by czlee** [comment]
I think we had the three on one page partly

**Comment by czlee** [comment]
Gah, I tried subclassing `ModelChoiceField` to override `label_from_instance()`, then subclassing `ForeignKey` to `formfield()`, then using that for `subject_content_type`, included print statements to verify that my code was in fact running, and even that doesn't work—it appears that the `app_label_name` overrides the whole lot.

**Comment by czlee** [comment]
Oh, just kidding, I was changing the wrong field, lol.
