### ISSUE TITLE
Dissenting judges

### ISSUE THREAD

**Issue by SEDAlk** [TabbycatDebate/tabbycat#1738]
Hello, 

Currently tabby cat does not include dissenting judges when calculating speaker scores.  Is there anything i can change in the configuration to make it include dissenting judges when calculating speaker scores!?
-Lin

**Comment by tienne-B** [comment]
Yes. You can activate "Margin includes dissenters" in the Configuration under "Score Rules".

**Comment by czlee** [comment]
Hmm, should we update the name to this setting?

**Comment by SEDAlk** [comment]
Yes I think naming it 'speaker scores include dissenters' , or something like that, would be easier to understand!
