### ISSUE TITLE
When adding an adjudicator for an institution, tabbycat doesn't create an adjudicator-institution conflict

### ISSUE THREAD

**Issue by ReteganCatalin** [TabbycatDebate/tabbycat#1740]
I believe this is a bug(or is an undocumented change), the instance of tabbycat was directly deployed to Heroku from tabbycat website

**Comment by philipbelesky** [comment]
Hey thanks for the report. Just to confirm: what method were you using to add the adj? Was this when adding in the database area?

**Comment by ReteganCatalin** [comment]
When adding from Setup->import data

**Comment by tienne-B** [comment]
I've just tested adding an institutional adjudicator through "Import Data" on `develop`; and the conflict was added (as it should). There have been no changes to the mechanism between `master` and `develop`. Glitch? I can't find the problem and there is little detail here.
