### ISSUE TITLE
Update guidance for email configuration

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#1751]
Creating an issue to track much-discussed updates relating to how emails are configured. This issue is about configuring an email server for Tabbycat. It is *not* about the notifications framework within Tabbycat, though where configuring via Tabbycat settings is a substitute for configuring via environment variables, it may touch on it.

See also: [Posts marked #emails in the Facebook group](https://www.facebook.com/hashtag/emails/).

Current state of discussion:
1. **Automatically provisioning SendGrid is no longer viable.** Two main problems:
    - SendGrid auto-blocks all automatically created accounts (e.g. created via the Heroku add-on), and the only known way to get them unblocked is to contact SendGrid support and wait for a response. While they respond within 24-48 hours, this also sort of renders the concept of automatic provisioning moot.
    - SendGrid spams you _every four minutes_ from the time the account is created to tell you that the brand new account's activity is "in violation of one or more of our policies", despite its having done absolutely nothing. No, really, _every four minutes._ I don't know if SendGrid is aware of the irony in spamming a user who is suspected of spamming despite having sent no emails.
      ![image](https://user-images.githubusercontent.com/1725499/110277487-3537dd00-7f8a-11eb-8206-0595e18969c1.png)
2. **A third-party SendGrid account still works.** That is: User can create their own SendGrid account, possibly via the GitHub Education Pack if they're eligible. Then they configure Heroku to use that SendGrid account using config vars, _without the SendGrid add-on_, as suggested in [current docs](https://tabbycat.readthedocs.io/en/v2.5.7/install/heroku.html#sendgrid-account-details).
3. **No known automatically provisioned alternative via Heroku.** We're not currently aware of any Heroku-based solution that allows us to recreate the seamlessness we had when we introduced SendGrid emails back in 2016.
4. **Several known third-party solutions.**
    - [Calico](https://www.calicotab.com/) (run by @tienne-B) provides the email integration itself, so Calico users are unaffected by this issue.
    - Users can configure (e.g.) a Gmail account directly, so long as their use doesn't fall foul of Gmail's policies.
    - Can use third-party mail merge solutions, see Facebook post above for products users have reported using.

Current plan:
- [ ] Remove SendGrid from automatic provision.
- [ ] Update docs to advise more clearly through personal SendGrid account instructions.
- [ ] Update docs to reference other third-party solutions.
- [x] Investigate [other email apps on Heroku Elements](https://elements.heroku.com/addons/categories/email-sms).

**Comment by tienne-B** [comment]
Quick ref: 29bf76aff2267bce70006f0ab5167b304256b430

**Comment by czlee** [comment]
I tried the [Mailgun add-on on Heroku](https://elements.heroku.com/addons/mailgun). It didn't spam me every four minutes from the time I created the account, and it gave a useful error message when I tried to send the first email (that sandbox domains are for testing only and can only be used to send to authorized recipients). From there, it's subject to the same limitation as SendGrid: You must add a verified domain before you can send emails more generally, and you must add a credit card before you can add a verified domain. Since adding a verified domain requires adding a DNS record to a domain name that you own, this is out of reach of most people, so in this sense is probably worse than SendGrid, which at least permits "Single Sender Verification". My assessment is therefore that automatically provisioning a Mailgun add-on is also no good. It's probably a reasonable third-party service in the right context, but it seems easier (or at least no harder) to advise users to create an account outside Heroku and use that instead.

**Comment by czlee** [comment]
… and I don't think [any other add-ons](https://elements.heroku.com/addons/categories/email-sms) are intended for sending lots of emails, so it seems like automatically provisioned add-ons are a no-go. Potentially we could add instructions for Mailgun, but I feel like it's unlikely that adding documentation that's only useful for people who control a DNS record is worthwhile.
