### ISSUE TITLE
Internal server error report

### ISSUE THREAD

**Issue by jennyfoggin** [TabbycatDebate/tabbycat#1756]
I hit an internal server error while trying to load this URL:
https://waikatoschoolsdebating.herokuapp.com/senioropen/admin/draw/round/2/create/
https://waikatoschoolsdebating.herokuapp.com/JrOpen2021/admin/draw/round/2/create/
https://waikatoschoolsdebating.herokuapp.com/JrNovice2021/admin/draw/round/2/create/

Please describe what you were doing when the error happened, along with any other useful information:
Trying create a draw for the second round of the tournament and it sends me this error issue with all divisions of the round.

**Comment by tienne-B** [comment]
Change the _Intermediate bracket resolution method_ in Draw Rules to a method without preallocated sides.
