### ISSUE TITLE
Add team-specific passwords for the online feedback system

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#179]
Probably doesn't need to be built into Django's actual authentication system, rather just a simple string attached to each `Team` that is checked before allowing online feedback submissions.

**Comment by czlee** [comment]
To be honest, building into Django's authentication system is probably easier =P

**Comment by czlee** [comment]
See also #193

**Comment by philipbelesky** [comment]
Going to close this now as I think it is largely superseeded by the hash functionality in #193 . We can re-open or remake in future if there is ever a need for passwords over hashes.

**Comment by czlee** [comment]
It's probably worth keeping on the backburner anyway, maybe keep the issue open and don't mark it for a milestone? The hash functionality isn't really a matching substitute.

**Comment by tienne-B** [comment]
#193 does seem to fill the same use-case, but even if we wanted a second layer of security, this is just another hurdle to submit feedback; another thing to look up or remember. Closing as won't fix.
