### ISSUE TITLE
open windows_docker_start.bat Run Tabbycat in Docker not running

### ISSUE THREAD

**Issue by fadloero1010** [TabbycatDebate/tabbycat#1795]
we were unsuccessful to install tabbycat in docker desktop 3.3.3 (64133) and OS Windows 10 Pro Education 64Bit
location file C:\Users\Fadloe\Documents\tabbycat\bin

![Screenshot 2021-05-25 at 5 49 45 PM](https://user-images.githubusercontent.com/82032976/119477656-b761c180-bd81-11eb-8154-0875e20fa2bc.png)

**Comment by philipbelesky** [comment]
Hey, thanks for the report. I've tried this with the latestDocker Desktop on Windows 10 without an issue. Could you confirm which version of Tabbycat you downloaded? I think Docker in `develop` might be a bit unstable, but did you use the `zip` from the 2.5.8 release tab? Could you also check in the Docker settings and see if you are using the WSL based setup or the Hyper-V based setup?

**Comment by tienne-B** [comment]
Answered and no reply in many years.
