### ISSUE TITLE
Verify email HTML outside of consumer

### ISSUE THREAD

**Issue by tienne-B** [TabbycatDebate/tabbycat#1812]
Other than the email provider not working, another invisible error is with the use of malformed messages. Maybe test that the form is correct before sending off the consumer.

**Comment by tasdidtahsin** [comment]
You can see this as an example of a badly formatted HTML email body 

> <div><span style="font-size: 24px;"><span style="font-weight: bolder;">Hi {{ USER }},</span></span></div><div><br></div><div><span style="font-size: 18px;">We welcome you to&nbsp;</span><span style="font-weight: bold; font-size: 18px;">{{&nbsp;TOURN }}</span><span style="font-size: 18px;">. Here we are using an online tabulation system and a virtual tab assistant,﻿&nbsp;</span><span style="font-weight: bold; font-size: 18px;">TabbyBot</span><span style="font-size: 18px;">. You can register, checkin and do many things through the bot, using your&nbsp;</span><span style="font-weight: bold; font-size: 18px;">Identification Key.</span><span style="font-size: 18px;">&nbsp;This Identification Key is unique to you — do not share it with anyone, as anyone who knows it can register as you and submit data on your behalf.&nbsp;</span></div><div><br></div><div><span style="font-size: 24px;">Your personal private</span><span style="font-weight: bold; font-size: 24px;">&nbsp;Identification Key</span><span style="font-size: 24px;">&nbsp;is:&nbsp;</span><span style="font-weight: bold; font-size: 24px;">{{ KEY }}</span></div><div><br></div><div><span style="font-size: 24px;"><a href="https://discord.gg/Z2CKyGhDyq" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://discord.gg/Z2CKyGhDyq&amp;source=gmail&amp;ust=1623303436009000&amp;usg=AFQjCNHWIjcuGbvfjQojKEVmZpmZKQbJIw">Link to the discord server:&nbsp;</a></span><a href="https://discord.gg/Z2CKyGhDyq" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://discord.gg/Z2CKyGhDyq&amp;source=gmail&amp;ust=1623303436009000&amp;usg=AFQjCNHWIjcuGbvfjQojKEVmZpmZKQbJIw" style="color: rgb(0, 0, 255);"><span style="font-size: 24px; background-color: rgb(255, 156, 0); font-style: italic;">https://discord.gg/<wbr>Z2CKyGhDyq</span></a></div><div><br></div><div><span style="font-size: 18px;">To register yourself, go to&nbsp;</span><span style="font-weight: bold; color: rgb(255, 255, 255); background-color: rgb(0, 0, 0); font-size: 18px;">#registration</span><span style="font-size: 18px;">&nbsp;text channel in the tournament server, just type:</span>&nbsp;<span style="font-size: 24px;">&nbsp;</span><span style="font-weight: bold; color: rgb(255, 255, 255); background-color: rgb(0, 0, 0); font-size: 24px;">?register {{ KEY }}</span><span style="font-size: 24px;">&nbsp;</span></div><div><br></div><div><span style="font-size: 18px;">You can also submit your ballots and/or feedback using the private URL:&nbsp;&nbsp;</span><span style="font-weight: bold; font-size: 18px;">{{ URL }}</span><span style="font-size: 18px;">&nbsp;&nbsp;</span></div><div><br></div><div><span style="font-size: 18px;">This URL will be also given by the bot in your discord inbox after you register.</span></div><div><div><span style="font-size: 18px;">Check out the&nbsp;</span><a href="https://ebdp2021.calicotab.com/ebdpnovice2021/participants/list/" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://ebdp2021.calicotab.com/ebdpnovice2021/participants/list/&amp;source=gmail&amp;ust=1623303436009000&amp;usg=AFQjCNE-PfGgp2566QW0F6z09iBQpeVtHg" style="color: rgb(0, 0, 255); background-color: rgb(255, 156, 0);"><span style="font-size: 18px; font-style: italic;">Participant List</span></a><span style="font-size: 18px;">&nbsp;and fill your valid clashes in&nbsp;</span><a href="https://forms.gle/zo7RuNLXrvT6TotJA" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://forms.gle/zo7RuNLXrvT6TotJA&amp;source=gmail&amp;ust=1623303436009000&amp;usg=AFQjCNG1V2_ABkeyeTBPd7LciJMqpHyC6g" style="color: rgb(0, 0, 255); background-color: rgb(255, 156, 0);"><span style="font-size: 18px; font-style: italic;">Clash Form</span></a><span style="font-size: 18px;">.</span></div><div><span style="font-size: 18px;">Clashes can be submitted till the draw release of Round 1.</span></div><div><br></div><div><span style="font-size: 18px;">Check out our&nbsp;</span><a href="https://docs.google.com/document/d/1TmZKO0Ora8KTCvMTQlvxLLjAmiWK5wgod_gJvMAQzFU/edit?usp=sharing" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://docs.google.com/document/d/1TmZKO0Ora8KTCvMTQlvxLLjAmiWK5wgod_gJvMAQzFU/edit?usp%3Dsharing&amp;source=gmail&amp;ust=1623303436009000&amp;usg=AFQjCNHBbdlrDnRHY1l5rJN2F8ydIw1MCQ" style="color: rgb(0, 0, 255); background-color: rgb(255, 156, 0);"><span style="font-size: 18px; font-style: italic;">Equity Policy</span></a><span style="font-size: 18px;">&nbsp;&amp;&nbsp;</span><a href="https://forms.gle/EcuUeUYbyF9vLvtdA" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://forms.gle/EcuUeUYbyF9vLvtdA&amp;source=gmail&amp;ust=1623303436009000&amp;usg=AFQjCNHzzNvoeob4BVQ3cFibFlQ2StV1zw" style="color: rgb(0, 0, 255); background-color: rgb(255, 156, 0);"><span style="font-size: 18px; font-style: italic;">Equity Complaint Form</span></a><span style="font-size: 18px;">.</span></div></div><div><br></div><div><span style="font-size: 18px;"><span style="font-weight: bolder;">Regards,</span></span></div><div><span style="font-size: 18px;"><span style="font-weight: bolder;">Shuvro, Sarjil, Umid &amp; Tasmia</span></span></div><div><span style="font-size: 18px;"><span style="font-weight: bolder;">Tab Team</span></span><br></div><div><span style="font-size: 18px; font-weight: bold;">{{ TOURN }}</span></div>

```<div><span style="font-size: 24px;"><span style="font-weight: bolder;">Hi {{ USER }},</span></span></div><div><br></div><div><span style="font-size: 18px;">We welcome you to&nbsp;</span><span style="font-weight: bold; font-size: 18px;">{{&nbsp;TOURN }}</span><span style="font-size: 18px;">. Here we are using an online tabulation system and a virtual tab assistant,﻿&nbsp;</span><span style="font-weight: bold; font-size: 18px;">TabbyBot</span><span style="font-size: 18px;">. You can register, checkin and do many things through the bot, using your&nbsp;</span><span style="font-weight: bold; font-size: 18px;">Identification Key.</span><span style="font-size: 18px;">&nbsp;This Identification Key is unique to you — do not share it with anyone, as anyone who knows it can register as you and submit data on your behalf.&nbsp;</span></div><div><br></div><div><span style="font-size: 24px;">Your personal private</span><span style="font-weight: bold; font-size: 24px;">&nbsp;Identification Key</span><span style="font-size: 24px;">&nbsp;is:&nbsp;</span><span style="font-weight: bold; font-size: 24px;">{{ KEY }}</span></div><div><br></div><div><span style="font-size: 24px;"><a href="https://discord.gg/Z2CKyGhDyq" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://discord.gg/Z2CKyGhDyq&amp;source=gmail&amp;ust=1623303436009000&amp;usg=AFQjCNHWIjcuGbvfjQojKEVmZpmZKQbJIw">Link to the discord server:&nbsp;</a></span><a href="https://discord.gg/Z2CKyGhDyq" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://discord.gg/Z2CKyGhDyq&amp;source=gmail&amp;ust=1623303436009000&amp;usg=AFQjCNHWIjcuGbvfjQojKEVmZpmZKQbJIw" style="color: rgb(0, 0, 255);"><span style="font-size: 24px; background-color: rgb(255, 156, 0); font-style: italic;">https://discord.gg/<wbr>Z2CKyGhDyq</span></a></div><div><br></div><div><span style="font-size: 18px;">To register yourself, go to&nbsp;</span><span style="font-weight: bold; color: rgb(255, 255, 255); background-color: rgb(0, 0, 0); font-size: 18px;">#registration</span><span style="font-size: 18px;">&nbsp;text channel in the tournament server, just type:</span>&nbsp;<span style="font-size: 24px;">&nbsp;</span><span style="font-weight: bold; color: rgb(255, 255, 255); background-color: rgb(0, 0, 0); font-size: 24px;">?register {{ KEY }}</span><span style="font-size: 24px;">&nbsp;</span></div><div><br></div><div><span style="font-size: 18px;">You can also submit your ballots and/or feedback using the private URL:&nbsp;&nbsp;</span><span style="font-weight: bold; font-size: 18px;">{{ URL }}</span><span style="font-size: 18px;">&nbsp;&nbsp;</span></div><div><br></div><div><span style="font-size: 18px;">This URL will be also given by the bot in your discord inbox after you register.</span></div><div><div><span style="font-size: 18px;">Check out the&nbsp;</span><a href="https://ebdp2021.calicotab.com/ebdpnovice2021/participants/list/" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://ebdp2021.calicotab.com/ebdpnovice2021/participants/list/&amp;source=gmail&amp;ust=1623303436009000&amp;usg=AFQjCNE-PfGgp2566QW0F6z09iBQpeVtHg" style="color: rgb(0, 0, 255); background-color: rgb(255, 156, 0);"><span style="font-size: 18px; font-style: italic;">Participant List</span></a><span style="font-size: 18px;">&nbsp;and fill your valid clashes in&nbsp;</span><a href="https://forms.gle/zo7RuNLXrvT6TotJA" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://forms.gle/zo7RuNLXrvT6TotJA&amp;source=gmail&amp;ust=1623303436009000&amp;usg=AFQjCNG1V2_ABkeyeTBPd7LciJMqpHyC6g" style="color: rgb(0, 0, 255); background-color: rgb(255, 156, 0);"><span style="font-size: 18px; font-style: italic;">Clash Form</span></a><span style="font-size: 18px;">.</span></div><div><span style="font-size: 18px;">Clashes can be submitted till the draw release of Round 1.</span></div><div><br></div><div><span style="font-size: 18px;">Check out our&nbsp;</span><a href="https://docs.google.com/document/d/1TmZKO0Ora8KTCvMTQlvxLLjAmiWK5wgod_gJvMAQzFU/edit?usp=sharing" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://docs.google.com/document/d/1TmZKO0Ora8KTCvMTQlvxLLjAmiWK5wgod_gJvMAQzFU/edit?usp%3Dsharing&amp;source=gmail&amp;ust=1623303436009000&amp;usg=AFQjCNHBbdlrDnRHY1l5rJN2F8ydIw1MCQ" style="color: rgb(0, 0, 255); background-color: rgb(255, 156, 0);"><span style="font-size: 18px; font-style: italic;">Equity Policy</span></a><span style="font-size: 18px;">&nbsp;&amp;&nbsp;</span><a href="https://forms.gle/EcuUeUYbyF9vLvtdA" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://forms.gle/EcuUeUYbyF9vLvtdA&amp;source=gmail&amp;ust=1623303436009000&amp;usg=AFQjCNHzzNvoeob4BVQ3cFibFlQ2StV1zw" style="color: rgb(0, 0, 255); background-color: rgb(255, 156, 0);"><span style="font-size: 18px; font-style: italic;">Equity Complaint Form</span></a><span style="font-size: 18px;">.</span></div></div><div><br></div><div><span style="font-size: 18px;"><span style="font-weight: bolder;">Regards,</span></span></div><div><span style="font-size: 18px;"><span style="font-weight: bolder;">Shuvro, Sarjil, Umid &amp; Tasmia</span></span></div><div><span style="font-size: 18px;"><span style="font-weight: bolder;">Tab Team</span></span><br></div><div><span style="font-size: 18px; font-weight: bold;">{{ TOURN }}</span></div>```

**Comment by tienne-B** [comment]
For context, the first error in the message is on column 239 with the insertion of a non-breaking space (`&nbsp;`) which causes a `TemplateSyntaxError`: "Could not parse the remainder: '&nbsp;TOURN' from '&nbsp;TOURN'"
