### ISSUE TITLE
Internal server error report

### ISSUE THREAD

**Issue by titianZega** [TabbycatDebate/tabbycat#1830]
I hit an internal server error while trying to load this URL:
https://tabbycat-groupb.herokuapp.com/bp88team/admin/

Please describe what you were doing when the error happened, along with any other useful information:
Im upgrading the app from fork repo of tabbycat, when i try the app after deploy and go to the administrator tab i get an error.

**Comment by tienne-B** [comment]
Sometimes Heroku doesn't migrate completely, you can try using the Console in your Heroku Dashboard (Under "More") and type `dj migrate` to make sure all is set. You may also delete and recreate the site.
