### ISSUE TITLE
Internal server error report

### ISSUE THREAD

**Issue by jennyfoggin** [TabbycatDebate/tabbycat#1835]
I hit an internal server error while trying to load this URL:
https://waikatoschoolsdebating.herokuapp.com/database/tournaments/round/?tournament__id__exact=7

Please describe what you were doing when the error happened, along with any other useful information:

Im trying to delete a tournament but unable to do so. I cannot delete rounds or teams etc or the whole tournament itself. I have hit too many rows so by deleting this tournament it will free up rows hopefully.

**Comment by tienne-B** [comment]
Seems that you already exceeded your limits and so write access was revoked. Even though deleting a tournament frees rows, deletion is logged, and that one added row is preventing deletion. Need to [upgrade the database](https://devcenter.heroku.com/articles/upgrading-heroku-postgres-databases) or migrate to another service (I've used ElephantSQL and Calico).
