### ISSUE TITLE
Documentation: Remove outdated reference to "welcome message" field in the database

### ISSUE THREAD

**Issue by thbsp** [TabbycatDebate/tabbycat#1839]
At this location in the documentation:
> Using Tabbycat
> --> Starting a Tournament
> --> Special data types and options
> --> Tournaments > Tournaments
> "Note that tournaments can have a welcome message (useful for displaying maps and other information on the homepage)."

This information is out of date. The welcome message is actually found in the admin section of the tab under settings --> configuration --> public features.
Since it's no longer hard to find this welcome message option, this item in the documentation can just be deleted.

**Comment by philipbelesky** [comment]
Hey, thanks for the report. I've updated the docs to remove this reference as it is (hopefully) relatively clearly documented in the settings area itself.
