### ISSUE TITLE
Update outdated interface screenshots in the documentation

### ISSUE THREAD

**Issue by thbsp** [TabbycatDebate/tabbycat#1840]
In the documentation, there are a number of screenshots of the admin interface that show an older version of Tabbycat. (How old, I'm not sure.)

These are the locations:
* Importing initial data
* * Simple importer screenshot
* * Add institutions screenshot
* * Add teams (1 of 2) screenshot
* * Add teams (2 of 2) screenshot
* Running a tournament
* * "Checkins overview" screenshot
* * "Draw for Round 2 (draft draw)" screenshot
* * "Draw for Round 2 (confirmed draw)" screenshot
* * "Results" screenshot

**Comment by philipbelesky** [comment]
Thanks for the report, these cases should all be fixed now!
