### ISSUE TITLE
Change 'trans-' template tags

### ISSUE THREAD

**Issue by tienne-B** [TabbycatDebate/tabbycat#1872]
The `trans` and `blocktrans` tags have been deprecated in Django 3.2 in favour of `translate` and `blocktranslate`. We might want to change.

https://docs.djangoproject.com/en/3.2/topics/i18n/translation/

**Comment by czlee** [comment]
Interesting! Any chance in functionality, or is it just a renaming?

**Comment by tienne-B** [comment]
Just a renaming.

**Comment by czlee** [comment]
Link to release notes for future reference: https://docs.djangoproject.com/en/3.2/releases/3.1/#templates
