### ISSUE TITLE
Docker compose issue on MacOS

### ISSUE THREAD

**Issue by Joshuah143** [TabbycatDebate/tabbycat#1929]
When I downloaded release 2.6.4 and ran the `osx_docker_start.command` file I got this error: `Error response from daemon: pull access denied for tabbycat, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

It seems to be some docker config error, should I have added the DB and redis details first?

I did my best to follow the instructions [posted to the docs](https://tabbycat.readthedocs.io/en/stable/install/docker.html) but, for some reason, it didn't work. I'm a newbie to docker so this is likely a pretty dumb mistake. Thanks for your help in advance!

Steps taken:
1. Download from GitHub
2. Download Docker
3. Open Docker
4. Run `docker login`
2. Navigate to file and run `osx_docker_start.command`

Versions:
- OSX = 12.0.1
- Docker = 20.10.11
- TabbyCat = 2.6.4

Command line:

> USER@MACHINE tabbycat-2.6.4 % /Users/USER/Downloads/tabbycat-2.6.4/bin/osx_docker_start.command
> [+] Running 0/4
>  ⠿ redis Error                                                                                                                                                                                         2.1s
>  ⠿ worker Error                                                                                                                                                                                        2.1s
>  ⠿ db Error                                                                                                                                                                                            2.1s
>  ⠿ web Error                                                                                                                                                                                           2.1s
> Error response from daemon: pull access denied for tabbycat, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Also, just to note, the reason that I am trying to use docker instead of a traditional local install is that I'm hoping to be able to put the container on Google Cloud. So any advice specific to that is very welcome!

**Comment by Joshuah143** [comment]
Update:

Fixed by replacing `image: Tabbycat` with `build: .` in the docker-compose.yaml file for both worker and web services.

Should I submit a PR for this or just leave it as a one-off in my setup? I'm more than happy to submit one.

**Comment by tienne-B** [comment]
Mind submitting a PR?

**Comment by Joshuah143** [comment]
Created pull request, worked for me after making the change

**Comment by tienne-B** [comment]
Closed with #1931
