### ISSUE TITLE
Source code deploy

### ISSUE THREAD

**Issue by VAT97** [TabbycatDebate/tabbycat#1956]
Cannot deploy tabby cat on Herokuapp

**Comment by philipbelesky** [comment]
Thanks for letting me know. It looks like there is an issue on Heroku's end that is preventing new deployments from this repo. 

We've contacted Heroku, but in the meantime you should be able to [deploy using this link](https://heroku.com/deploy?template=https://github.com/philipbelesky/tabbycat/tree/master).

**Comment by VAT97** [comment]
Hi, we are still having trouble  creating new tab for our tournaments

**Comment by tienne-B** [comment]
Heroku doesn't look at their tickets during the weekend, but they'll try to get back to us on Monday or Tuesday. This is really out of our control; sorry.

**Comment by VAT97** [comment]
Noted
I really understand and appreciate all your help

Regards,
VAT

**Comment by tienne-B** [comment]
Don't really see an action to be taken with this task.
