### ISSUE TITLE
[Suggestion] Enter ballots via API

### ISSUE THREAD

**Issue by gserranof** [TabbycatDebate/tabbycat#1971]
Hi there! Amazing work you all have done and continue doing - I feel it's never recognised enough the humongous impact you have made worldwide. That said, feel free to close if I'm just blind.

I'm working with the API for an app I'm programing on my spare time and, unless I'm wrong, there seems to be no way to submit ballots via the API. That seems a little weird to me, given that it's possible to do with the API almost everything else the average user would do within Tabbycat - from entering feedback to read the motions, even the more "private" things like retrieving private urls are possible. That's why not being able to submit ballots seems odd to me, and I think that would be an amazing adition to the API given the obvious prominence of that feature on every round and tournament.

As said, I may be completely blind and that is actually possible, but God knows I've searched it ad nauseaum within the Swagger schema.

**Comment by tienne-B** [comment]
You are able to, using the [`/v1/tournaments/{tournament_slug}/rounds/{round_seq}/pairings/{debate_pk}/ballots`](https://app.swaggerhub.com/apis-docs/tienne-B/tabbycat-api/v1.1.0#/v1/v1_tournaments_rounds_pairings_ballots_create) endpoint.
