### ISSUE TITLE
Add ability to manage venue category constraints to the API

### ISSUE THREAD

**Issue by CreatedBySeb** [TabbycatDebate/tabbycat#1972]
Currently you are able to create and manage venue categories, including adding venues to them, via the API, however you cannot create or manage venue constraints using them. Using venue constraints to enforce streaming consent is a fairly common use case for me of venue constraints, so being able to add this data programmatically from an external registration tools could be extremely useful. As in person competitions return I imagine this would also be helpful for making it easier for tournament organisers to ensure accessibility to venues.

I am unsure how this is currently structured in the database so I am unsure what would be the easier way to implement this. Placing this on teams or adjudicators like conflicts currently are would probably make the most sense with the current API schemas, but if it's easier it would work fine on the venue categories themselves too.

**Comment by tienne-B** [comment]
I'd go about it by adding a `venue_constraints` field to the participant endpoints, treating the model as a M2M field with an extra `priority` field.
```json
{
  "venue_constraints": [
    {
      "category": "",
      "priority": 0
    }
  ]
}
```
