### ISSUE TITLE
Add render.com deployment method

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#1975]
Relates to #438, but probably wouldn't close it as further options would also be valuable. Current progress:

- [X] Basic django/postgres setup running with static assets
- [x] See if running redis as a docker image will work / not trigger payment
- [x] Setup a combined WSGI/ASGI environment
- [x] Write docs / setup button

If/when merged, this might be a chance to simplify the setup environment to remove some of the Heroku-specific workarounds and some of the more complicated performance optimisations. We would also need to be careful with cross compatibility for Calico/Docker.

**Comment by philipbelesky** [comment]
Ok, all of those original task are completed. The only remaining major issue is that the `runworker` process throws when using redis as the backing layer. When using the in-memory layer it just silently does nothing. 

As a sidenote, I don't think Render actually has a Heroku style 30-second dyno timeout, so if this is intractable then it might not be the worst thing to shift things back to running on normal server processes.

**Comment by tienne-B** [comment]
Would this be finished, as the Render branch is merged in?

**Comment by philipbelesky** [comment]
Yes!
