### ISSUE TITLE
Disable deletion of action log entries

### ISSUE THREAD

**Issue by tienne-B** [TabbycatDebate/tabbycat#1988]
Action log entries can be deleted through the Database interface, which can remove important information about who changed what. It should be possible to disable deletion, at least in the Database user interface to avoid potential abuse.

**Comment by philipbelesky** [comment]
Sounds good. Is there any use case for allowing action log deletions (in any case?). Eg should we just hardcode them to be uneditable? The only reason I can think of is to reclaim database rows, but I don't think that sort of heroku catering is worth worrying about any more.

**Comment by tienne-B** [comment]
Done in 47ef9727a314e85fd6534bb566835054e396f337
