### ISSUE TITLE
auto allocate adjudicators not working

### ISSUE THREAD

**Issue by SuveerGoyal** [TabbycatDebate/tabbycat#1996]
I was trying to test the software using the 8-generic team dataset but for some reason The auto adjudication allocate does not seem to be working and is stuck on loading.

**Comment by tienne-B** [comment]
There's not enough information here. Is your Redis running and connected?

**Comment by SuveerGoyal** [comment]
> 

yes it is connected and running

**Comment by tienne-B** [comment]
Closing as inactive and not enough information to act upon. Feel free to re-comment to continue this.
