### ISSUE TITLE
Quote secret_key variable in deploy_heroku.py

### ISSUE THREAD

**Issue by dcorks** [TabbycatDebate/tabbycat#2009]
On Windows, deploying Tabbycat through Heroku CLI gives errors when setting `DJANGO_SECRET_KEY` to `secret_key`, if `secret_key` contains certain special characters, such as `&` and `)`. See screenshot below.

I think this can be fixed by adding quotes to the `secret_key` string in line 183 of `deploy_heroku.py`.

Change:
`command = ["config:set", "DISABLE_COLLECTSTATIC=1", "DJANGO_SECRET_KEY=%s" % secret_key]`
to:
`command = ["config:set", "DISABLE_COLLECTSTATIC=1", "DJANGO_SECRET_KEY=%s" % "\"" + secret_key + "\""]`

I've never programmed in Python and I learned the syntax above about 3 minutes ago with a few Google searches. Maybe there's a smarter way to escape the string? Either way, let me know and I'll make a pull request.

![image](https://user-images.githubusercontent.com/18520229/161408821-a7edc652-105b-48fe-a107-24982377813c.png)

**Comment by philipbelesky** [comment]
Hey, thanks for opening this issue, this had been on my TODO list. I tried the approach/syntax you suggested, however, it ends up adding the `"` characters to the variable itself on Heroku. Looking into it further it seems like there are differences between the different types of command line on Windows as well.

As a lazier and simpler alternative I've changed the function that makes the key to only generate alphanumerics that don't need to be escaped. Did you want to try things on your end? You can [copy the updated script over from here](https://github.com/TabbycatDebate/tabbycat/blob/hotfix/2.6.7/deploy_heroku.py).

PS: I've added a credit in our CHANGELOG, let me know if you'd like to be identified differently to your username.

**Comment by czlee** [comment]
Yeah it's super strange, I think Unix systems take the arguments to `subprocess.call` (or `.check_output`) and pass them straight through so they don't need to be escaped (and will not be interpreted as if they were shell syntax). It surprises me a little that this doesn't happen on Windows, or that there's no obvious OS-agnostic solution to this.

**Comment by dcorks** [comment]
> I tried the approach/syntax you suggested, however, it ends up adding the `"` characters to the variable itself on Heroku.
> As a lazier and simpler alternative I've changed the function that makes the key to only generate alphanumerics that don't need to be escaped.
I thought about that issue but since `secret_key` is only used in that one place I wasn't sure if it would be a problem. But changing the characters used in the original function is much simpler.

> PS: I've added a credit in our CHANGELOG, let me know if you'd like to be identified differently to your username.
I just changed my user name to dcorks. That's close enough to my actual name for attribution purposes. Thanks for checking.

**Comment by philipbelesky** [comment]
Easy! I've just released this change as a hotfix so it should work for all new deploys.

**Comment by czlee** [comment]
Hey @dcorks, just a heads-up that (as part of other changes) I've modified the line that implements this slightly in 51753bdf7336e4ac00e7037ee18e8f61fb3c633f. It should be the same, but let me know if it breaks! It isn't intended to change functionality so won't be released until the next (non-patch) version.
