### ISSUE TITLE
Internal server error report . Nothing is eligible to be deleted.

### ISSUE THREAD

**Issue by adnancemkiral** [TabbycatDebate/tabbycat#2050]
I hit an internal server error while trying to load this URL:
https://yeditepeacik2021.herokuapp.com/database/venues/venue/?tournament__id__exact=5

Please describe what you were doing when the error happened, along with any other useful information:

**Comment by adnancemkiral** [comment]
Hi! I could not be deleted either tournament, or debate draws, either round from the application. I need raws. Unfortunately, there is no budget for the new rows. No more tabbycat applications are created. Callico-tab website wants money too that is too costly to be afforded. What should be done? Can someone help me please. Thank you in advance.

**Comment by tienne-B** [comment]
Nothing really actionable here; this is a database administration problem (permission denied for table django_admin_log).
