### ISSUE TITLE
Automatise the generation of the API Schema

### ISSUE THREAD

**Issue by tienne-B** [TabbycatDebate/tabbycat#2061]
The documentation for the API, in `api-schema.yml`, is updated manually when changes are applied. However, it should be possible with DRF to automatically generate that file, as shown in [their docs](https://www.django-rest-framework.org/api-guide/schemas/). It seems that the roadblock is with our nested endpoints.

**Comment by czlee** [comment]
I can't believe "automatise" [is a word](https://www.collinsdictionary.com/us/dictionary/english/automatize), I always say "automate" 😂
