### ISSUE TITLE
Internal server error report

### ISSUE THREAD

**Issue by ERNEST9009** [TabbycatDebate/tabbycat#2080]
I hit an internal server error while trying to load this URL:
https://midyeardebates2k22.calicotab.com/database/

Please describe what you were doing when the error happened, along with any other useful information:
Hi we have a tourney coming up in less than 12 hours and we cannot edit the data base due to internal server error 500. Would greatly appreciate a prompt reply

**Comment by ERNEST9009** [comment]
Hi is there an estimated time of fixing? Thank you

**Comment by tienne-B** [comment]
Sorry for the delay! Your site should be good now.

**Comment by ERNEST9009** [comment]
Yup its good thank you
