### ISSUE TITLE
Update emoji list

### ISSUE THREAD

**Issue by tienne-B** [TabbycatDebate/tabbycat#2081]
Our current emoji list goes up to the emojis introduced in Unicode 11.0. However, the stable and widespread version of Unicode is currently 13. For this task, you will need to:
* Add new sections for the updates of Unicode in our [Emoji spreadsheet](https://docs.google.com/spreadsheets/d/1cUFyOSjqovZOlB_bqzr6slS9E36IsMhIiook0RXfFR0/edit#gid=0) (available on request)
* Mark emoji with exclusion criteria / rename to be fun
* Copy the new sections over to `emoji.py`.

We use [Emojipedia](https://emojipedia.org/unicode-12.0/) for lists of emoji.

**Comment by daankoning** [comment]
Hi, can I be assigned? I would love to help.

**Comment by tienne-B** [comment]
Sure; added. Mind requesting access to the Emoji spreadsheet? How it works is that the emojis are added to the spreadsheet, and then it generates the code which you can then add to `emoji.py`.

**Comment by czlee** [comment]
@daankoning shared, thanks! don't hesitate to ask if you have any questions

**Comment by daankoning** [comment]
Thanks a bunch to both of you! On it as we speak ❤️ :
