### ISSUE TITLE
Clarify header of checkins

### ISSUE THREAD

**Issue by tienne-B** [TabbycatDebate/tabbycat#2088]
<img width="1442" alt="Screen Shot 2022-07-21 at 13 05 22" src="https://user-images.githubusercontent.com/6293465/180199316-0ff248e1-0e6d-4a47-b318-4a6eb547a228.png">

I feel that the two center filters are confusing as "Debaters" brings teams and "By Speaker" includes Adjudicators, so the header should be clarified.

**Comment by philipbelesky** [comment]
Maybe: `All | Only Adjudicators | Only Teams` and `As Speakers | As Teams`?

**Comment by tienne-B** [comment]
Maybe for the 2nd: `As People | As Teams`

**Comment by tienne-B** [comment]
Fixed with #2113 (15db67c63b1659528cd57498bb802a2055d002de)
