### ISSUE TITLE
Upgrade heroku stack, current heroku-18 stack soon will be deprecated

### ISSUE THREAD

**Issue by BetaUliansyah** [TabbycatDebate/tabbycat#2123]
I think its the time to redo #1503 again. Heroku-18 soon [will be deprecated](https://help.heroku.com/X5OE6BCA/heroku-18-end-of-life-faq).

**Comment by tienne-B** [comment]
The wider discussion is whether we should continue natively supporting Heroku at all, taking into consideration that the free tier will be removed much earlier than when the heroku-18 stack will be unsupported. The free tier is what attracted us and our users to Heroku; with that gone there'll be much less interest.

**Comment by tienne-B** [comment]
Done, updated to Heroku-22.
