### ISSUE TITLE
when I send the custom email, it is not reading the code and does not send the url

### ISSUE THREAD

**Issue by superfer0412** [TabbycatDebate/tabbycat#2126]
help me with a problem
i am trying to send the private url's i put the code {{ URL }} but when the message arrives the url does not appear only the code the same thing happens with the other codes like {{ TOURN }}

**Comment by tienne-B** [comment]
Didn't notice this ticket; sorry. What site is this for and the version? What happens sometimes is that if you copy-paste the message, the HTML gets mangled and so the variables are no longer recognized.

**Comment by TrudeauOkech** [comment]
Hey @tienne-B @superfer0412 
I am experiencing the same problem now. Did you find a way around it?
{{ USER }} seems to the the only one working, all the rest e.g {{ URL }} and {{ TOURN }} just come back blank

**Comment by tienne-B** [comment]
There's really not enough information here... What was your template, Tabbycat version, hosting, etc? The next version will have a new framework for sending emails so this may not be applicable. I suggest using our Facebook group if you encounter problems: https://www.facebook.com/groups/tabbycat.debate
