### ISSUE TITLE
Internal server error report

### ISSUE THREAD

**Issue by GenesisRhapshodos** [TabbycatDebate/tabbycat#2140]
I hit an internal server error while trying to load this URL:
https://binova.herokuapp.com/database/results/speakerscore/1424/delete/

I want to delete old tournament tab but the internal server error notice keeps appearing even when attempting to delete smaller data (i.e speaker score etc)

![image](https://user-images.githubusercontent.com/101701946/193744095-afb5b123-edb7-4a3f-a0da-43d2d1324132.png)

Edit: Update, every action made in the database also shows the 500 error page.

**Comment by tienne-B** [comment]
I'm seeing the error `permission denied for table django_admin_log`, so you might have to change the owner of the `django_admin_log` table with this SQL command: `ALTER TABLE public.django_admin_log OWNER TO CURRENT_USER;`. Also, we don't support version 2.2 anymore; we're at version 2.7 now. Please upgrade. The instructions [are in the docs](https://tabbycat.readthedocs.io/en/stable/install/heroku.html#upgrading-an-existing-heroku-app).
