### ISSUE TITLE
README.md links to dead tab

### ISSUE THREAD

**Issue by daankoning** [TabbycatDebate/tabbycat#2144]
The first link in `README.md`, which is supposed to go to the WUDC 2020 tab. This tab has, however, gone offline. It should probably be changed to a more recent example.

**Comment by tienne-B** [comment]
The new URL for WUDC 2020 is https://wudc2020.calicotab.com/ . It could be nice to use the most recent, WUDC 2022 as an example: https://wudc2022.calicotab.com/ . Would you want to make the PR for that?
