### ISSUE TITLE
Round 1 seeding

### ISSUE THREAD

**Issue by nathanielyoon** [TabbycatDebate/tabbycat#2165]
In APDA, round 1 pairings/judge allocations are based on seeding. Individual debaters are considered seeded if they've qualified to the national tournament, and teams are either fully-, half-, or un-seeded. Pairings are high-low based on the level of a team's seeding (e.g. fully-seeded teams will tend to face unseeded teams), and judges are similarly allocated (with better judges going to rounds with higher seeds). Seeding does not affect pairings beyond round 1, which are power-paired based on previous rounds at that tournament.

This could be put in manually when pairing/allocating round 1, but would go much faster if integrated as a metric like priority into the auto-allocation feature.

**Comment by philipbelesky** [comment]
That's interesting to hear about. Do you think the current adj ranking and room priority features would work for this purpose, assuming the data was entered correctly?

My first though for an implementation would be that if there are new data fields to track adj/team seeds then there might be a button in the UI to copy those fields over to become initial adj/room rankings. The benefit being that the existing allocation systems and UI could work as-is; they would just be fed different data.

**Comment by tienne-B** [comment]
The way I'd envision such a feature is with a new field for `Team` for their seed, and a new allocator type that can be set for round 1. I wouldn't care much about recording which speaker "seeded" the team though. There needn't be any changes to adjudicator auto-allocation with our current system if the debates are then prioritized by "seed status".

@philipbelesky, I think this task is for a new way of pairing teams, and I'm not sure I understand how room allocations are affected or respond to the point of the task (or I might be mistaken!)

**Comment by philipbelesky** [comment]
@tienne-B sorry, by 'room rankings' I should have been saying 'matchup priorities'. The idea being that if the matchup priority represents the two team seeds (and adj seed becomes adj ranking, or is represented by initial adj ranking) then the existing auto-allocator should be able to work unmodified. My comment was just in the context of adj allocations, I agree that draw generation would definitely need a separate allocator. 

I assume there would be some sort of APDA-tailored 'use seeds' preference setting that would enable the UI to show these new options?

**Comment by tienne-B** [comment]
The team seed and new draw type could be available only in the Database area (and API), then a new preference wouldn't be needed.

**Comment by rkapoor1512** [comment]
A more detailed explanation of seeding. There are 4 types of seeded teams. Each tournament is free to determine who gets which seed, so just allowing people to manually enter 'seed status' while adding teams would be ideal for data entry purposes. Some teams choose not to do seeding at all: right not, they just mark every team as unseeded, but ideally we could have it be optional. 

The four types of seeds are, in heirarchy, full, half, free and unseeded teams. Which teams get which seeds is not important for implementation purposes, but typically full seeds are teams where both partners have qualified for nationals, half seeds have one partner qualified, and unseeded teams have zero. Typically, each institution gets one free seed allocated to it, and can choose to give it to whichever unseeded team they want. 

The draw for R1 is generated randomly, while meeting the following constraints, in descending order of priority. 
1. No full seeds shall hit another full seed
2. No full seeds hit a half seed.
3. No full seeds hit a free seed.
4. No half seed hits another half seed.
5. No half seed hits a free seed.
6. No free seed hits another free seed. 

In practice, this most often looks like most seeded teams hitting unseeded teams. If that is not possible, free seeds hit other free seeds, and so on. 

Judges for round 1 are allocated on the basis of this. Rooms are ordered in descending order by number of full seeds, half seeds, free seeds in them, and judges are allocated top down. So, a room with 1 full seed is marked as a higher room than one with two half seeds, and so on. A room with two full seeds ( which typically only exists at Nationals) is the best possible room, followed by one with 1 full seed and one half seed, and so on.
