### ISSUE TITLE
Internal server error report

### ISSUE THREAD

**Issue by rein7703** [TabbycatDebate/tabbycat#2167]
I hit an internal server error while trying to load this URL:
https://newbies2021.herokuapp.com/NEWBIES2022/admin/draw/round/2/create/

Please describe what you were doing when the error happened, along with any other useful information:
I wanted to generate the draw and an internal server error occurred

**Comment by tienne-B** [comment]
You're using an invalid setting for odd bracket resolution in the Draw Rules configuration. Do not use an option labeled as "preallocated sides".
