### ISSUE TITLE
Generate results after for APDA forum

### ISSUE THREAD

**Issue by rkapoor1512** [TabbycatDebate/tabbycat#2183]
After the conclusion of an APDA tournament, generate a copy-pasteable text for posting the results to the APDA forum. 

This should have number of teams and novices who competed in (n/2 rounded up) rounds of the tournaments, top 10 novice and varsity speakers, and a team ranking in both the novice and varsity division for all the teams that broke. A link to the tab is also good to post.

**Comment by tienne-B** [comment]
What would be the format of the text?

I'm also not convinced that a new export format should be in Tabbycat, could it be better served by using the API to generate externally?

**Comment by tienne-B** [comment]
I'm closing this; I don't really want to add a new export format, especially one which is specific to one circuit and closed to that one. Recommend to use the API.
