### ISSUE TITLE
Connection Lost

### ISSUE THREAD

**Issue by hekayee** [TabbycatDebate/tabbycat#2194]
![image](https://user-images.githubusercontent.com/119631620/205430916-8ae6145d-2353-4df6-a099-89c454f86e30.png)

I was able to import datas such as participants, institutions, rooms and adjudicators but could not do check-ins or auto-generate adjudicator draws. Checking availability from the round worked.

**Comment by tienne-B** [comment]
Summarily closing this; the ticket is unactionable as there is so little detail. We use GitHub to track bugs within the software, and there's no indication that it is the software or a deployment problem. Tickets here should have detail such as the failing URL, logs showing the failure(s), and explain the steps you've taken to diagnose what is the problem or to fix it.
