### ISSUE TITLE
`CONTRIBUTING.rst` references non-existant file

### ISSUE THREAD

**Issue by daankoning** [TabbycatDebate/tabbycat#2199]
It says to install the packages in`config/requirements_development.txt`. Unfortunately this file does not exist.

I was able to find [this commit](https://github.com/TabbycatDebate/tabbycat/blob/a91f18ad4554c128eb6fdef2c3af9afb0d813167/requirements_development.txt) from a while ago which has the file I think it is referring to however as of now this file does not exist.

**Comment by tienne-B** [comment]
Try the local installation instructions to build Tabbycat rather than the Contributing guidelines.

**Comment by daankoning** [comment]
I am aware and have a functioning install myself but my point was that the instructions should probably changed to reflect the fact that the file no longer exists 😅
