### ISSUE TITLE
automatic adjudicator allocation not working from website

### ISSUE THREAD

**Issue by cyl628** [TabbycatDebate/tabbycat#2263]
Hi, I wonder has anyone met the problem. I deployed tabbycat on a Linux server and access from my browser. However, when I click adjudacator auto allocation, it just shows "loading..." and nothing comes out ever after. (I waited for a long time).

![image](https://user-images.githubusercontent.com/55496186/221176934-856075f2-1caa-4173-84f3-f0c57351374f.png)

So I check the network request from my browser. It seems no request was sent after I click the button.

I wonder if there is some necesssary setting that I have missed. Cuz I started with a newly rented cloud server.

P.S. I tried allocation by manage.py script and it works fine. So I suspect it is a network issue?

**Comment by tienne-B** [comment]
Are you simultaneously running a Redis server? Allocations and websockets require it.

**Comment by cyl628** [comment]
Oh, I see lol. Thanks. Btw are there any special settings for Redis to work with tabbycat? Or should I just install and run it the default way?

**Comment by tienne-B** [comment]
Run in default way, but also set
```py
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("localhost", 6379)],
        },
    },
}
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "IGNORE_EXCEPTIONS": True, # Don't crash on say ConnectionError due to limits
            'KEY_FUNCTION': 'django_tenants.cache.make_key',
            'REVERSE_KEY_FUNCTION': 'django_tenants.cache.reverse_key',
        }
    }
}
```
in your local.py settings.

**Comment by cyl628** [comment]
now I can't even open the website... don't know why. Just sudo apt-get install redis and start the service.
Then I shut down redis and change local.py to the original, and restart my tabbycat. But still cannot access the website remotely

**Comment by tienne-B** [comment]
Any error logs?

**Comment by cyl628** [comment]
seems the server starts alright, but I just can't access it remotely
![image](https://user-images.githubusercontent.com/55496186/221192854-890b780b-a577-4ceb-992b-70ca9377d79d.png)

**Comment by tienne-B** [comment]
Try running `npm run serve`, which will also run the workers.

**Comment by cyl628** [comment]
OMG Thank you so much! That saved my day. Now my tabbycat and judge allocation work properly! You are so helpful!
