### ISSUE TITLE
private url not working in current master branch version

### ISSUE THREAD

**Issue by cyl628** [TabbycatDebate/tabbycat#2264]
I deployed tabbycat back in November 9th, 2022 and the private url for ballot entering was fine. Now trying to access through judge private url, the error log is such
![image](https://user-images.githubusercontent.com/55496186/221222730-62858ecd-259c-4e6b-b432-a896d6fd37b3.png)

Other people around me who deploy it on heroku report same problem. So I suspect it is a bug from some recent updates in master branch.

**Comment by tienne-B** [comment]
Fixed in 895b6f5272d680bf62c2773cdfac9dcde629ff7e
