### ISSUE TITLE
Byes for 2-team formats

### ISSUE THREAD

**Issue by rkapoor1512** [TabbycatDebate/tabbycat#2282]
This is a brief description of how to determine which team gets the bye in APDA tournaments: the work here should probably work for any 2v2 system.

**Byes**

This should be an optional setting: some tournaments might opt to give out a Bye, while others pair in a swing team into their tournament to fix an odd number of teams in the draw. 
The bye is allocated to the bottom team in tab, provided it has not gotten a bye before. If it has, we go to the second-lowest team, and so on. If there are multiple teams on the same record, speaks, and ranks, tied for the bottom performing team, then it is allocated randomly to any one of them. 
The team that gets the bye should be assigned their average speaks and ranks for the round they missed. So, if they get the bye in R3, they receive the average of R1 and R2 for pairing for R4, and the average of R1,R2 and R4 for pairing in R5. 
A team which gets the bye needs to be displayed on the draw, so that they know that they are not debating that round. 

An optional capability could be perhaps to allot the bye randomly in the lowest bracket, or randomly overall: APDA tournaments do not do this, but it seems within the realm of possibility of people wanting to do this.

**Comment by franga2000** [comment]
Many World Schools variants also use this method of byes with average speaks, but with the bye often being allocated randomly each round (but never twice to the same team).

If it helps, here's roughly how we achieve this in Slovenia (using a few custom scripts and some manual entry):
 - use a placeholder team called "BYE" to get an even number of teams - team history ensures a team doesn't get bye twice
 - use room constraints so the team doesn't waste real rooms
 - in the first round, speakers for the team on bye are chosen randomly and given the speaker position average for the round
 - other rounds, the speaker order is copied from their first real round and given average speaks for those speakers so far
 - each round, all bye averages are updated
 - the placeholder team always gets a loss and its speaks are set either to the minimum (to ensure the bottom team gets a bye) or to a random value between tournament min and max (to emulate a randomly placed bye)
