### ISSUE TITLE
Wrong 'team draw email message' API label

### ISSUE THREAD

**Issue by gserranof** [TabbycatDebate/tabbycat#2291]
I was playing with the API preferences section when I noticed that the verbose_name and help_text of the team_draw_email_message preference are mixed with the ones from the Private URL message.

I'll paste the JSON response, which I think makes this clearer:

  `"section": null,`
 ` "name": "team_draw_email_message",`
 ` "identifier": "team_draw_email_message",`
  `"default": "<p>Hi {{ USER }},</p><p>You have been assigned as <strong>{{ SIDE }}</strong> for {{ ROUND }} (...)",`
  `"value": "<p>Hi {{ USER }},</p><p>You have been assigned as <strong>{{ SIDE }}</strong> for {{ ROUND }} (...)",`
  `"verbose_name": "Private URL notification message",`
  `"help_text": "The message body for emails sent to participants with their private URLs.",`
  `(...)`

I've tried to find the corresponding strings to update them, but I've been unable. I don't think those are really used features, and its correct use is clear from the identifier, name or default, so I think this has an even lower than low priority, but I wanted just to pinpoint this for you to know.

**Comment by tienne-B** [comment]
Good catch! The string is found here (all the settings are in that file): https://github.com/TabbycatDebate/tabbycat/blob/5c0779189d7d470b26015cb61fc300d3998a2d8b/tabbycat/options/preferences.py#L1288-L1295

Could also unmark them for translation as they're hidden from the interface...
