### ISSUE TITLE
API: Incorrect POST of 'ms' type feedback questions.

### ISSUE THREAD

**Issue by gserranof** [TabbycatDebate/tabbycat#2294]
Hi there! Another week, another API question/issue.

For the last two days, I've been unable to figure out what is happening. I'm trying to do some feedback POST and, so far so good, everything is fine and all answers are getting posted correctly, with the only exception of the 'ms' (multiple select) questions. No matter what, the strings posted are gettin splitted, word by word, with a ', ' in between each character. This only happens when the feedback is getting posted, not whenever it is manually introduced via the tabbycat interface. 

I think an image could be really telling:
[https://i.imgur.com/uQwMyN6.png](https://i.imgur.com/uQwMyN6.png)

The feedback on the right is the one manually introduced; the left one, the posted via api. The thing is that I've tried everything I've been able to think of, and the one on the left is literally a copy-paste of the right one, retrieved via a GET. 

This is the JSON for the question:
`{"question":"http://feedback-question-url.com","answer":"['OG', 'CG']"}`

As an aside, the answers are inside an array in the manually introduced one, but putting the brackets inside the answer causes to be displayed as well on the Tabbycat UI (as in the left one). Posting without them, joining them as a single string (as in `"answer":"OG, CG"`, which I think is actually the prefered syntaxis as per the API docs) prevent the brackets from appearing in the UI (but not the ', ' split).

So, just as a final clarification, originally I thought the problem was on my end and I've tried to debug my code with no success, so I decided to change course and I've also tried to debug this making the API request via Microsoft Edge's built-in network requests inside the DevTools. In both cases, the problem has appeared in exactly the same way, so that's when I decided to open the issue - I can be for sure the one making the POSTs in a wrong way, but after changing from my code to Edge I started thinking that maybe it can simply be a bug.

**Comment by tienne-B** [comment]
Did you try `"answer": ["OG", "CG"]`?

**Comment by gserranof** [comment]
Yes! It throws an error and it is not accepted.

`{"answers":[{},{"answer":["Not a valid string."]},{}]}`

After putting it back to `"answer": "['OG', 'CG']"` it gets accepted again.

**Comment by gserranof** [comment]
From the errors and so, this is my theory of what may be happening. 

As @tienne-B correctly suggested, the ms questions are an array of string options, and so are handled by Tabbycat. But when it comes to the API, the general rule is to only accept strings as answers, as all the other questions are or can be converted to strings - I assume this was to provide more uniformity and this is consistent with the schema, that states that answers must be strings. This also explains why for the `"answer": ["OG", "CG"]` post it throws a `not a valid string` error - because it is in fact not a string and only those are accepted. So how this may be handled? 

For the GET requests, as it is correctly being stored as an array but it have to be a string, it joins all the strings on the saved array, with a join(', ') or similar, and displays it as a string. Hence why the retrieved answer is `"answer":"['OG', 'CG']"`. 

And for the POST? The same path is taken, but on the opposite way. As it recieves a string, it splits it with split(', ') or similar, with the expectation to it be ['string', 'string']. But as it is an entire string in and on itself, every single character is splitted with that comma and space. And that's why the app recieves the incorrect answers in that way.

That's my theory. The problem? I've been taking a dive on the api code and I've not seen any join or split around the feedback question classes, so I don't know how the implementation was and if this is indeed what it's happening.

**Comment by tienne-B** [comment]
If you want to see where it's happening: https://github.com/TabbycatDebate/tabbycat/blob/50bc7ed9afda894aaef1c9d50b6d9fd2e3baa008/tabbycat/api/serializers.py#L968-L974

The `answer` field should be polymorphic rather than a `CharField`. Then we wouldn't need to cast to other datatypes (like `list("ABC")` returns `['A', 'B', 'C']`.
