### ISSUE TITLE
Add new emoji from 13.1 and 14

### ISSUE THREAD

**Issue by tienne-B** [TabbycatDebate/tabbycat#2340]
Emoji version 13.1 and 14 are now widely supported, so we should be able to add the new emojis to `emoji.py`. You'll also need to update the spreadsheet and create a (useless) migration for `participants`.

**Comment by B0mb37** [comment]
Hello,
I'd like to work on this issue if possible. I can handle updating emoji.py and creating a migration for participants. However, I can't find the spreadsheet. Can you please guide me on accessing the same?

**Comment by tienne-B** [comment]
Perfect! I've invited you (through the email you make `git` commits with) to the Emoji spreadsheet. Feel free to comment here if there's anything you don't understand.

**Comment by B0mb37** [comment]
Alright, I've seen it and working on it, I will ask incase of anything. Thank you
