### ISSUE TITLE
There is need a new feature.

### ISSUE THREAD

**Issue by Taraldinn** [TabbycatDebate/tabbycat#2342]
There is a issue with the feedback.
![image](https://github.com/TabbycatDebate/tabbycat/assets/59772487/f4138695-d580-4ece-94b3-22c81435c035)

This feedback is seeing by organizers there need anonyms feedback by default. Cause most of tournament judge is from organizer side so team can't give any real feedback. So, there is an anonyms feedback system must need.

**Comment by tienne-B** [comment]
I'm sorry that your tournament does not feel safe enough to submit feedback without judgement. However, making feedback anonymous is functionally impossible as authorship could easily be deduced from the context of the feedback. I'd suggest not submitting feedback if you think it'd be wrongly handled, and would doubt how important it'd be if adjudicator assignments were already predetermined.
