### ISSUE TITLE
API: More straightforward access to checkin statuses

### ISSUE THREAD

**Issue by gserranof** [TabbycatDebate/tabbycat#2353]
Related to #2087 

AFAIK currently the only way to get access to lists of missing or present participants via the API is by GETting one by one for each individual participant (and/or venue, in its case); as they're structured right now, each individual checkin is accessed by its corresponding URL, obtained in the `_link` section, but there is no access to a global checkin list. As so, to try to access something like that, it is required to do a call for every single participant which, in a tournament like EUDC or WUDC, can very easily scale to an enormous degree of calls.

That, I guess, can be easily fixed with a way to directly export them or, maybe even without the need to add another endpoint, just replace the current approach (in which the checkin data is hidden behind a URL thus calls) and instead just make it accesible in the corresponding participant list - but having it being relatively straightforward, I guess there was some design reasons for configuring this the way it currently is, so I also wanted to ask too in case I'm missing something here. 

Being maybe more clear, if this is the current speakers list: 

`[
    {
        "id": 1503,
        "url": "https://tournament.calicotab.com/api/v1/tournaments/tournament/speakers/1503",
        "team": "https://tournament.calicotab.com/api/v1/tournaments/tournament/teams/444",
        "_links": {
            "checkin": "https://tournament.calicotab.com/api/v1/tournaments/tournament/speakers/1503/checkin"
        },
        "name": "Speaker 1",
  ... ` 

just changing it to:

`[
    {
        "id": 1503,
        "url": "https://tournament.calicotab.com/api/v1/tournaments/tournament/speakers/1503",
        "team": "https://tournament.calicotab.com/api/v1/tournaments/tournament/teams/444",
        "checkin": {
            "barcode": "123456",
            "checked": false,
            "timestamp": null,
        },
        "name": "Speaker 1",
... ` 

wold entirely solve this, isn't it? If a security layer is needed, maybe it could be hidden if there's no token in the API call. If I remember correctly, this is already the way some key values are handled in other parts of the API structure.

**Comment by tienne-B** [comment]
I'd disagree about extending participant schemas to include checkin information, as checkins are a different resource to the participants with a very well-loaded set of verbs for the endpoints, discoverable through the link. I'd be more inclined to create a new list endpoint, and maybe even add shortcuts to check in entire teams or institutions at once.
