### ISSUE TITLE
Local installation on windows (without Docker)

### ISSUE THREAD

**Issue by tanzilamd** [TabbycatDebate/tabbycat#2376]
I am encountering difficulties with the local installation of Tabbycat on Windows. The installation process appears to be encountering errors or issues that prevent the successful setup of the application. 

I think, the documentation isn't updated. It would be very helpful if we can get updated instructions regarding local installation on windows (without Docker).

**Comment by tienne-B** [comment]
Could you tell us what errors were you getting at what steps? Currently there's not enough information in this report.

**Comment by tanzilamd** [comment]
**Issue with pipenv install --deploy command (according to the documentation)**

### Environment Details:
- Python Version: 3.11.6
- PostgreSQL Version: 16.1
- Git Version: 2.42.0
- Operating System: Windows 10

### Steps:
1. Installed dependencies locally (Python 3.11.6, PostgreSQL 16.1, Git 2.42.0).
2. Set up the database and edited the `local.example` file.
3. Installed `pip` and `pipenv` and used `pip install --user pipenv` as well.
4. Ran the command: `pipenv install --deploy`.

### Issue:
Upon running the `pipenv install --deploy` command, encountered an error. That's why, unable to continue the next process.

### Screenshot:
![pipenv](https://github.com/TabbycatDebate/tabbycat/assets/59307135/f20af7ca-630e-42ed-861f-36833cdcb5e3)

**Comment by tienne-B** [comment]
What were the errors exactly? Your screenshot isn't working.

**Comment by tanzilamd** [comment]
It's been deployed successfully. But, requrements.txt file should be added. Should I pull request with the file?

**Comment by tienne-B** [comment]
No, there shouldn't be a `requirements.txt` file as that'd be a holdover from `pip`. We now use `pipenv` which uses `Pipfile` and `Pipfile.lock`.
