### ISSUE TITLE
Re-enable the motion fairness test

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#238]
Currently on the `motions.html` template the 'fairness' column is blank. Previously this used a library to calculated a chi-2 test, but said library was removed at some point. This functionality should be re-enabled, and could also be presented graphically, potentially in a manner similar to Tabbie. [This post](http://trolleyproblem.blogspot.com.au/2012/06/better-fairness-test.html) has good background/implementation details

It may also be interesting to have this info be added to the Dashboard and/or results page for the purposes of fun gossip during tournament rounds

**Comment by philipbelesky** [comment]
Quick mental note that it might be nice to do a tabbie-style diagram as a part of this; quick mockup attached for future reference / feedback. Inner bars are expected variance given quantity of debates using chi-2 test at whatever confidence interval we are using.

![](https://dl.dropboxusercontent.com/s/2p3xmwft98yvzup/Untitled-1-01.png)

**Comment by philipbelesky** [comment]
Have implemented a basic form of this now, courtesy of Viran. There's some scope to tweak the thresholds and interface, but I think it's sufficient for the purposes of this release.

**Comment by philipbelesky** [comment]
Note: unclear if, or how, vetoes should be taken into account. The sample size cutoff for 'inconclusive' could also be better considered; currently it's just <10

**Comment by czlee** [comment]
Just checking, does "balanced" mean "the motion is balanced" or "we can't really see that it's not balanced"?

**Comment by viranweerasekera** [comment]
It means "we can't really see that it's not balanced" (ie. We fail to reject the null that AFF wins = NEG wins) - It's probably not strictly correct to say "balanced" but for these purposes it may be sufficient.

**Comment by czlee** [comment]
Hmm, yeah, I think we would understand this instinctively but I wouldn't trust users more generally to understand the precise meaning—we should think about how to present this in the UI 🙂

**Comment by viranweerasekera** [comment]
Agreed, yeah - I'm not sure how we can represent it in a way that keeps the integrity of the test (to at least some extent) but that also makes it understandable by people without a background in stats.

**Comment by czlee** [comment]
Haha, eternal questions 😉

**Comment by philipbelesky** [comment]
The other option would perhaps be to use a diagram or something else visual to display the likelihood of balance, and perhaps shift the wording to be a title or tooltip. Although then there is the problem of people under or over interpreting what the diagram means in statistical terms. I think also the current 'tiers' of balance are not linear, so any visual representation would need to check and ensure its not misrepresenting the stats. I might have a crack at this for ABP if we get through the other high priority stuff.

**Comment by czlee** [comment]
Yeah, this all said, it might be that this just isn't a UI problem as such, and the answer is to embark on a community-wide education programme alongside this feature.

**Comment by philipbelesky** [comment]
This has been reimplemented for 2vs2 and super-seeded by #506 for BP.
