### ISSUE TITLE
Internal server error report

### ISSUE THREAD

**Issue by keelzythe2nd** [TabbycatDebate/tabbycat#2396]
I hit an internal server error while trying to load this URL:
https://wadl-live.herokuapp.com/sdc-senior-2022/admin/overview/

Please describe what you were doing when the error happened, along with any other useful information:
Currently shows for any page we attempt to access beyond the homepage. The 'edit database' area still opens and contains all the information on the site and I can login, but we can't access any of the actual pages content. A number of errors appearing on Heroku about the Cedar-14 stack being end of life but unsure what I can do about it to fix.

**Comment by tienne-B** [comment]
Wow, Tabbycat v1.4.0ak! It's before my time, and I don't think I can support it anymore, sorry. As it is version 1, it is also doubtful that it can be completely migrated to the current version. I'd recommend making new sites on Calico, and hope it responds to your needs.
