### ISSUE TITLE
judge allocation auto-saving not work

### ISSUE THREAD

**Issue by cyl628** [TabbycatDebate/tabbycat#2401]
![image](https://github.com/TabbycatDebate/tabbycat/assets/55496186/26c74924-d0cd-463f-b0a8-cb40bf9ca0cd)

seems auto-allocation not working and auto-saving also not working

**Comment by tienne-B** [comment]
Hello! Mind providing some more information? What version are you running, and what's the URL? This problem is most likely caused by some configuration. Make sure that Redis is currently running and Tabbycat has the connection set.

**Comment by cyl628** [comment]
> Hello! Mind providing some more information? What version are you running, and what's the URL? This problem is most likely caused by some configuration. Make sure that Redis is currently running and Tabbycat has the connection set.

I am using the current version of master branch. I believe it is working properly yesterday. Yes my redis is running. I have tried restarting redis and tabbycat.

**Comment by cyl628** [comment]
`ON_LOCAL = True

# ==============================================================================
# Settings that you should specify
# ==============================================================================

DATABASES = {
    'default': {
        'ENGINE'      : 'django.db.backends.postgresql',
        'NAME'        : 'trial',  # put your PostgreSQL database's name in here
        'USER'        : 'tabbycat',  # put your PostgreSQL login role's user name in here
        'PASSWORD'    : 'tabbycat',  # put your PostgreSQL login role's password in here
        'HOST'        : 'localhost',
        'PORT'        : '5432',
        'CONN_MAX_AGE': None,
    }
}

# Replace this with your time zone, as defined in the IANA time zone database:
# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TIME_ZONE = 'Australia/Melbourne'

# ==============================================================================
# Overwrites main settings
# ==============================================================================

ADMINS              = ()
MANAGERS            = ADMINS
DEBUG               = True
DEBUG_ASSETS        = True
SECRET_KEY          = '#2q43u&tp4((4&m3i8v%w-6z6pp7m(v0-6@w@i!j5n)n15epwc'

# ==============================================================================
# Django-specific Modules
# ==============================================================================

ALLOWED_HOSTS = ["*"]

INTERNAL_IPS = (
    '0.0.0.0',
    '127.0.0.1'
)

# ==============================================================================
# Caching
# ==============================================================================

PUBLIC_FAST_CACHE_TIMEOUT   = 0
PUBLIC_SLOW_CACHE_TIMEOUT   = 0
TAB_PAGES_CACHE_TIMEOUT     = 0
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("localhost", 6379)],
        },
    },
}
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "IGNORE_EXCEPTIONS": True, # Don't crash on say ConnectionError due to limits
            'KEY_FUNCTION': 'django_tenants.cache.make_key',
            'REVERSE_KEY_FUNCTION': 'django_tenants.cache.reverse_key',
        }
    }
}
#CACHES = { # Use a dummy cache in development
#    'default': {
#        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
#   }
#}

# Use the cache with database write through for local sessions
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'`

here is my local.py

**Comment by cyl628** [comment]
there is nothing abnormal in my tabbycat log. Auto-saving not working is pretty weird.

**Comment by tienne-B** [comment]
How about adding this to your `local.py`:

```py
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("localhost", 6379)],
        },
    },
}
```

**Comment by cyl628** [comment]
> How about adding this to your `local.py`:
> 
> ```python
> CHANNEL_LAYERS = {
>     "default": {
>         "BACKEND": "channels_redis.core.RedisChannelLayer",
>         "CONFIG": {
>             "hosts": [("localhost", 6379)],
>         },
>     },
> }
> ```

it is already in my local.py

**Comment by tienne-B** [comment]
Your current `CACHES` parameter is not on `master`... Try removing that and making sure you're on the master branch rather than a multi-tenancy one? Also, I'd recommend trying the Docker installation where everything is already set.

**Comment by cyl628** [comment]
yes, I guess it is issue related to switching between different branches. I switch back and it is fine now. Thank you so much for your quick support!

**Comment by tienne-B** [comment]
Glad I could help!
