### ISSUE TITLE
I can't finish the tournament

### ISSUE THREAD

**Issue by komediantddr** [TabbycatDebate/tabbycat#2411]
I did the usual installation via heroku, held a tournament, did not give out any errors, but after I entered the results into the final, I could not complete the tournament itself because the button itself is missing.
![image](https://github.com/TabbycatDebate/tabbycat/assets/98735782/be9272a2-362b-46f8-9af2-0bd9e2faa4e0)
when I go to the main page, I am asked to enter the results of the final, although they have been entered and confirmed by me
![image](https://github.com/TabbycatDebate/tabbycat/assets/98735782/ed4a9c66-2e7f-431d-a9eb-8bbc0f5e2665)
link to tabbycat itself
https://mnu30-13a1dc45d98b.herokuapp.com/mnu30/

**Comment by tienne-B** [comment]
The round had already been marked as completed, and that's why the button is missing. The round circle on the left is also green. This state does not prevent a correct tab release, and is not an issue.
