### ISSUE TITLE
Local installation fails due to outdated dockerfile setup of npm

### ISSUE THREAD

**Issue by PiechZ** [TabbycatDebate/tabbycat#2423]
Hello,

I wanted to install Tabbycat locally using Docker on Windows 10 and I encountered this issue:

**ISSUE:**
When executing `windows_docker_start.bat`, the following error occurs: 
`RUN apt-get install -y nodejs npm
The following packages have unmet dependencies:
   nodejs : Conflicts: npm
`

**CAUSE:**
In recent nodejs installations, the npm is installed automatically and the error is due to installing it again (probably).

**SOLUTION:**
In `Dockerfile` change 
`RUN apt-get install -y nodejs npm`
to
`RUN apt-get install -y nodejs`

This worked for me and the installation was successful then.

**RELATED:**
It looks like the same issue somebody else [here ](https://serverfault.com/questions/529385/the-following-packages-have-unmet-dependencies-nodejs-conflicts-npm/529743#529743)with different project.

This is my first issue to public repo, so if anything is unclear, feel free to write me.

Thank you very much!

**Comment by tienne-B** [comment]
Hello! Have you tried running docker on `develop`? I think I've fixed this already for the next version.

**Comment by PiechZ** [comment]
Ah, no - I tried the release 2.8.1 - sorry for not mentioning that.

https://github.com/TabbycatDebate/tabbycat/releases/tag/v2.8.1

If this is fixed that everything is okay 👍
