### ISSUE TITLE
Create schedule Event model

### ISSUE THREAD

**Issue by tienne-B** [TabbycatDebate/tabbycat#2425]
To begin for #2424, we'd need to create a Django model for each "event" within a tournament. For now, they will only be accessible/modifiable within Edit DB. We should be able to optionally link events to specific rounds, and either have a predefined event type or custom text.

Some ideas for predefined events:
* Check-in
* Briefings
* Debates occurring
* Break announcement
* Awards

In `tournaments/models.py`, we can create a model with the following fields:
* _id_
* tournament (fk)
* round (fk, nullable)
* type (text choice, blank)
* title (text, blank)
* start (aware date-time)
* end (aware date-time, nullable)

You'll then have to add the model to `tournaments/admin.py` for it to show up in Edit DB.

- [ ] Create model
- [ ] Create migration (`dj makemigrations tournament`)
- [ ] Add to Edit DB

**Comment by gserranof** [comment]
That's a really neat idea! Just as feedback (for reference, I organize almost a dozen tournaments a year, so I would be the first interested in using this function): there are several tournaments that use multiple instances of Tabbycat in parallel for, for example, the Open and Masters competitions. In these situations, many of the schedules are shared (the opening and closing of check-in, meal times, the awards ceremony, or the break announcement...), so maybe restricting the 'tournaments' field to be a ForeignKey would require duplicating these fields. Perhaps it would be more functional if it were a ManyToManyField?

**Comment by tienne-B** [comment]
Very glad people are interested! I have seen such "shared" events before, but I don't really think it'd save much time for users to have a M2M for tournaments. There wouldn't be much data to input, and such time would just be used to find the event to link in this scenario. Then they'd be harder to edit if something arises for one but not the others. This would also make the API and permissions harder as they are scoped to tournaments.
