### ISSUE TITLE
Docker installation problem

### ISSUE THREAD

**Issue by iwantlotsofcookies** [TabbycatDebate/tabbycat#2436]
I am using macOS Sonoma Version 14.4.1 and have tried installing the latest version of Tabbycat with Docker. When I run osx_docker_start.command I get the following error.

=> ERROR [web  5/14] RUN apt-get install -y nodejs npm

failed to solve: process "/bin/sh -c apt-get install -y nodejs npm" did not complete successfully: exit code: 100

I have attached a screenshot of my terminal in case it is of any use.
<img width="705" alt="Screenshot 2024-05-18 at 22 18 47" src="https://github.com/TabbycatDebate/tabbycat/assets/76258655/4e676b10-9182-49e1-8c66-58bbb741dcd9">

**Comment by tienne-B** [comment]
Try running on the `develop` branch

**Comment by iwantlotsofcookies** [comment]
Thank you - I'm not getting that error anymore!

Weirdly though, the webpage looks as if no CSS has been applied and I get the following errors saying that that it could not find required scripts and images.

<img width="1439" alt="Screenshot 2024-05-19 at 08 35 58" src="https://github.com/TabbycatDebate/tabbycat/assets/76258655/80481d30-dadf-491c-917f-64969394cee4">
<img width="1412" alt="Screenshot 2024-05-19 at 08 32 56" src="https://github.com/TabbycatDebate/tabbycat/assets/76258655/a88046d9-bea5-4192-9cf6-c71701a10eb5">
