### ISSUE TITLE
deploy_heroku.py Not working

### ISSUE THREAD

**Issue by DDH13** [TabbycatDebate/tabbycat#2439]
![image](https://github.com/TabbycatDebate/tabbycat/assets/63235220/2bddb996-bac8-47d4-a751-af45bfb7d52b)
Heroku Postgres mini and basic plans have reached end of life
![image](https://github.com/TabbycatDebate/tabbycat/assets/63235220/8030fcc2-9f37-4cb2-a6f4-be08a7ce4acf)
 [](https://devcenter.heroku.com/articles/heroku-postgres-plans)

**Comment by DDH13** [comment]
Just did. Hope [this] works(https://github.com/TabbycatDebate/tabbycat/pull/2440) . It's my first time contributing

**Comment by tienne-B** [comment]
Thank you! I've just merged it, and should be out shortly; I'm just getting the final features ready for the release.
