### ISSUE TITLE
Cannot enter ballot for two-team debates

### ISSUE THREAD

**Issue by inohan** [TabbycatDebate/tabbycat#2481]
Tested on Calicotab

For tournaments with two teams (Asian Parliamentary, North American, etc.), sending ballots with the Debate Rule "Require separate winner selection as a check on correct scores" is not working (at least via Private URL).
Trying to send the ballot returns the following message:
```
There are some problems with this scoresheet. Please review and correct them.
The declared winner does not correspond to the team with the highest score.
```
This is despite having selected the correct winning team. Selecting the losing team (Opp in the picture below) returns the same error.

![image](https://github.com/user-attachments/assets/7180db73-28fc-4bb9-8850-ff059966fef3)

**Comment by tienne-B** [comment]
This is fixed in a1eda57a7d905eade9e0b691977980016341f3e0 and will be released in the next hotfix.
