### ISSUE TITLE
Potential bug: API schema not accessible on Calico

### ISSUE THREAD

**Issue by inohan** [TabbycatDebate/tabbycat#2484]
Environment: Calico 2.8+

Accessing the API Schema mentioned in [the documentation](https://tabbycat.readthedocs.io/en/stable/features/api.html) (`/api/schema/redoc/` path) on Calicotab returns a Internal Server Error (500).
Accessing the same path on a heroku-deployed tab has no problem, and loads the Redocly schema.

**Comment by tienne-B** [comment]
Hey! This should be fixed now.
