### ISSUE TITLE
Heroku error message

### ISSUE THREAD

**Issue by EleanorM7** [TabbycatDebate/tabbycat#2493]
I have cleared my cache, cookies, etc as well as restarted and updated my computer but I keep getting this error message: 
"Push rejected, failed to compile Python app." 

How can I get around this?

**Comment by tienne-B** [comment]
Unfortunately I'll have to close this, as there's insufficient detail to identify a specific error. A stacktrace or deploy log would be useful in this regard. Deployment on Heroku is not recommended, as technical expertise is expected with that option, and we cannot give good support for it. We'd recommend using [Calico](https://calicotab.com) as it does not require any prerequisite DevOps knowledge.
