### ISSUE TITLE
Change wording for who can submit feedback

### ISSUE THREAD

**Issue by gizapavone** [TabbycatDebate/tabbycat#2495]
I think the wording "Panellists and trainees on chairs, vice-versa" can be confusing. I suggest changing it to "Chairs on panelists and trainees, panelists on chair, trainees on chair" to avoid confusion.

**Comment by tienne-B** [comment]
How about:
* "Panellists and trainees on chairs, and vice-versa" or
* "Panellists and trainees on chairs, chairs on panellists and trainees"

There's already a lot of repetition, and often not a lot of space for very long option names...

**Comment by gizapavone** [comment]
I like the second one: "Panellists and trainees on chairs, chairs on panellists and trainees".
