### ISSUE TITLE
Internal Server Error 500

### ISSUE THREAD

**Issue by Taraldinn** [TabbycatDebate/tabbycat#2509]
![Screenshot 2024-10-12 141415](https://github.com/user-attachments/assets/044d3f17-d92c-4797-8ef3-b08d426c1924)

I have hosted tabbycat on heroku by python deploy script . everything good and smooth but When I going to update anything like input configuration this shows like this .

My heroku configuration basic dyno , postgres essential-0 , redis mini . 

this logs is 

[tabbing-logs-1728729713281.txt](https://github.com/user-attachments/files/17349734/tabbing-logs-1728729713281.txt)

**Comment by tienne-B** [comment]
Sorry, there's too little detail here to be actionable (and the logs have no detail either). I do hope #1841 can help you though.
