### ISSUE TITLE
Potential bug: User permission denied for editing debate allocations

### ISSUE THREAD

**Issue by inohan** [TabbycatDebate/tabbycat#2511]
Version: Calicotab 2.9.2-C

When logging in as a user with the "edit debate adjudicators (allocations)" permission (given directly and/or given via the "Adjudication Core" group membership) and trying to access the "Draw" tab for each round to edit the judge allocations, the access is denied (status code 403).
I believe this is something unintended, as users with the "edit allocation" permission should be able to access the draw tab (`https://xyz.calicotab.com/_/admin/draw/round/1/`).

**Comment by tienne-B** [comment]
Try giving them the "view debates (detailed draw)" permission as well. It's true that the "edit debate adjudicators (allocations)" permission doesn't make much sense without this other permission.
