### ISSUE TITLE
Add email validator to "Reply-To address" setting

### ISSUE THREAD

**Issue by tienne-B** [TabbycatDebate/tabbycat#2514]
In here: https://github.com/TabbycatDebate/tabbycat/blob/cb8a08fbcdefffe2ba396fb42800c58d552d39c5/tabbycat/options/preferences.py#L1268-L1274

We should either add an attribute
```py
    field_class = forms.EmailField
```
(from django form fields) to get Django's email validation, or the validator directly:
```py
    field_kwargs = {'validators': [EmailValidator()]}
```

**Comment by tienne-B** [comment]
@aamfahim Yes! Go ahead, and don't hesitate to ask if you have any question.

**Comment by aamfahim** [comment]
Hey @tienne-B, I was wondering if it's not too much trouble, is it possible to add `Hacktoberfest` label to this issue?

**Comment by aamfahim** [comment]
Thanks @tienne-B! appreciated it a lot 🫡.
