### ISSUE TITLE
Adjudicator Feedback Integer Scale is buggy

### ISSUE THREAD

**Issue by DDH13** [TabbycatDebate/tabbycat#2541]
![image](https://github.com/user-attachments/assets/82dc586b-2f8b-4d85-a1e5-35bf995b3cae)

Doesn't let me add an integer scale despite having a maximum and a minimum.

**Comment by teymour-aldridge** [comment]
I think this won't work if you use `0.0` because Django parses this as a float. What happens if you try 0-10? It should definitely work if you use 1-10.

**Comment by teymour-aldridge** [comment]
Additionally for these kinds of questions you might find more people who can help in [the Tabbycat Facebook group](https://www.facebook.com/groups/247848888716409).
