### ISSUE TITLE
Add swappable panels to allocation pages

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#353]
Requires only front-end changes; shouldn't be too difficult. Off limited use though, so low-priority for now.

**Comment by philipbelesky** [comment]
Ok, this has landed in ed3ccae9fceba048c1aa1d374ccc69661c6b3d74. I got the hoverable conflicts going, so you should be able to see any potential conflicts before a swap is made. I didn't get the conflicts panel (e.g. the top overlay) going as I think there would just be too much information there to parse. 

I've had a check of the functionality and the over drag/drop pages for any issues. At first glance they seem fine, but it would be good to test these changes a bit before they are released.

**Comment by czlee** [comment]
Woohoo! 🎉 Always exciting to see a three-digit PR get closed as completed!
