### ISSUE TITLE
Test/add scalingo deployment

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#358]
[https://scalingo.com](https://scalingo.com). Supposedly cross-compatible with heroku, but doesn't require a credit card to signup. It has a 30 day trial rather than free dyno hours, but does have a larger postgres size, so it may be a better fit for one-off tournaments.

**Comment by philipbelesky** [comment]
Had a quick play, current issues:

- No python 3.5.1 runtime (have downgraded; building works fine)
- Seemingly no addon equivalents to `memcachier` and `sendgrid`. The latter is probably not strictly necessary, but the former would need to be switched to a redis-based backend. Shouldn't be too difficult though. 
- Need to figure out how to set their version of buildpacks

Bumping down the priority list as its probably not ideal to have tab sites that only exist for 30 days

**Comment by czlee** [comment]
That last observation sounds like a great use-case for file-based tab preservation strategies like TheAgoraProject/dta-spec :wink:
