### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#387]
First effort is in 65714e60a20b31f0b85844b333d21fc7fb0ec613. Here are my thoughts:

It's not quite as bad as I thought it would be, but doing this for the whole project (making it translatable, not doing the actual translation) would still be a concerted effort, especially bearing in mind that I did one of the easier apps. There are a number of features that I would've thought close to essential abstractions for translation that Django doesn't seem to support very well. So simple cases are simple, but more complex cases take effort.

It would also require us to have a bit more discipline in how we lay out templates and construct strings in Python—for example, we'd want to keep `<p>` on a separate line to the text in the paragraph so that `{% blocktrans %}` has a nice place to live, and we'd have to get into the habit of using `"Hello %(name)s" % {'name': name}"` to construct string rather than `"Hello %s!"` or `"Hello " + name + "!"`. But that's probably a good thing.

Python:
- The majority of this is just wrapping strings in `_(...)`.
- _All_ models, fields and apps need to have verbose names _explicitly_ added, and wrapped in `_(...)`. Translation won't pick up on default verbose names. This might be a little annoying, but seems to be standard practice in third-party and `django.contrib` apps.
- As mentioned above, we'll need to convert some strings to be constructed with `%(...)s` rather than `%s` or the concatenation operator (+)
- New-style `{varname}` formatting is allowed, but doesn't seem to be favoured by Django. Maybe we should convert all existing strings out of it.

Templates:
- In many circumstances, the `{% trans %}` and `{% blocktrans %}` tags work fine. I thought they would be annoying, but most of the time the amount of actual text in a template is much less than I realised.
- It gets messy where there's [a link in the middle of a sentence](https://github.com/czlee/tabbycat/blob/65714e60a20b31f0b85844b333d21fc7fb0ec613/tabbycat/tournaments/templates/tournament_index.html#L19-L24), and the internet doesn't seem to have a satisfying way of dealing with it.
  - It's probably easiest to use `{% url 'thing' as name %}`, and just to put HTML tags inside translation strings. In some circles this is frowned upon, because translators aren't meant to have to worry about HTML syntax and the like, but I think all the alternatives would be worse.
  - The `{% tournament_url %}` and `{% round_url %}` template tags don't support the "as" option of the standard `{% url %}` tag, and need to be modified to do so.
- For an example of where we need to rethink how we construct strings: [the first sentence in the footer](https://github.com/czlee/tabbycat/blob/65714e60a20b31f0b85844b333d21fc7fb0ec613/tabbycat/templates/footer.html#L26-L31) is a nightmare to put through a translator effectively. In fact, it's not even obvious how to do it "properly", since it includes complex internal fields, like the part rendering "Tabbycat 1.1.3 (Egyptian Mau)", which to a translator can be abstractor as one string but which takes some amount of template logic to construct. Ideally templates would provide a way to store this in a local variable, but they don't. One way around this is to construct it in Python, but I'm not sure that works so well for the footer.

There's also JavaScript, which I didn't look at.

One last thing: Partly because I think the most difficult strings to translate are the logging strings, I'm of the view that we just shouldn't translate anything printed to logs—only strings that render on web pages should be translatable. For example, I was concerned about how [pluralization](https://docs.djangoproject.com/en/1.10/topics/i18n/translation/#pluralization) does (or does not!) work with translation, but then I realized that the circumstances where you want to pluralize a general word in a sentence (as opposed to an entire sentence whose pluralized noun is known in advance) basically only occur in logging output.

**Comment by philipbelesky** [comment]
Looks good! I think the reality of doing translation across an app that isn't like, an actual business, is that things might need to be somewhat incomplete and/or some of the existing text blocks may need to be modified to be more easily translateable. That said there are many case I think we over-use large blocks of explanatory text in the UI anyway; this could be a chance to remove or simplify them. 

Maybe a goal might be to focus on setting up just the public UI templates for translation?

**Comment by czlee** [comment]
Sure. It's not really large blocks of explanatory text I'm worried about—so long as they're plain text they're really easy to mark for translation. It's any text, long or short, that has a link in the middle of it, or that involves real-time complicated construction.

I think the questions I'm interested in answering are:

1. Do we want to (gradually) do the work making things translatable, and have the associated overhead when adding new features?
2. Are we okay with translation markers being in (_i.e., cluttering) our other code?
3. Would people actually use Tabbycat in other languages? I don't know if debate formats in other languages mirror the Australs/WSDC-type styles enough that it'd be useful, and I sort of think this is a requisite for it to be worth the effort.

**Comment by philipbelesky** [comment]
1. The overhead doesn't sound too rigorous — most of the new features on the road map are quite evolutionary, so I wouldn't expect there to be huge amounts of new UI text.
2. I guess its slightly annoying but not enough to not do it?
3. Ha, that is pretty important. How would we go about ascertaining this? I or we could start a discussion in the tabbycat / regional debating groups. It would be good to gauge:
    - How much people would value this relative to other features
    - Whether public or admin is more important to have translated
    - Who might be keen to help out
    - What languages would be most useful

Also it strikes me that there may be a lot of overlap between the tabbie2 translations and our ones. It focuses on european languages which are a bit less useful for us, but it could be worth looking at.

**Comment by czlee** [comment]
Yeah, I was thinking of asking the debating groups too.

I suspect there's not enough overlap to do anything automated, but I think the Tabbie2 translations would be a good reference for particular phrases, like "break" or "opposition" or "speaker points" or "motion".

I could just merge the translation branch into develop now? While it's not complete, the extra code/files don't appear to be harmful either.

**Comment by philipbelesky** [comment]
Yup, merging in sounds good. As with class based views: 

- [ ] ActionLog
- [ ] AdjAlloc (aside from deprecated UI views)
- [x] AdjFeedback
- [ ] Availability
- [ ] Breakqual
- [ ] Draw
- [ ] DIvisions
- [ ] Importer
- [ ] Motions
- [ ] Options
- [ ] Printing
- [ ] Participants
- [ ] Results
- [ ] Standings
- [x  Tournaments
- [X] Venues

**Comment by czlee** [comment]
oh lol none of them are done yet I think I just did a few relatively arbitrarily selected pages in tournaments

**Comment by philipbelesky** [comment]
Ok, notes on this for javascript:

- I don't *think* we have any language strings in non-Vue js files. If we do there are a couple of quick/easy ways around translations, such as passing a variable from the template
- From what I can gather Django's standard methods for 'extracting' strings to be translated don't parse Vue files correctly at all as their syntax is far from standard. Thus it seems like we need to rely on creating the translations for Vue javascript files automatically
    - The [vue-get-text](https://github.com/Polyconseil/vue-gettext) package is able to parse vue files, generate the `.po` files and the translate those back to a `json` file to be used. However doing so is done via a custom `Makefile` that would need modification; particularly if being used cross-platform
    - The much more widely used [vuei18n](https://github.com/kazupon/vue-i18n) package seems to be the defacto way to do this in vue; however it only reads from json. This json file isn't of the type that transifex will happily parse; i.e. it seems non standard as it has distinct methods for doing plurals etc.

At this point using vuei18n seems like the better option, but looks to be a hassle to get it into transifex. That said it might be a *simple* hassle in that it just involves copying the strings over manually to transifex and back as needed; perhaps by using a manually-generated `.po` file as an intermediary. If the scope of translation is just the public site this is definitely the path of least resistance as there are very few public strings in javascript. Theres possibly not even that many if doing the admin site also. 

Alternately we could ignore all of that generate all user-facing javascript strings server side and pass them to the front-end as a simple dictionary. That could get ugly for Vue files with a ton of interface text, but we could perhaps hide some of that away by sticking the per-view dictionaries in the locale folders and building a Mixin that allows for a minimal class annotation for getting things. It's a little unorthodox but it does mean we can keep the existing `po` / transifex workflow and would probably be more portable if we ever replaced Vue.

**Comment by czlee** [comment]
So using Django's [built-in JavaScript catalog method](https://docs.djangoproject.com/en/2.0/topics/i18n/translation/#internationalization-in-javascript-code) won't work for Vue files?

**Comment by philipbelesky** [comment]
No, as per above it doesn't recognise marked strings in vue files:

    $ django-admin makemessages -d djangojs -e vue -l fr

...will fail at parsing/identifying strings using the provided js equivalents of `gettext` etc

**Comment by czlee** [comment]
Oh, sorry, I meant, is it not possible to use the Django `gettext` syntax in Vue files (instead of the Vue i18n syntax), given that they are just JavaScript functions in a Django-provided JavaScript library? As in, can Vue files execute arbitrary JavaScript code?

Or, if the only problem with using Vue's i18n framework is getting `makemessages` to extract strings, it's (at least in theory) possible to pass arguments to the `gettext` tool itself to get it to recognize more patterns. But I'm guessing that would only get us halfway, as we'd still have to convert the `.mo` file back to a form that Vue likes.

**Comment by philipbelesky** [comment]
Yes, its definitely possible to use the `gettext` methods provided by django's javascript library within Vue. Ideally it would be a proper Vue plugin that plays nice with require and the like, but at worst they can pull from global scope with `window.gettext` if I remember the tests I tried out properly.

From what I understand, as long as the .po/.mo works properly the Javascript catalogue handles translating that back into what the front end needs. 

So I guess I should (re)set that up as per the django docs and we can look at [something like this](https://github.com/eldarc/vue-gettext-tools) or [this](https://github.com/smhg/gettext-parser) or [this](https://github.com/kennyki/vue-webpack-gettext) to generate the `.po` files. Or perhaps create our own, and (as a worst case) manually make the `.po` files.

**Comment by philipbelesky** [comment]
Ok, so current solution:

- Given the (current) scope of translation is just the front-end I'm manually maintaining the `.po` files in `locale/CODE/djangojs.po`
- As it stands I think the only front-end facing page with significant amounts of text is the Diversity page; if there are a few other stray strings manually updating those `.po` files will be easy.
- Rather than offering these translations as a view they are compiled to a static js file so they can be compressed and save a django view request. This process is (now) documented in `CONTRIBUTING.rst` (along with my understanding of the translation workflow in general).

I think I've figured out a workflow that could automate the task of generating of the .po files from Vue files, but I don't think its worth exploring this until translating the backend JS is strongly desired and verified as a significant enough of a task to warrant the time investment:

- [vue-gettext-tools](https://www.npmjs.com/package/vue-gettext-tools) is able to extract strings from vue files to .po files. However this requires that the vue files follow the syntax of [vue-gettext](https://github.com/Polyconseil/vue-gettext) rather than using the django-provided methods they currently do. 
- [easygettext](https://github.com/Polyconseil/easygettext#gettext-compile) can then compile the po files back into a json format that vue-gettext uses. 
- This could all be automated as a gulp task.

**Comment by czlee** [comment]
I see. So is the following understanding correct:

* **_Either_**, we use the Vue standard (vue18n), then Django would have nothing to do with it (which is fine). Extraction and integration work fine, but the problem here is that Transifex doesn't like the JSON format that this produces.
* **_Or_**, we use the Django standard, then Vue would have nothing to do with it. Transifex and integration work fine, but the problem here is that we don't have an easy way to automatically extract translatable strings.
* A third option is a kludge on the first: Use the Vue standard, but convert their message files to .po format so that Transifex will play nice with them. Django still has nothing to do with this. The problem here is that it's a right pain.

**Comment by philipbelesky** [comment]
I think vue18n is out of the picture; working with JSON seems like it is just too much a hassle; or at least of an equivalent hassle to manually working with other solutions that use `.po` files

Currently merged is the Django standard approach implemented within Vue which, as you mentioned, requires manually constructing the translatable strings. 

The 'third' option actually uses `vue-gettext` rather than `vue18n` but the former still seems pretty popular. That would involve some slight tweaks to the Vue templates to use `vue-gettext`s syntax (and in doing so strip away django's javascript functions), but the advantage of doing so is that strings could then be automatically extracted — and read from — `po` files. This isn't really a kludge, its closest to a 'clean' solution and would make it easier to maintain new translations are added. It will, however, take a reasonable effort to get working and I'm not sure the time investment is worth it just yet.

**Comment by czlee** [comment]
I see, sounds good. If we switch to vue-gettext in the future, would you be consider about transitional effort (refactoring existing code that uses the current approach)?

**Comment by philipbelesky** [comment]
Not quite sure what you mean be 'would you be consider' :p But the task of refactoring the vue syntax from the current methods to the `vue-gettext` syntax would be pretty simple; probably do-able with a find+replace in most circumstances.

**Comment by czlee** [comment]
Whoops, fixed. But that answers my intended question 😆

**Comment by philipbelesky** [comment]
Do we want to keep this issue around to track progress? Or close it given the technical underpinnings now seem finished and only the task of translating remains.

**Comment by czlee** [comment]
I'm happy to close it. Even if we decide to refactor the JS system, we can deal with it when the time comes.

**Comment by tienne-B** [comment]
Linking to #744.
