### ISSUE TITLE
Allow photo uploads of ballots

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#402]
This is a bit of a blue-skies idea right now, but the idea goes like this:

- Adjudicators, instead of filling out an e-ballot form, would be able to take a photo of their ballot to be added to the tab system.
- The photo might, for example, be directly uploaded to Tabbycat, or (more conveniently) sent to an e-mail address or a Facebook chat or something like that. In the latter cases, Tabbycat would need to integrate with third-party systems to pull the photos in.
- The photos would be stored by Tabbycat, and ideally Tabbycat would show them in the ballot entry form, so a data entry volunteer just has to copy from the picture in one part of the screen, to the form in another part of the screen.
- This would allow data entry staff to start entering data before physical ballots arrive at the tab room.
- If we wanted to be fancy, we'd include some sort of QR code or other identifying image on the ballot, so that Tabbycat could autodetect which debate it is, but of course it couldn't read any handwriting.

HWS IV and Yale IV this (academic) year ran e-ballots sent to an e-mail address, and at least at Yale IV, because we had few runners, this certainly saved a number of minutes (maybe up to about 10-ish, but I didn't measure). The idea is to avoid the stresses on chairs (and potential for error) associated with e-ballots, while still capturing the benefits of eliminating the time it takes runners to get to the tab room.

**Comment by philipbelesky** [comment]
To add to the blue skying it seems like the structured data of the ballot and entry processes would be amenable to processing via a chat bot (lots of new APIsin the space, such as for fb) that could prompt users for input while providing them updates on ballot processing.

**Comment by czlee** [comment]
There shouldn't be much to asking for a photo I guess, but actually it would be a good way of feeding back their results to them for them to check for accuracy, since once a FB Chat or e-mail channel is open, that adjudicator is presumably authenticated.

This also reminds me that we would need to have protections against randoms submitting ballots. But actually, maybe that's not necessary either, so long as there exists only one printed copy of each ballot, presumably anyone who can send a photo of it must be authorized, right?

**Comment by czlee** [comment]
More thoughts:

- For some level of basic security, the QR code text should be able to be guessed from information about the debate, e.g. it should not just be the ID number of the debate. Ideally it should be the tournament name (to avoid accidents), plus a randomly generated string that only the Tabbycat site and its administrators know.
- The system will need to be able to detect whether it can parse the image, and reply straight away if it cannot (e.g. because it's too low resolution, or on a funny angle).

**Comment by czlee** [comment]
Generating QR codes is easy enough: either the [Google API](https://developers.google.com/chart/infographics/docs/qr_codes) or a [pure Python QR code generator](https://pypi.python.org/pypi/PyQRCode) will do the trick.

Reading QR codes, appears to be a lot harder; this SO question seems to imply that it's not possible without a non-Python library, which would work fine on local installations but would not work on Heroku: https://stackoverflow.com/questions/27233351/how-to-decode-a-qr-code-image-in-preferably-pure-python

See also: 
- https://devcenter.heroku.com/articles/python-c-deps (about "obscure" Python library dependencies)
- https://pypi.python.org/pypi/zbar (a Python QR code reader that relies on the ZBar binaries)
- https://github.com/ewino/qreader would be promising, but has a long way to go

At first glance this would appear to make this not suitable for a standard Heroku-based installation. Where there's a will there's a way, but it'd be a custom set-up probably involving a second server, which isn't really a great solution.

**Comment by czlee** [comment]
Alternatively, it might be that this is the kind of thing that needs to be spun out into a new project, with an API interface to Tabbycat.

**Comment by czlee** [comment]
If we can't do automatic ballot recognition, here's another procedure:

1. Chairs send ballots to an e-mail address/chat/upload to a page
2. Rather than clicking on a debate in a results table, tab staff open a page that shows a photo of a ballot, and asks which debate it is. (More on this later.)
3. Tabbycat then associates the ballot with that debate, and loads the form for that debate.
4. Data entry as usual.
5. Go to step 2.

More on step 2, identifying ballots from photos: There are a number of ways to do this:

* Look at the whole ballot and have the staff member extract the teams.
* Ask for the venue name.
* Have a special random codeword on each ballot, and ask for that. (Purpose would, in theory, be security: no-one knows the codeword except for tab staff and people who can physically see the form, so it provides some protection against spoofed ballots being submitted to a public e-mail address/upload page.) It could be a random string, but random strings are hard to type, so you'd probably just draw a codeword at random.

If it's possible to get a Python library to figure out where the ballot is in the photo and its orientation (say, using markers on the ballot form), then Tabbycat could zoom into the relevant parts of the form automatically—at the extreme, putting the relevant parts of the image next to form elements so tab staff just have to type what they see on the screen.

**Comment by philipbelesky** [comment]
Misc thoughts: I wonder if touch screen devices could actually be better at data entry than a computer/keyboard (at least for keyboards withouts full number pads). If rapid entry was a key concern (particularly with blind double checking) a mobile app that guides you through the entry process, with always-visible entry controls (ie a number pad) might actually be faster. I think of this as if users are being presented a ballot to enter, having the ballot be on the computer, and the data entered through a phone, could avoid the need to crop/zoom a photo so that it can be shown alongside the standard data entry UI.

**Comment by czlee** [comment]
It wouldn't achieve quite what I have in mind, which is for just the relevant part of the ballot to be shown next to the field in question. So, for example, next to the 2nd negative score field on the form, would be just the box in which the chair writes the 2nd negative score. The idea would be to save tab staff two things: (1) visually searching the form for the number, and (2) looking down at the ballot then up at the screen, and continuing to alternate between looking at two different places. Neither of those things are hard, of course, but I was thinking of them more as "quality-of-life" improvements, I guess—as in, it would be faster if I just stared at a screen and typed what I see, with numbers that I type appearing right next to where I'm looking (the image of the score field). Similarly for other fields.

**Comment by czlee** [comment]
- Pure JavaScript QR code reader, works in browser https://github.com/LazarSoft/jsqrcode
    - (This is a JS port of https://github.com/zxing/zxing, of which there is no pure Python port)
- ArUco markers: http://docs.opencv.org/3.1.0/d5/dae/tutorial_aruco_detection.html
    - http://www.uco.es/investiga/grupos/ava/node/26
    - paper is from 2014, so pretty recent
- OpenCV has a Python interface, but is in C++ so can't (easily) be installed on Heroku

**Comment by czlee** [comment]
More JS/HTML QR code readers:
- https://github.com/cozmo/jsQR
- https://github.com/schmich/instascan

The closest to a Python code reader I can find is https://github.com/holizz/pyxing, which is 8 years stale and a long way from anything useful. Though given that multiple people have done it in JS, maybe I should just do it myself.

Given that we already include Node.js, I suspect just using one of the JS libraries would be easier. Not sure if doing it in server-side JS would make the workflow tricky though.

**Comment by philipbelesky** [comment]
Hmm, just thinking about the storage of the images; I assume the easiest way to go here would be to store them directly in Postgres as a data blob. Anything else would require a third party service (ie some sort of AWS layer) and not work offline (although offline image scanning may not exactly be a use case worth worrying about). I assume also that, for a MVP, the rough workflow would be:

- There is a page on Tabbycat that let's you upload a photo; possibly as part of the existing private URL system. That page might provide guidance also on orientation, etc.
- When the image is uploaded it is stored in a cache or on the front end, at which point the QR code is scanned (likely by a front end js library) and the associated debate presented to the user.
- User confirms the debate is correct, which then has the page POST the image to the tabbycat backend where it is stored in postgres
- Presumably there is some sort of `BallotImage` model that associated the image with a `BallotSubmission` or `Scoresheet`

**Comment by czlee** [comment]
I actually think using Amazon S3 is likely to be easier, because there are probably loads of existing patterns for this sort of thing. (We can't be the first Heroku app to want to deal with user uploads!) Also, once you get into user uploads, we should probably think about security carefully, and I think having user uploads live on a different domain is part of how you do that. It would make deployment nontrivial I guess, but I can't say I'm too bothered if the worst case is "you need to be okay working with Amazon S3 credentials or you lose this one feature".

Agree that it won't work offline, and agree that that's not a use case—at all! The only reason you'd have photo uploads is to let judges submit online.

(Will discuss the rest later.)

**Comment by czlee** [comment]
Just jotting down some notes:
- https://devcenter.heroku.com/articles/s3-upload-python#uploading-directly-to-s3
  - This article describes how to upload _directly_ to Amazon S3 from the client, as opposed to via a Heroku dyno. We probably want to do this, to save ourselves the Heroku dyno, and because photos are big.
  - The article describes it using Flake. I can't currently find an analogous article for Django, but the Flake instructions should be transferable to Django, with a bit of effort.
- https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html
  - This seems to be a common library for using Django with Amazon S3.
  - In particular, it uses [boto3](https://boto3.readthedocs.io), the AWS Python SDK. 
  - The above Heroku guide just says to use boto3 directly, but I suspect the django-storages package abstracts away some things and allows us to use Django's `FileField`.
- https://docs.djangoproject.com/en/1.11/topics/files/
  - This is the page in the Django documentation that discusses how to work with uploaded files.
  - It's based around the simplest option, storing it in the file system, which isn't supported on Heroku.
  - The principles are meant to extend to any file storage system though, I think including Amazon S3, which is where that django-storages package comes in.

I think we'd have to do something like this:

- Client uses JavaScript to upload directly to S3, using the Django server to provide suitable authentication, as per the Heroku article
- When Django understands that a client is uploading a file, it somehow has to store that fact in the `FileField` in its database.
  - I'm not sure if this part requires some sort of hack to "trick" Django into believing that the file is there, when it hasn't actually seen it itself.

**Comment by philipbelesky** [comment]
Just quickly on the FileField aspect, presumably it could store the data as a reference link (an S3 UIDD?) rather than as the file field itself?

**Comment by czlee** [comment]
A step further—I think that's what it _does_ do, under the hood. The `FileField` itself is then an abstraction layer that hides the details of saving and retrieving the file to storage (in the file system or on S3). So if we just implemented a `CharField` ourselves to store the file location, we'd basically be reimplementing what's already there.

Also, now that you mention it, it's just occurred to me that if we can use Django's built-in file storage API, then it's easier for us to test the photo upload system locally, by just changing `settings.DEFAULT_FILE_STORAGE` to `'django.core.files.storage.FileSystemStorage'` (the default) rather than `'storages.backends.s3boto3.S3Boto3Storage'`.

**Comment by czlee** [comment]
Actually, maybe the problem of how do you get Django's file API to work with direct-to-S3 uploads was what this package is for: https://github.com/bradleyg/django-s3direct

Though, using that would rule out testing uploads locally.

**Comment by czlee** [comment]
Ah, maybe not so convenient: https://github.com/bradleyg/django-s3direct/issues/61

**Comment by tienne-B** [comment]
> Alternatively, it might be that this is the kind of thing that needs to be spun out into a new project, with an API interface to Tabbycat.

Agreed. There are a lot of possibilities for entering ballots mentioned and discussed here, so our interface could be basic. If the need arises for a tournament to have a custom entering "strategy", they can hook it up to the results API, which exists now!
