### ISSUE TITLE
Show when venue constraints are met

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#414]
It might be nice for peace of mind to have visual confirmation when venue constraints _are_ met. I can think of a couple of ways of summarizing this information:

1. Show in green text in the conflicts/flags column (in the admin view of the draw) when a venue constraint is met, saying something like "Venue constraint of Auckland 2 (Step-free access) satisfied". This would require us to have a framework for that column to handle both "success" and "danger" messages.
2. Just show the _number_ of venue constraints satisfied at the top of the page, since as a visual check, the tab director probably knows how many venue constraints they're expecting to see satisfied.

I'm not totally sold on this idea, it might end up getting in the way more than it helps reaffirm that things are working correctly, but I sort of think it might make the venue allocation a little less opaque.

**Comment by philipbelesky** [comment]
1. Makes sense; would be a nice complement to the current conflict text there
2. I think this makes sense as a success-alert displayed whenever a venue allocation has been run but not something to stick there permanently (especially if (1) is implemented)

**Comment by czlee** [comment]
(1) was done in d0ef81ed7d91ed96173a87449fe0e201db58a675, (2) I'm going to call unnecessary given that I've never wished for it since doing the success messages in January 2017.
