### ISSUE TITLE
Evaluate/test 'standard' Windows install

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#423]
Once Python 3.6.1 is released, see if the win-psycopg2 issue is resolved, and update installation instructions accordingly.

**Comment by philipbelesky** [comment]
Btw, I'm happy to try this out if you like. Is the step to check/resolve whether win-psycopg has to be installed from the exe, or if it can now be installed over pip?

**Comment by czlee** [comment]
The main step is to wait until the x64 Python 3.6 link on this page works no longer says "Package unavailable until Python 3.6.1": http://www.stickpeople.com/projects/python/win-psycopg/

Python 3.6.1 has been released so I thought the package might be up by now, but it looks like it's not quite ready yet.

**Comment by philipbelesky** [comment]
This still has yet to be release so will bump from 2.0
