### ISSUE TITLE
Improve query performance of feedback overview page

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#428]
There's probably a way to collect all the statistics necessary for the list overview page using prefetches and carefully chosen SQL queries, rather than doing post-processing in Python, particularly for things like average margins from a particular adjudicators. Just making a note to look at doing so some time.

**Comment by philipbelesky** [comment]
Is this likely to make it into Iberian Lynx, or should it be bumped?

**Comment by czlee** [comment]
Bump. I could do it, but probably won't have time.
