### ISSUE TITLE
Consolidate Heroku settings under a single environment variable

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#432]
Follows from discussion towards end of #132.

Unlike Travis, Heroku doesn't set any standard environment variables that would reliably detect whether we're on Heroku, so it's a little complicated. One option is to use `post_deploy`. Another is to insert an environment variable in the app.json file, but then we'd also need to make sure we maintain a line in the `deploy_heroku.py` script.

**Comment by tienne-B** [comment]
I'd consider this task done with the addition of the `ON_HEROKU` environment variable to use the Heroku settings.

Ref: #2017
