### ISSUE TITLE
Allow results page's list of ballots to update in place 

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#433]
Basically it occasionally becomes a pain (with large numbers of data enterers) that one has to refresh the results list in order to get an up to date list of what still needs to be entered, confirmed, etc. When lots of data is entered this can lead to people loading old versions of ballots or not realising something needs to be confirmed, not entered.

This should be relatively easily avoided by having the list be populated by a Vue object that it can then update every 10 seconds or so over JSON. If we wanted to be extra careful to avoid degrading performance we could cache the JSON response and manually invalidate it only when a ballot's information changes.

**Comment by philipbelesky** [comment]
Ok this has been merged in. Keep an eye out for odd behaviour although I haven't found any unfixed cases in testing. Notes:

- In addition to being nice and rounding out the websocket infrastructure this should hopefully save a lot of load when lots of people are on that page at once.
- [ ] The JS translations files haven't been added (but the code uses `gettext`) as compiling them still seems broken.
- The advance round button still needs a manual refresh to show. This is a pain but too tricky too fix and maintain the layout. An alert notifies admins of this need to do this.
- Assistants can now no longer click through links to ballots that they are unable to confirm. Hopefully this is a convenience, but not sure if there's an edge case to consider here.
- This was a pain to get working with the ballots graph. I also found that the ballots graph doesn't really work well when the last confirmation is many many hours after the round advanced (I presume this is when a result is re-edited?). This doesn't fix this but shouldn't make it worse either.
- The confirmed timestamp of a ballotsub is now recorded in local time.
- [ ] Would it be possible to remove the inline display of results in the ResultsTable? Its a bit stretched for space in BP formats and I'm not sure its worth the extra cost of the page load.

**Comment by czlee** [comment]
Nice! Looks great and sounds good.

-  Re clicking through to ballots they can't confirm, the edge case would be if they decide they need to discard it? (Should people be able to discard their own inputs?)

- Can you elaborate on the "confirmed timestamp in local time" thing? What was the case before? It's a timezone-aware object, right?

- I quite like having an inline display of results, it's nice to see what's been going on at a glance. I can't say I'm concerned about page load cost (unless I'm missing something?), but I see what you mean about horizontal space. 

    Do you just mean the chevrons? Do they make that much of a difference? Or do you also mean listing the teams?

    If you just meant the chevrons, would you have feelings about presenting it like this?

    | Government teams | Opposition teams |
    |--------|-----------|
    | Auckland 1 <br> Waikato 1 | Victoria 1 <br> Otago 1 |
    | Harvard 1 <br> Alaska 1 | Stanford 1 <br> Hart House 1 |

    Obviously this would make it two lines for every debate, which I guess you might also not like.

**Comment by philipbelesky** [comment]
- Hmm, the edge case of discarding their own inputs might be worth the tradeoff. I can't think of it that has ever happened — it probably would easy be easy enough to ask someone else to go through an do so at the draft stage?
- Maybe my knowledge of time zone mechanics is flawed, but the dates that I found being stored weren't being reported in the site's time zone. That might be more due to the mechanics of how it is being exported/interpreted by the front end though.

For the spacing thing:

- The chevron's are relatively non-neglible amount of space — this is a little masked by our dummy data sets generally having long names
- We could have a split set up where admins see results but assistants don't. If we're operating on the principle that assistants should know as little as possible this could be an improvement in rounds where those results are sensitive. 
- Page load costs I mention as this is a page that gets a lot quickly in a big tournament — its reloaded essentially every time a ballot is entered and checked. That said, given the page is live updating now, we could have it so that ballot entry is done in a new window, and it redirects to a generic page after (which the user would then close). Thoughts?
- Not opposed to having a layout split over two lines — the rows in that form almost always end up wrapping over two lines anyway. Its perhaps a slight usability issue, particularly if we do it there but nowhere else.

**Comment by philipbelesky** [comment]
Closing as this seems to be working well as-is. Have decided against doing anything with the links opening in the new window or removing the results; might revisit individually in future.
