### ISSUE TITLE
Add support for team code names

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#458]
Just spitballing some ideas:

- Team names could be automatically generated from a list of strings automatically when created. 
    - For fun we could have a couple of different distinct sets of strings; such as Emoji Names, Colors, Feelings, Animals, etc.
- I presume there would be a global toggle that changes any representations of team names to use their random name rather than their true name; ie a Team Code Mode.
    - Unclear if the the tab release should automatically override this; or we should just leave it to users to turn it off.
    - Will need to build into the admin interface (perhaps in the hover popups) an easy way of determining the 'real' name.
- There have been suggestions that adjudicators should also have codes. Not sure if we want to go down that path.
    - That said it probably makes sense to also hide an adjudicator's institution if team codes is on; even if we don't hide their name
- Would need to set a couple of flags or some other mechanism for ensuring the show_institutions setting isn't on when the team_codes name is also on.
- We probably don't need to disable to popover slider that shows the names of team members. Judges are going to see those on the ballot anyway so I'm not sure showing them on the web is going to affect their bias.
    - It's probably a good idea to also be able to identify persons in a room for clash/equity reasons

For future reference: [Patricia's note on team codes](https://www.facebook.com/notes/patricia-johnson-castle/team-codes-an-equitable-step/10154964407523578/)

**Comment by czlee** [comment]
Does ABP use code names?

**Comment by philipbelesky** [comment]
They would like to. But if its not viable to have a 'true' team code system in place I expect that manually editing names to anonymise them would work fine.

**Comment by czlee** [comment]
Oh that's cool, just checking where the tangible benefit to implementation is. Mainly I think the interesting question is where codenames should be used, and where they should not be, and other things like speaker names, like you say (I agree no need to hide).

**Comment by philipbelesky** [comment]
Mental note for this: I think an ideal default implementation would piggy back on the emoji system and use emoji descriptions as the auto-generated options (but with the ability to edit/import them as we currently do).

**Comment by czlee** [comment]
Bumping forward to USUDC, since it's before ABP.

**Comment by czlee** [comment]
Initial plan:

- [ ] Add a field `code_name` (with underscore) to `Team`
- [ ] Add a choice preference that enables or disables code names:
    - Disable everywhere
    - Show real names everywhere, code names in all tooltips
    - Show real names in admin, code names in admin tooltips and public
    - Show code names everywhere, real names in admin tooltips [low priority]
- [ ] Autogenerate code names based on emoji
- [ ] Show warning when `show_team_institutions` is enabled and code names are also enabled

**Comment by czlee** [comment]
Okay, I think that's a first implementation in. Let me know what you think when you get a chance. 🙂

**Comment by philipbelesky** [comment]
Yea, the implementation looks great! Maybe its my own bias but I quite like the emoji-names as team-codes part, although I think (ideally) each emoji-name would be a single word or at least a very short set of two words, so we might want to keep an eye on those labels and edit them when we spot the opportunity for a more compact description. I.E. *Graduate* rather than *Graduation Cap*.

I presume this feature should be mentioned in the docs, perhaps as a top level 'feature' in the sidebar? Do you think its necessary to add a methods to the Simple/CLI importers to accomodate them? (I would have thought yes in an ideal world, but perhaps the demand/use for the feature isn't enough to justify it over just having people manually edit things in the database).

**Comment by czlee** [comment]
Haha, I like the emoji names idea. Wouldn't want to restrict users to it, but I don't think I can be bothered going that far out of my way to support custom names.

For custom code names, the CLI importer should support it without modification to any code—for non-foreign-key fields, given a correct column header, the base importer class just interprets it as the value for the field. I think I'd lean against complicating the simple importer for this though—code names aren't even a concept in many (most?) circuits. Agree that it'll be easiest for it to get its own feature page in the docs.

**Comment by philipbelesky** [comment]
- [ ] Add feature note about team codes in docs

**Comment by czlee** [comment]
Okay to close?
