### ISSUE TITLE
Venue Categories visual importer should sort venues by display name and exclude venues from other tournaments

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#469]
Currently venues from other tournaments show up in the `venues` field when editing Venue Categories, and remaining venues are not sorted alphabetically. I know `get_formset_queryset()` exists to override the queryset for the main model but couldn't easily figure out how to do it for a field. For australs purposes I've done so manually but it would be good to address this for future large tournaments.

**Comment by czlee** [comment]
Yeah, for that it's probably easiest to define a form explicitly and to rewrite the view to use it. Will have a look over the next week.

**Comment by czlee** [comment]
I did the exclude-venues part, there are probably lots of ways to do it but I chose this way: https://stackoverflow.com/a/22487973/2056081

Sorting by display name can be done in Python with an assortment of different hacks, but if we're going to be treating display names similarly to how we treat long/short team names, I should probably just implement a mechanism similar to long/short team names, _i.e._ a non-editable field in the database, as mentioned in #468. Is that analogy a good one? This is a nontrivial exercise; is it worth the investment?

**Comment by philipbelesky** [comment]
I think when other tournament's venues are excluded it cuts down clutter in the worst instance to the point where it is manageable. Adding a `Team.short_name` style field would be nice in the case and #468  (and possibly for performance reasons more broadly?) but it's not urgent.
