### ISSUE TITLE
SecondElimination DrawGenerator doesn't account for forfeits

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#487]
Currently forfeit results are not recorded as wins, so will prevent the round advancing as there are no results.

As with other issues under the Cygent milestone these can be held off on until we confirm if/when Cygnet is brought up to date with master.

**Comment by czlee** [comment]
Wait, they're not? I thought forfeits were `TeamScore` objects with `forfeit=True` and `win` set to `False` if the team was the forfeiting team and `True` if not?

**Comment by philipbelesky** [comment]
Apparently not from what I can tell. I have a backup of the database at that time, but it might not be worth investigating too thoroughly at the moment. The other possible exacerbating issue was that there were no adjs attached to the results, but apparently re-assigning adjs and then doing the forfeits still didn't work. For context the instance is running  a copy before the refactoring of results.

**Comment by czlee** [comment]
Oh, I see. I have some recollection of something not quite right with forfeits before the refactor, but can't remember exactly what it was.
