### ISSUE TITLE
Rework the preferences module to be more user-friendly

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#500]
There are quite a few of these now, and currently it just crashes when you actually try to use the preferences. I expect the number of incompatible preferences to grow in the near future, so a framework for alerting the user to them when they're set would be useful.

**Comment by czlee** [comment]
Maybe we should expand this issue to cover a more general wishlist for preferences?

- Some groups of preferences can only be chosen in certain combinations.
- Some preferences can only take certain values ([validation is already supported](https://django-dynamic-preferences.readthedocs.io/en/latest/quickstart.html#additional-validation))
- Some preferences are only relevant when others are selected in a particular way.
- Some preferences are more important than others (or probably need to be regrouped).

Specific things:
- [ ] Public ballots/feedback would probably be more user-friendly as a choice preference. Although public links and private URLs are orthogonal preferences, in practice it's stupid to enable both and confusing that you can.

**Comment by philipbelesky** [comment]
Agree with ballots/feedback as a choice pref. Which preferences are incompatible to the point of causing a crash?

**Comment by czlee** [comment]
Can't name all off the top of my head, but e.g. certain intermediate bracket options only work with pre-allocated sides.
