### ISSUE TITLE
Consider/implement ABP pull up restrictions

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#511]
From what I can tell the change is:

> No teams in bracket is to be pulled up again if they’ve been pulled up before unless every other teams in that point bracket have been pulled up subject to technical constraints and existing priorities (e.g random pull up and position consideration)

**Comment by tienne-B** [comment]
Such a restriction seems to have been added in fc6f1b8244332cafb24349d46b65ee3fb5632b01.
