### ISSUE TITLE
Time zone support

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#513]
At the moment the time zone is locked to Melbourne, which means all timestamps are Melbourne time. This should probably be configurable somehow. The easy way is to make it a deploy-to-Heroku environment variable, but maybe we could do a user-friendly way too.

This is subject to the same "do you follow the user or the tournament?" problem that translation support does, I guess.

**Comment by philipbelesky** [comment]
The Django recommendation seems to be to store datetimes in UTC and then [translate that to the session's local timezone when the time is presented in the front-end](https://docs.djangoproject.com/en/1.11/topics/i18n/timezones/). 

Looking through the templates we don't present times very often, or accept them as inputs very often, so this probably wouldn't be a huge effort to implement. 

That would probably be my preference as opposed to adding a user configuration. I guess it would look slightly odd for people watching the tournament form afar to see times presented in their own timezone format, but in many ways that would be helpful from an observation point of view.

**Comment by philipbelesky** [comment]
Also is this in consideration for 2.0? Am I right in thinking that all front-end representations of times are incorrect?

**Comment by czlee** [comment]
Yes, you're right. Most times we show are relative times ("2 hours ago") so it doesn't matter. But those times shown as absolute times are always in Australian Eastern time, including in the Edit Database area. The exception is the start time of a round, which is not time zone-aware.

Websites for sports events (like the RWC or Olympics) often give users the option to present times in either the user's time zone, or the event's time zone. I guess this is the ideal, but might be overkill for our purposes. I don't think Django's recommendation works as well for sports events, but for our purposes it's probably fine, I think.

**Comment by czlee** [comment]
Notes:

1. First, a problem. Django doesn't actually automatically detect the end user's time zone; unlike with languages, [there's no easy way to do so](https://docs.djangoproject.com/en/1.11/topics/i18n/timezones/#selecting-the-current-time-zone):

    > The current time zone is the equivalent of the current locale for translations. However, there’s no equivalent of the Accept-Language HTTP header that Django could use to determine the user’s time zone automatically. Instead, Django provides time zone selection functions. Use them to build the time zone selection logic that makes sense for you.

   If we're determined to do time zones according to the user, there are probably ways to detect this using JavaScript, for example, the [django-tz-detect package](https://github.com/adamcharnock/django-tz-detect). But the point where Django doesn't make this trivial, I'm sympathetic to making this a site setting that site administrators configure (presumably to the local time zone of the tournament), and Django then sets the current time zone to that for everyone, including those watching from afar.

2. Because the action log and results timestamps are communicated using JSON, and they (to my best knowledge) can't be serialized in a standard datetime format, they have to be converted to strings in Python, as they are now. To localise this correctly, I wrote a function `badge_datetime_format` in the `utils.misc` module, which relies on the files in `utils/formats/`. **When you want to put a timestamp in a badge, use this `utils.misc.badge_datetime_format` function.**

3. More generally, Django's very good at localizing dates in template code; not so much in Python. Whenever you produce a human-readable time in Python, beware.

4. **Every time we add a new language, we must add the appropriate `BADGE_DATETIME_FORMAT` in [`utils/formats/`](https://github.com/TabbycatDebate/tabbycat/tree/3d4614b/tabbycat/utils/formats/).** Different languages have different date formats; see [Django docs](https://docs.djangoproject.com/en/1.11/topics/i18n/formatting/) or the [formats.py files in the Django source code](https://github.com/django/django/tree/2.0.2/django/conf/locale) to get some idea. I've set it up so that if a language's `BADGE_DATETIME_FORMAT` isn't defined, it'll default to `18/02 16:33` so that it doesn't crash, but spit out a whole bunch of errors to make sure we notice.

5. On that note, since "08/02" is ambiguous in English, I changed the format for English to always use textual months, _e.g._ "8 Feb". (See [source code](https://github.com/TabbycatDebate/tabbycat/blob/3d4614b/tabbycat/utils/formats/en/formats.py).) This is both in `BADGE_DATETIME_FORMAT`, and in overriding all of the "standard" datetime formats (which we don't really use).

    I also put in an override to make follow Commonwealth conventions where unambiguous (rather than the default American ones). The other option would be to distinguish between American and British English, which is a route I'd rather not go down (at all, not for Spanish either).

6. The "starts at" time (a field in `Round`) is not a datetime, it's just a time, so it's timezone-naive. This means that it will display the same everywhere in the world, which will in practice mean the local time of the tournament. I don't have a problem with this—it seems broadly sensible to me, given that it's the only time displayed anywhere in the public interface. But if we decide we want this to be timezone-aware, in principle we could convert it to a datetime field, and always put in the current date for the date part of it.

**Comment by philipbelesky** [comment]
Looks good! To address (1) I had imagined time zone support as basically meaning that the 'canonical' time time could be changed based on tournament location; not necessarily based on where a user accesses the site from. That is to say it's debateable whether we even want times to adapt to the end user — for pages such as the TournamentOverview or, as your mention, the round start time I would probably lean towards keeping those time stamps naïve. For people 'observing' the tournament; or for tab staff accessing the site post-tournament I think those times make most sense when kept in 'tournament time' rather than user-local time as they are mostly measured relative to the tournament's schedule. That said, for (6) at least you could make a case for showing both tournament-local and user-local times so people could both tell when a round is likely to finish (in user local time) and whether a tournament is running to time (in tournament local time).

**Comment by czlee** [comment]
Re naivety, we don't have much of a choice with datetimes, actually - they get stored and converted with time zones whether we like it or not. (Check the database using PostgreSQL, and try setting `USE_TZ` to False and `TIME_ZONE` to something other than your time zone and notice the times all look wrong. At a minimum, the time zone has to be admin-configurable.) But also, as the Django docs argue, there are good reasons to use timezone-aware datetimes even if you don't need time zone support (e.g., daylight saving).

**Comment by philipbelesky** [comment]
Is this finished/closeable?

**Comment by czlee** [comment]
No, I haven't really looked at it again in a while, but I remember thinking we still had more to do to make the feature accessible.

**Comment by philipbelesky** [comment]
Ah true. It seems like there are two paths for doing so:

- Having the time_zone configuration be dynamic and stored in the database somewhere. Unclear if this would have a performance impact (I assume so?). This would probably allow for a better experience in that we could prompt people to set a time zone (for the entire instance) during the tournament creation wizard *if* a time zone value not been set for the entire site. In doing so we could offer a nice drop down with proper country/zone names.
- Having the time_zone configuration left as an environment variable / hardcoded setting. For heroku we could ask for a timezone code during app creation, and I guess for local installs we could ask people to edit local_settings or set an environment variable.

I'd probably lean towards the second option as both the easier implementation and the cleaner one. I suspect most people using local installs won't actually nominate a time zone, but that seems like an ok outcome — as long as they are aware of why the dates might look off sometimes. It's a little akward to have to ask people to look up and enter ISO time codes on the heroku app creation page but I guess we could really pad out the `description` field to include common codes and a URL/instructions on how to find them.

**Comment by czlee** [comment]
Ah, I see, doing it on the Heroku deploy page isn't a bad idea (and I admit, one I had forgotten about), I could live with that.

**Comment by czlee** [comment]
In fact, we could also add stuff to the documentation explaining how to change the config vars on Heroku, and people who find it especially annoying after the fact can look there.

**Comment by philipbelesky** [comment]
Ok have updated the docs for local installs and heroku and added it to app.json. Kind of loathe to have such a marginal setting added to an already-long instruction set but have tried to make it clear that it probably isn't necessary.

**Comment by czlee** [comment]
Re 0bde70270725848428e87f00ceb52fbe3a9903ae, the time zone names aren't an ISO standard, they're just an IANA database maintained by a very kind individual. Also, `US/Pacific` isn't a time zone name (it used to be, but it's deprecated); the correct time zone name for the Pacific time zone is `America/Los_Angeles` (or `America/Vancouver`). Maybe this strategy will be harder on users than we thought? 😝

About the instructions, by the time someone's doing a local install, they're probably advanced enough for this to be a trivial step. I also feel like there'd be less text if we just told them to do it in step 4(b), rather than caveat its necessity. So if we're trying to minimize the impact on the local installation instructions, I'd just put it in?

(It's also actually quite annoying to have times show up in Melbourne time, when you're not in Melbourne.)

**Comment by czlee** [comment]
I tried it in e26008a, though only in the Linux page (so we can compare), let me know what you think 🙂
