### ISSUE TITLE
Adding a reply speaker who hasn't given a substantive speech causes an error

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#515]
Line 492 of forms.py currently throws an error if the reply speaker is not also a substantive speaker. This should probably be handled better, either through front end validation and/or passing an error to the form itself that displays inline.

**Comment by czlee** [comment]
Wait, it does? [This line?](https://github.com/czlee/tabbycat/blob/894069d378027dd685e8f7f96cef478412b11761/tabbycat/results/forms.py#L492) That's meant to be part of form validation, not an uncaught error? Do you mean we should also include front-end checks for all validation already in the back-end? (If so I agree, just clarifying.)

**Comment by philipbelesky** [comment]
Yea so that part of form validation seems to fail (i.e. shows an error page) rather than bouncing back the form with an inline error.

**Comment by czlee** [comment]
I can't reproduce this, I get this error message, as expected.
![image](https://user-images.githubusercontent.com/1725499/34895945-b1e1900e-f79c-11e7-9d97-4686137952ac.png)

Mind taking another look at this, or sending me a snapshot, when you get a chance?

**Comment by philipbelesky** [comment]
Hmm; can't seem to reproduce this so will close.
