### ISSUE TITLE
Move to a "completed rounds" system rather than a "current round" system

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#516]
The use case is where (say) open and novice break rounds occur simultaneously. It'd be nice to be able to:
- [x] On the public interface, show just the current break rounds (without showing all inrounds)
- [x] In GA display, show draws for all simultaneous rounds in the same view.

**Comment by czlee** [comment]
Thoughts:

1. We can't possibly do this without allowing multiple rounds to be marked as "current" at the same time. The simplest way to do this would be to add a `BooleanField`, `current`, to `Round`. This is a pretty major database schema change, though not a prohibitive one, in the sense that we could still define `Tournament.current_round` as an alias that works whenever the current round is unique, or better still, that always returns the _last_ current round, as in something like:
``` python
class Tournament(models.Model):
    @cached_property
    def current_round(self):
        return self.round_set.filter(current=True).order_by('seq').last()
```
    We could also still cache this as a property, as we do now. I'd want to understand the impact of such a change more fully, though.

2. I wouldn't place any constraints at the database level. As in, if someone wants to edit the database to make every round current, they should be able to do so and enjoy or suffer the consequences.

3. If no current round is set, it should redirect to the "set current round" page, as currently. The lazy and flexible rework there would be to make the "set current round" form use a `SelectMultiple` widget. The intelligent and guiding rework would be to set up the form to have them choose either an inround, or, an outround in each break category.

4. Where "public draw" is set to "only the current round", they should just all be in the same view, like for the GA display.

5. I think it's fine to conceptualize each break category as its own line, so when you "advance" from a break round, it marks the next break round in the same series as current.

**Comment by philipbelesky** [comment]
Hmm, I was thinking about this yesterday, and I wonder if this would work as an alternative:

- Unite the two draw release preferences in to a single preference to the effect of 'show draws publicly'
- If that preference is enabled, and the current round is an *in-round*, the public site shows in the menu/index:
    - A link to the current round's draw if it is released
    - Links to all released draws (past/present/future)
- If enabled, and the current round is an *out-round*, the public site shows in the menu/index:
    - A link to the most recently released draw for each category (sneakily labelled as *Current Draw for X Category*
    - Links to all released draws (past/present/future; regardless of category) 

This change was initially imagined as a way to unite two preferences that don't really need to be separated. It also clarifies the user behaviour around releasing a draw — once a draw is released it will *definitely* show up on the public site regardless of the `current_round` status. It also, in the case of this issue, means that the effect of `current_round` can be ignored for the purposes of releasing break rounds which largely matches the desired actions/workflow in break rounds as-is.

**Comment by philipbelesky** [comment]
Only just saw the changes in `fa43d4bcb18f04a21279159ce0fdd47ef0b2b5e7` related to this. In contrast to that change, a single on/off preference toggle seems much more clear as it allows users direct  control over the release state of individual rounds. It also, if the above comment is implemented, means that the same workflow continues into break rounds without needing to enable a specific setting or change the underpinning mechanics of the `current_round` field. From a user's perspective the 'current round' link should just be a convenience link rather than something they need to consider in relation to the release process.

**Comment by czlee** [comment]
I'm… confused, sorry. So it's round 7, and I've just released the draw, and I released the draw for every round prior. And the menu and index are arranged, with _both_ current _and_ all draws? As in, the menu is


| Draw for Round 7 | Draws ▼ | Results ▼ | Motions | Standings |
|------------|---------| ---|---|---|
|   | Round 7 | Round 6 |
|   | Round 6 | Round 5 |
|   | … | … |

and 
 
| Menu |
| ---------- |
| Draw for Round 7 |
| Draw for Round 6 |
| … |
| Draw for Round 1 |
| Results |
| Motions |
| Standings |

I don't think we gain much from this clarity of effect. In power-paired tournaments that release results, the only draw you care about is the current one; the rest is just clutter. In power-paired tournaments that don't release results, tab directors should be able to choose whether past round draws are visible (they might have their own reasons), without having to go back diligently unreleasing every round after it's over (draw release also affects public ballots and feedback, so there's a side effect of unreleasing). There's a use case for releasing all draws, for sure—fully drawn tournaments, and ones where the tab director wants past draws but not results to be available—but that's why we'd have an option for it.

I think the existence of different desirable behaviors in different tournaments is enough for me to object to the claim that these preferences need not be separated?

I can see the desirability of distinguishing between effects in other cases. For example, if rounds 7 through 9 are silent, maybe you want to have draws for rounds 7 through 9 available, but to rely on results for rounds 1 through 6 to convey the draw. So maybe we should

1. distinguish between "draw for round _n_ is visible to public" and "e-ballots and e-feedback for round _n_ are available", and
2. have the system you suggest, but exclude rounds whose results are released from the list of "released draws"?

There's a case against these for sure: (1) separates two steps that can be argued to be distinct but in practice are always the same, and (2) adds implicit side effects. And I'm sympathetic to a rethink of how we conceive of the role of a "current round", so I'm open to further discussion. But I don't think I agree that tournaments should be assumed to want all past released draws to be available on the the public site, unless they manually turn off every past round, in a way that also happens to disable ballots/feedback.

**Comment by czlee** [comment]
Ah, on the first issue, for what it's worth, I'm 100% not averse to either having `all-released` be a superset of `current`, or having a fourth option that does both. I was just trying to recreate the existing behavior, which disabled the "current round" link when `show_all_draws` was enabled.

With simultaneous break rounds—almost. I think that, at least when `current` is used, the current round page should show all simultaneous break rounds on the _same_ page. I've found it annoying at recent tournaments that I couldn't easily show the entire draw on a single page in GA; I think it'd be more convenient for public users to have just a single page listing everything that's going on too. (Use case: "Which debate should I go and see, given that my school's eliminated from the tournament?")

That all said, this discussion has made me wonder: why do we need to keep track of an explicitly set "current round"? It's really convenient to be able to reach for a `current_round` attribute in code. But could and should we infer this from other information, and would doing so avoid the gymnastics we currently have to do with making sure the user's set it to what we think it should be (and at all)? For example, if the rule for outrounds is "the last released outround in the category", why not make the rule for inrounds "the last released inround"?

This would change current behavior in some ways. It would eliminate the "draw has not been released yet" page, and just continue to show the round 5 draw instead until round 6 has been released. On reflection, I feel like this probably isn't desirable; it's nice for participants to see that round 6 is underway before the draw is released, particularly with their current tendency to hammer "refresh" before release (despite tab directors' pleas to the contrary). But then, I think we'd want to keep this behavior consistent between inrounds and outrounds, right? It's a bit weird for "draw not released" to be a concept for inrounds, but not outrounds.

(For what it's worth, personally, I prefer to disable past draws just to avoid clutter, since the results pages are a superset of the past draws. I've noticed some tournaments seem to want to release information only on an as-and-when-needed-and-until-not-needed basis, I don't know whether that's deliberate or just lack of awareness of other public options. That )

**Comment by philipbelesky** [comment]
Hmm, definitely open to some replacement for `current_round`. Using release status is somewhat problematic as it then plays a dual function in displaying draws and advancing the round, which are at odds depending on how you want to display information pubilicly. 

Perhaps to route back to your earlier proposal about adding a new Boolean field — perhaps that could be reframed as a 'round is completed' boolean? Whereas the current last action for a round in the standard workflow is to advance the round, that action could easily be altered as a "Complete Round" action that instead sets that Boolean field for that round (before redirecting; thus keep the existing workflow). This still relies on there being a difference in/out round behaviour for `current_round(s)`, i.e. filtering for *highest sequence in-round with `completed=False`*  vs filtering for *highest sequence rounds for each break category with `completed=False`* but I think that would match the expected user behaviour.

**Comment by czlee** [comment]
I like this idea! Except you meant the _lowest_ sequence round with `completed=False`, right?

To me that qualifies as not being an inround/outround distinction. The logical effect is the same, the only difference is the existence of parallel tracks, which I agree is what we want.

It'd also be nice to get rid of that "set current round" nonsense.

**Comment by philipbelesky** [comment]
Errr yes, lowest sequence. It could also better open a path to pre-flighted rounds or similar multi-track setups within in-rounds.

**Comment by czlee** [comment]
After some work today (see the `feature/#516-completed-rounds` branch, or 46d7d58c10fbaaf5bdae2f3c9f35499933efd5b8), questions and lingering notes:

1. I think it should now be possible to merge `Tournament.current_round` and `Tournament.get_current_round_cached`, but my understanding of the caching of this attribute isn't solid enough to know what to do. What should we do?

2. I updated the "set current round" form so that it asks for _either_ a preliminary round _or_ an elimination round in _each_ break category. It currently enforces this using `clean()`, because I was too lazy to do the JavaScript for it, but I'll get to that some other time.

    (The simpler option would have been just to present a checkbox for every round and allow the user to mark any combination as complete, but I think that's too confusing for the standard use case, and users who want that granularity should head to the database area.)

3. I considered calling it `complete` and decided against because to me "complete" means "has every part with none missing", which is not quite the same has, "has been finished".

4. If _all_ rounds have been completed, then we could say the current round is `None`, but a bunch of pages would break. So I put in a stopgap in 46d7d58c10fbaaf5bdae2f3c9f35499933efd5b8, where it'll return the last round if all rounds are completed (thus matching current behavior). On reflection, I'm sort of comfortable with this being a permanent solution, because I think it'll be too much overhauling to write in special cases for this everywhere where `current_round` is assumed to exist. Thoughts?

**Comment by philipbelesky** [comment]
1. I guess we should err on the side of merging. That said maybe we should deprecate this kind of caching and look at caching those kinds of objects at the request level perhaps? A pretty large portion of queries on any given page seem to be for single objects (preferences, current user, current tournament/round, etc) that are the same within a request cycle.
4. This sounds good.

**Comment by czlee** [comment]
1. Maybe! Though there shouldn't really be any duplicate queries within the same request because we made quite an effort to avoid this?

2. Up to and _not_ including, since the current round is the first _not_-completed round.

**Comment by philipbelesky** [comment]
Yea, it's hard to get a handle on how complex/intuitive its going to be. Traditionally I think the public UI has done a relatively good job of streamlining people towards what they actually want to see, whereas the admin UI makes explicit the different options currently available.

**Comment by czlee** [comment]
Oh, obviously this breaks a bunch of tests, so I'm not done yet, this is complicated enough that I want a bunch of tests in there to check that no draws can be prematurely released to the public before merging.
