### ISSUE TITLE
Sides confirmation status saves the opposite of what is checked

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#521]
It appears that the `sidesStatus` key in the AJAX request has the opposite value of that the UI says attached to it, so _e.g._ if sides were unconfirmed and you check the box to confirm, the value sent to the server (from the client) is `sidesStatus: False`.

**Comment by philipbelesky** [comment]
Could you see if the commit above resolves this behaviour? Just checking that it works across browsers/platforms.

**Comment by czlee** [comment]
Negative on Chrome. 😞 
Affirmative on Microsoft Edge. 😄

**Comment by czlee** [comment]
I reran `npm install` and `dj collectstatic` before trying, was there anything else I should've done?

**Comment by philipbelesky** [comment]
Hmm, can you post the Chrome version? And what is the behaviour — you check a previously unchecked box, reload the page, and then it is still unchecked?

**Comment by czlee** [comment]
Chrome version 62.0.3202.94 (updated today).

Behavior: Upon reload, the box is in the opposite state of whatever it was before the reload.

Examples:
- Start unchecked, click once to check. On reload, it'll be unchecked.
- Start unchecked, click once to check, then a second time to uncheck. On reload, it'll be checked.
- Start checked, click three times, so it'll be unchecked. On reload, it'll be checked.

Other pages are consistent with the state upon reload. So, e.g. to confirm all sides in a round which previously had no sides confirmed, you could click every box twice (once to check, a second time to uncheck), and then all sides will be confirmed.

**Comment by philipbelesky** [comment]
Hmm, I've just tested on Windows with the same copy of Chrome, and haven't been able to replicate this. To be safe do you want to delete and rebuild the `staticfiles` folder and check cache is disabled in the Network tab of the chrome inspector?

**Comment by czlee** [comment]
I `rm -r staticfiles`ed then `dj collectstatic`ed and cleared the cache and disabled cache in Inspector, and still getting the same symptom. There's definitely some problem with caching though, because even when I edit the console debug lines myself, it still prints the old debug line.

**Comment by czlee** [comment]
Hmm, I noticed it's not running gulp, so I ran `npm run gulp build -- --development` separately and now it works. I'll have to figure out why that is, but it seems like this issue can be closed.
