### ISSUE TITLE
Write framework for managing different result types

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#527]
Currently the GUI provides no way to nominate a single team winning, as they do in final elimination rounds.

**Comment by czlee** [comment]
I think this relies on some refactoring to be able to display different result types in the various places where it occurs, easily, particularly with popovers (_i.e._ we should reduce technical debt, then do this). Maybe this issue should be about that instead?

**Comment by philipbelesky** [comment]
Quick note that I'm bumping this to next release

**Comment by philipbelesky** [comment]
Just a note that given this doesn't seem to be on the immediate horizon, we should add a docs page that explains the workaround, and use an alert or similar to surface that for ballots in the ultimate round of a given break category. I'll try and add this in for a hotfix.
