### ISSUE TITLE
Upgrade Django to 2.0

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#528]
Changes required:

- [x] Dynamic preferences dependency compatible  release
- [x] Jet dependency compatible release
- [x] Potentially rewrite views to use new url syntax
- [x] Deprecate psycopg2 (is inbuilt now I believe)

**Comment by philipbelesky** [comment]
Now that Jet has been updated I've gone ahead with the 2.0 update. Changes are mostly a couple of namespace edits. Turns out psycopg2 is not deprecated; just the name of the postgres backend has. Rewriting urls to use the new syntax can probably be done on an adhoc basis.

@czlee The one thing I've run out of time is to fix the page/test for the diversity page, whereby `compile_grouped_counts()` now fails with a TypeError of `unhashable type: 'list'`. I'm not sure what the change in behaviour was that triggered this but will push it up (sorry for the incoming test failure) for you to check out.

**Comment by czlee** [comment]
No problem, will have a look.

**Comment by czlee** [comment]
Ooh, are these autocomplete fields useful? https://docs.djangoproject.com/en/2.0/releases/2.0/#django-contrib-admin

**Comment by philipbelesky** [comment]
In theory they should allow for us to deprecate the need for `django-gfklookupwidget` I think; will need to test if they work as drop-ins with Jet.

**Comment by czlee** [comment]
I don't think that deals with `GenericForeignKey`s, just `ForeignKey`s, which implies that gfklookupwidget is still needed? It just replaces the `raw_id_fields`.

**Comment by czlee** [comment]
I don't why that diversity page broke, but the stacktrace indicates that it was now trying to hash a list, which is of course not possible. But the list in question is just `['F', 'O']` (used to group females and others into the same category for statistical display), so I just changed it to a tuple.

On rewriting URLs to use the new syntax, this'll conflict with #510, so we could hold off till that's merged in if that works for you?

**Comment by philipbelesky** [comment]
Yea, I don't see any need to go through and convert everything to the new syntax. We could try and do it as we change them naturally; maybe as a part of #510 even? But if that will make it more annoying then we can do so later.

**Comment by czlee** [comment]
To be fair, the new syntax is so much cleaner that I want to do it at our earliest convenience haha. But I agree it's not urgent. If I'm converting things "naturally" as I see them, then I'll be doing bits of it in #510 anyway, definitely won't make it more annoying.

**Comment by czlee** [comment]
If it's helpful, a lot of the URL syntax conversions can be done using regular expressions:
`url\(r'\^(.*?)\$?'` with `path('\1'`
`\(\?P<(\w+)>\\d\+\)` with `<int:\1>`
`\(\?P<(\w+)>\\w\+\)` with `<slug:\1>`

**Comment by czlee** [comment]
nvm, I just did them all using a "Find in Files" function
