### ISSUE TITLE
Allow current wins/team points to be e-mailed to all speakers

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#532]
As a check, à la @philipbelesky's magic at WUDC México 2018.

- E-mail text should be editable as an advanced step, similarly to #531.
- We'll need two default texts, one for two-team formats ("wins") and one for BP ("team points").
- Text should (be required to) include a link to the current team standings, if that page is enabled.
- I think it's best for the count to be merged into the subject line, so that people see the crucial information in their notifications.

**Comment by philipbelesky** [comment]
It might as well also provide a link to the team-specific pages if those are enabled?

If we wanted to get fancy we could also send an email to adjudicators confirming their ballot results —  this wasn't possible, but was desirable at Mexico.

**Comment by philipbelesky** [comment]
Oops — saw this before #535

**Comment by tienne-B** [comment]
The message would not be editable as #531, rather like #535 in a option in the email section. With that, the settings could be added to the BP preset. I might take this on after the others are reviewed; some prerequisites to this are in the PRs, and I don't want to swamp both of you with these.

**Comment by tienne-B** [comment]
So a simple message, just point count (and link). The emails would thus not include information such as the team they just debated against, referring them to the standings URL. I'll take this task. With the default messages in the preferences, a button to send these emails to the speakers could be added to the Confirm Round Advance page.
