### ISSUE TITLE
E-mail entered ballots to adjudicators once entered

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#535]
A check similar to #532.

For consensus formats, either e-mail to chair or to all voting members.
For voting formats, e-mail each adjudicator just their own ballot.

**Comment by tienne-B** [comment]
Might take this on too. The email message/subject would be a configuration setting. As some (English) defaults, I was thinking

* **Subject**: `Your ballot for %debate has been received`
* **Message**:
```
Hi %user,

Your ballot for %debate has been successfully received, with these scores:

%team
 - (%position) %debater: %score
...

If there are any problems, please contact the tab team.
```

The %team and similar parameters are repeated until all the teams are in the message.

For consensus ballots, all the voting members should be emailed in my view.

**Comment by tienne-B** [comment]
Only one thing blocking me right now: The model for `results_speakerscorebyadj` is weird in that it "dances around" the speaker who got the score, only providing team and position. `results_speakerscore` does contain this information though, but I can't find a "Django" way to retrieve it. An SQL query for the purpose would be:
```
SELECT ... FROM results_speakerscorebyadj AS a INNER JOIN results_speakerscore AS b ON a.position = b.position AND a.debate_team_id = b.debate_team_id
```
Is there a neater way, should the debater field be added to the former table, or are we stuck with raw SQL?

**Comment by czlee** [comment]
Great question. Actually, our usual pattern is not to access those models directly at all, but to use the `result` attribute of the `Debate`. This is an instance of `BaseDebateResult` (see results/result.py), and it can be prefetched using the `populate_confirmed_ballots(debates, results=True)` function in results/prefetch.py. If you're grabbing this from a draw (which I assume you are), then there are arguments to `Round.debate_set_with_prefetches(...)` (in tournaments/models.py) that'll do this for you too, I think it's also `results=True`.

If you do this, then you should be able to iterate through everything using various methods of `DebateResult`. In fact, I think the `DebateResult.as_dicts()` method does precisely this; that's the one used in the public scoresheets view (see results/templates/public_ballot_set.html).

Let me know if that helps? Thanks for working on this!

**Comment by tienne-B** [comment]
Thanks! Didn't realize DebateResult could be used. It also makes a nicer format for the scores easier to do:
```
(Gov) Team A
 - Person A: 0
 - Person B: 0
(Opp) Team B
 - Person A: 0
 - Person B: 0
```
