### ISSUE TITLE
Provide a Feedback page that shows just comments

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#537]
Critical information seems to get buried in the comments part of feedback, it was cited as potentially useful at Mexico if there was an easy way to review just a stream of feedback comments (perhaps with the option to click through or reveal the full feedback)

**Comment by philipbelesky** [comment]
Hey @Qantas94Heavy, thanks for your interest! Agree that some sort of filtering method would be great, although I would say that relying on browser's search would be good enough for a first implementation. 

In terms of getting started the "Latest Feedback" page would be very similar to this in terms of its view structure and template — if you essentially duplicate its view/url/template you could probably then make a comments-only page by essentially cutting out the other information from it. Not sure how familiar you are with django, but as some starting points:

- The view class for [latest feedback is here](https://github.com/TabbycatDebate/tabbycat/blob/develop/tabbycat/adjfeedback/views.py#L240)
- The template `latest_feedback` has most of the work done by `feedback_card` — you could either pass a boolean parameter to `feedback_card` card in the template to then cut out the extra information, or make a new `feedback_comments` card sub-template or similar
- Note that feedback questions are configurable, so there can be more than one question with the `text` type. Currently its the implicit last option in a series of switches in `feedback_card.html`.
- To round things out you'll need to add the path for the view in `adjfeedback/urls_admin.py` and a link to it in `templates/nav/admin_nav.html`

Hopefully you haven't had any problems getting a local setup going but let us know if you have any problems with that or any of the above!

**Comment by tienne-B** [comment]
Some filters would be to exclude unconfirmed ballots but include ignored ones (exclusion takes precedence).

**Comment by tienne-B** [comment]
Clarification: Every question (with response) is shown, except for the score (from `AdjudicatorFeedback`) and the source participant?

**Comment by philipbelesky** [comment]
No, I think just those of `ANSWER_TYPE_LONGTEXT` and probably only if they have been answered — the intent is to be able to quickly review the long form comments as teams often leave detailed feedback there that isn't captured within the shorter question types. 

As far as filtering goes I think it would be best to match what the other feedback pages do — i.e. show confirmed/unconfirmed and ignored/un-ignored inline as part of that standard template block.
