### ISSUE TITLE
Create a Venue Status overview page

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#540]
The current results entry page is the only way to get an idea of the ballot's status. A simpler page, showing color coded venues (by group) would be desirable for the purpose of more easily identifying which venues are still missing ballots etc. Ideally this would live update.

**Comment by czlee** [comment]
This sounds like part of a runner management system, right?

**Comment by philipbelesky** [comment]
As it stands it would in effect just be an alternate visual presentation of the results page (i.e. using the existing ballot status codes). So it has value as that, or could be extended/spun-off depending on how a runner management system works.

**Comment by philipbelesky** [comment]
Going to close this as completed (in the most simple sense) as part of #526. Once that system is trialled and/or/if we have a more complete spec for a runner management system we can reconsider this either as an API end point or improvement to what is there now.
