### ISSUE TITLE
If a team ironed last round, check if it's ironing this round

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#541]
As a redundancy check, it's good to check explicitly whether a team who ironed last round also ironed this round. Ideas for achieving this, we should not necessarily do all of them:

- [X] Present a list of teams who ironed last round somewhere in the UI, linked to from an alert.
- [x] Present an alert on the ballot entry page for their next debate, reminding user to check if it was an iron.
- [x] Write an unmissable warning on the paper ballot asking the chair to mark explicitly whether the team is ironing this round.

**Comment by philipbelesky** [comment]
1. Any ideas for where this would be? I guess it could be a button or alert on the results page (perhaps for admin's only) that brings up a modal with more details?
2. Definitely; this seems like the critical use case
3. This should be possible; ideally by substituting an existing UI element so the layout is consistent.

**Comment by czlee** [comment]
On (1), I have about as much of an idea as you do—probably don't want inline, so either a modal or a page.

**Comment by tienne-B** [comment]
I'll take it. I think the easiest solution for (1) is to indicate it in the admin results table (like with the "user-x" icon). Wondering if 2 icons can co-exist, one for the win status, the other as an indicator of this.

I already have a prototype for display in the debate table like for adjudicator chair or dissent, using the "magnet" emoji: 🧲. Didn't really know which would be the most appropriate (maybe 👤 or ⚙️ but they don't really stand out) Suggestions (or for using icons)?

(2, 3) are in the works. For the purposes here, if in a 3-person team format it count as iron-manning to only have 2 people.

**Comment by philipbelesky** [comment]
Sorry, the problem I meant to state with (1) is that because the ballots vanish from the table when entered the record of those prior-ironed-teams also goes with them. So given that there is no longer one single list of that information. Happy to have the icons show that info inline but ideally it would also be augmented by having a consolidated list elsewhere on that ballots overview page to aid manual review of the entered data; perhaps behind a modal popup triggered by a button.

**Comment by tienne-B** [comment]
I don't understand the "ballots vanish[ing]" problem... Check the indications I have implemented.

**Comment by czlee** [comment]
We used to have ballots vanish from the table in the assistant view (but not the admin view) once they were confirmed, but we ditched this back in 7c3eac09dd48ad75abd138a1399d932501f51ccb, is that what @philipbelesky is referring to?

**Comment by philipbelesky** [comment]
Sorry totally forgot the ballots vanishing problem was a behaviour that had been changed ... by code that I myself wrote relatively recently. A consolidated list might also be useful but I can add that in after playing around with an implementation.

**Comment by czlee** [comment]
For what it's worth, by (1) I was thinking of a consolidated list. The in-table indicators help as another quick place to glance, but they don't really fit with the workflow I had in mind, which is to make the indicators unmissable to tab entry staff as they go about with their normal data entry process. (You might not look across the table to the teams when selecting which debate you're entering a ballot for.)

**Comment by philipbelesky** [comment]
@czlee yup, thats what I was thinking — a full list behind a modal popup somewhere. I can add that in after reviewing the PR.

**Comment by philipbelesky** [comment]
I've pushed up two changes. One tweaks the display of the inline icons to make them slightly more obvious and the other adds the modal list describe above. Let me know what you think!

Also, @czlee, I was at a loss for a button-length bit of text to describe 'iron person' for the button, however the title of the modal (hopefully) displays a jargon-agnostic explanation of what the modal is displaying. Does that work?

**Comment by philipbelesky** [comment]
For (2) a warning message indicator I think should work fine, although if possible it would be nice to also include some display in the team name also. It could be as subtle as changing the text color and adding the emoji (i.e. matching the style in the table of #868).

For (3) I wonder if the paper ballot should also indicate the prior-state as well as suggesting the course of action, i.e. something like "A speaker gave two speeches last round, please not if they did so this round also"
