### ISSUE TITLE
Provide means to export and import a tournament configuration

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#544]
Essentially a custom version of presets. In my mind, a Django command both is necessary and will do just fine, because I would use it from a script that I have to wipe a database and reimport a tournament. I'm not sure whether this would be useful from the GUI.

**Comment by philipbelesky** [comment]
If you're doing it form a script anyway you could do a simple fixture export (of just preferences) and then reimport them after you recreate it.

**Comment by czlee** [comment]
Ah, that worked (almost) perfectly. It's a bit restrictive, because it locks the configuration to particular primary keys, but works for now.
