### ISSUE TITLE
Problem with Private URL's

### ISSUE THREAD

**Issue by zettaileido** [TabbycatDebate/tabbycat#546]
Hi!
I'm having problem with the private URL's.
If this is normal, I'm fine but is there a way that the ballots for Asian style debate on the private URL's become separate for all the adjudicator in the room?
Which ever ballot, you have to insert all the judges score.

I was wondering if there is a setting you can change to make it individually possible to insert their ballot.
Thanks

**Comment by philipbelesky** [comment]
Hi Zettailedo, thanks for getting in touch. You're right that this is 'normal' — the assumption Tabbycat makes is that with eballots the chair is responsible for entering in all of their panellists ballots and that (at present) there isn't a way to change this. That's a very Australs/BP centric assumption that we  would like to change this in the future, although it may not be a priority for a little while. Hopefully you can work around this by having chairs and panellist do the data entry together on the chair's device.

**Comment by zettaileido** [comment]
Thank you for your quick reply!
We will wait for the system to change one day!

**Comment by czlee** [comment]
See also: #254 🙂
