### ISSUE TITLE
Check compliance with GDPR (EU Privacy Laws)

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#550]
These go into effect on 25 May 2018. Given we provide just software rather than SaaS I don't think we count as data controllers or data processors for compliance purposes, although there may be some features that need to be made compliant:

- [x] Enforce HTTPS (at least on heroku)
- [ ] Explain why IP data is gathered (on ballot entries)
- [x] Ensure sessions are expired
- [x] Use OAuth for any API access

It might also be worth adding something to the docs about how tab directors should ensure GDPR compliance in how they manage data gathering and storage.

**Comment by czlee** [comment]
Sounds like you already have an idea of what GDPR entails, do you have any links to resources shedding light on its relevance to tabulation? It surprises me a little that its requirements are that technically specific.

(Also, we already enforce HTTPS on Heroku sites, unless the site administrator disables it.)

**Comment by philipbelesky** [comment]
The [parts that are that specific](https://www.reddit.com/r/django/comments/7tjyvd/mainly_for_eu_but_does_affect_the_world_gdpr/) are just gathered from pretty second hand information, but seem plausible. There was another source that echoed them that I can't find any more. The more [general documentation](https://www.cennydd.com/writing/a-techies-rough-guide-to-gdpr) that [I've found]( https://www.infoq.com/articles/gdpr-for-software-devs) is much more about the responsibilities/process.
