### ISSUE TITLE
Sequences in Edit Motions should auto-increment

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#588]
I think this used to happen: that in the edit motions page the `extra` forms would display sequences that incremented; i.e. 1,2,3. Currently they all show as 1,1,1.

**Comment by czlee** [comment]
iirc the seq field used to be blank, it probably changed when we gave it a default. This is surprisingly nontrivial to do, the behavior of `extra` and `initial` in formsets doesn't quite seem to match the Django docs.

**Comment by czlee** [comment]
Just kidding, if you read the docs for _model_ formsets [very carefully](https://docs.djangoproject.com/en/2.0/topics/forms/modelforms/#id2), you'll eventually pick up on this sentence:
>However, with model formsets, the initial values only apply to extra forms, those that aren’t attached to an existing model instance. 

Hence, done in 4e8ca1656942b9e899a729a3b134a03037444b68.
