### ISSUE TITLE
Send Push Notifications On Round Creation

### ISSUE THREAD

**Issue by tfpk** [TabbycatDebate/tabbycat#652]
I've been thinking for a while about how we can best notify users of new rounds and room allocations. Viran tested using mobile notifications at a recent tournament, and I think it was a resounding success, but I suspect that push notifications may be a more effective option, for three reasons:
1) They work over wi-fi: 
At local tournaments, clearly this isn't an issue, since SMS would work just as well. Here I'll only note that I don't think you lose anything, since almost everyone would be likely to have wifi/data too.
At international tournaments however, cell service isn't guaranteed. I think wifi is much more likely to be (after all, people are going to want to check the tab).
2) They're free:
Admittedly, 5.c a message isn't a lot. But at Easters, for instance, assuming 6 rounds, 3ish start of day notifications, 400 participants (Ignoring directors etc.), that's nearly 400$. Perhaps that's change compared to the voluminous amounts of alcohol required for a good debating tournament, but I think it's relevant.
3) They're opt in:
Don't know how relevant this is, but I think that if someone is concerned about giving their details out, it's much easier to have them opt in than opt out of this service.
4) They don't preclude using SMS as well/instead:
At this recent tournament, I raised the possibility of exporting templated messages for one of those SMS services. This would be a large step towards doing that.
5) They don't imply an ability to reply:
One of the issues we observed at the tournament was people trying to text back to the number. SMS inherently implies that it's 2 way communication, but push notifications don't.

Clearly they're not perfect; some drawbacks include:
1) They're opt in:
Admittedly, this is probably more of a drawback. That said, I think it's okay, since this is a feature, not a requirement. Also, the smooth but stern voice of a tab director could probably get a large number of people to sign up to this.
2) Version support is required:
Push notifications, to my current knowledge are supported on iOS 11 (which has 85% market share among iOS devices), and lots of android versions (let's be honest, most debaters probably have iPhones anyways). Even so, I think even a 50-60% coverage at a tournament would be useful.
3) They're not loud
As far as I know, there's no way to make a sound when you recieve a push notification.

I'm interested in your opinions, since I've got a few weeks to prototype over the Uni holidays - do you think this is feasible/useful?

**Comment by czlee** [comment]
Hey Tom! In something that won't surprise @philipbelesky, my take on it is that it's a great idea but [outside the proper scope of tab software](https://www.facebook.com/notes/chuan-zheng-lee/on-the-development-of-debating-software/10154940672617715). That is, I think doing this well is harder than it sounds, and I think the interaction with tab software isn't actually that significant—at most you need peoples' contact numbers or email addresses, which really comes from reg, not tab, and even then not really if they're an opt-in system. Unless you want to include individualized messages about precisely where people are going, à la [Tabroom](http://docs.tabroom.com/Live_Updates), in which case there's more of a case for it, and this discussion is more involved.

I have other thoughts on this, both pros and cons, but I'll leave them for later. That said, push notifications would require users to install an app, wouldn't they?

**Comment by tfpk** [comment]
I was thinking that the messages would be indidualised, and though you're right that phone numbers would be needed for SMS, all we would need to do is export data. Someone could then join that on a table of phone data. 
Also, the reason I propose this is because you don't need an app! Look up service workers and web notifications if you'd like to know more about it, but it's the same stuff news sites now use to give notifications of articles. Its underused imo, but I think there are great applications here.

**Comment by philipbelesky** [comment]
My understanding is that the standard push API isn't supported on mobile versions of Safari. There is an Apple push notification service that could complement the standard API but that would requite a developer account and certificate setup that is probably a non-starter for a decentralised service.

**Comment by tfpk** [comment]
Ahh damn - I have been misled. I was working on another project and was under the impression we were using standard web push notifications for both iOS and Android. I couldn't test since I'm only on Android. That really sucks - I think this idea is kind of moot then. Thanks Phil...
