### ISSUE TITLE
Internal server error report

### ISSUE THREAD

**Issue by zettaileido** [TabbycatDebate/tabbycat#654]
I hit an internal server error while trying to load this URL:
https://myty-brothersxx.herokuapp.com/geminicup2018/admin/

Please describe what you were doing when the error happened, along with any other useful information:
After the tournament ended, it suddenly made it not accessible and no one can see the tab.
I got the page with says Internal Server Error (500) but I didn't receive any email concerning this.

**Comment by philipbelesky** [comment]
Hi @zettaileido thanks for opening this issue. From the error reports on the instance of the app it seems like there are "too many connections for the database role." I think you should be able to ameliorate this by going to your heroku dashboard and then restarting the app.

The reason for this (I think) is that the free tier of heroku has a relatively limited number of users can connect to the database at once. Normally however those connections close after a page has loaded so finding this particular error is very unusual.

That the connections seems to be persisting suggests they are not closing for some reason, so it would be great to let us know if any of the following (or other circumstances had occurred):

- Had you changed the database settings in heroku some time shortly before this error?
- Might there be a number of computers that are still logged in to tabbycat somewhere? Particularly if they are on the checkins page or tournament admin page
- Was there any strange behaviour you noticed throughout the tournament before this; such as pages not loading or other error messages that came up?

**Comment by zettaileido** [comment]
Thank you so much!
Restarting made it work as normal!

**Comment by philipbelesky** [comment]
@zettaileido great to hear, did you come across any of the scenarios mentioned in the bullet points here?

**Comment by zettaileido** [comment]
The internal server error was solved after I restart all addons.

After I deployed app, such an error occurs occasionally.
And what is worse we cannot enter the admin area when this error occurs.
So restarting addons is only a solution against Internal server error
