### ISSUE TITLE
Expensive Query: PublicCurrentTeamStandingsView

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#661]
On a typical in-rounds basis the team standings page query (according to scout) takes much longer to generate than other public views — it's up at 540 queries in 3200ms. For comparison then next-slowest view is 500ms and the other views >250ms. 

Some of this may be unavoidable due to the nature of what data that page shows but there may be some scope to create more efficient queries or check for cases where we are looping over a queryset or something.

**Comment by czlee** [comment]
540 queries is definitely not unavoidable, I'll have a look tomorrow. That page should be at most 40.
