### ISSUE TITLE
Deal with button overflow

### ISSUE THREAD

**Issue by tienne-B** [TabbycatDebate/tabbycat#665]
In pages like the `privateurls` index, there is a wealth of buttons. When the page is resized, the buttons move in response. However, in French, starting at a width of 992px, all the buttons are placed on the same line, even though there is not enough space for all of them, and could be broken up.

**Comment by philipbelesky** [comment]
Yea, there appears to be a kind of deadzone between tablet-width of ~970px and ~1240px (variable based on quantity/length of buttons) where they are shown on one line with clipping. In this case the easiest fix would probably be just to reduce the verbosity of the buttons such that their natural width fits better. 'Generate Private URLs > Generate URLs' and perhaps shifting the 'print' and 'email' text into a grouping button before each. 

PS let us know (maybe email tabbycat@philipbelesky.com) if you'd like to help out with the french translations!

**Comment by philipbelesky** [comment]
I've had a quick go at this in 1b0bcbf34c6fa84cbd525f9e5afe19b568a4c0db; let me know if you think that's sufficient or have any other feedback.
