### ISSUE TITLE
Send notification to adjudicators on draw release

### ISSUE THREAD

**Issue by tienne-B** [TabbycatDebate/tabbycat#671]
Continuation of #652 but within the framework being created with #653. The main details are in the former task, which was closed due to the infeasibility of the proposed method. This task takes the extensible e-mail approach.

**Comment by tienne-B** [comment]
Having #679 merged would be best before starting work of this feature.

**Comment by philipbelesky** [comment]
Sounds good! Is #679 ready — if not let us know when you'd like it reviewed

**Comment by tienne-B** [comment]
Yes, the pull request is ready; additional work would be in future ones.

**Comment by tienne-B** [comment]
Should the email contain

* The adjudication panel (with institutions), or
* Available motions

in addition to the basic "w"s: **w**hen (round) / **w**here (venue) /(against) **w**ho / **w**hich (side)

Also, should adjudicators get a similar notification for them to know where they are judging?

**Comment by czlee** [comment]
Adjudicator notifications are actually probably more useful than debater notifications. Adjudicators sometimes hang around not in GA (but just outside or something) to avoid crowds; debaters can't really do this because then they'll discover the motion after everyone else.

I don't really see any harm in including the adjudicators with institutions and available motions, though institutions should depend on the "show adjudicator institutions" setting and motions on whether motions are released. (They typically won't be at draw release, since the draw is released before motions are in limited prep tournaments.)

**Comment by tienne-B** [comment]
I do have a patch ready for adjudicator notifications, but which does not include institutions for them (does show Team affiliations) nor the motions, as they would come after, and are less relevant for the adjudicators.

**Comment by tienne-B** [comment]
This task is not yet finished, with some more items on the list before completion: (Might add some _au fur et à mesure_)
* [ ] How to deal with emails when un-releasing/re-releasing draws
* [ ] Being able to send similar notifications to speakers for their team's assignment

Emails sent when re-releasing a draw could check for whether the venue is the same before re-sending, as that is the most vital information.

The second point would be less useful (as @czlee points out), however they could still be useful as a reminder if forgot or something.

**Comment by philipbelesky** [comment]
@tienne-B @czlee do you think the unrelease/release issue and speaker assignment notification are enough to prevent this being released?

**Comment by tienne-B** [comment]
The lack of speaker assignment notifications shouldn't prevent release. The
email notice could be updated when they are included.

Less sure for the unrelease/release issue. Deferring it. Don't think it
should be a blocker, but it could be possible to add a sentence like "This
is your updated assignment" if the assignments are re-released.

**Comment by tienne-B** [comment]
Changed title to better reflect resolution. Created #792 for the big point.
