### ISSUE TITLE
Extend or duplicate StandingsMissedDebates preference to reply speeches

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#675]
At the moment speaker tabs have the capacity to hide speakers who have missed rounds — i.e. the members of a swing team. The same capacity is not present for the Replies tab although the use case is similar.

We could extend `StandingsMissedDebates` to cover the replies tab also, although it would probably be preferrable to create a second preference just for replies so they can be set independently. While it would be nice to start cutting back on preferences, rather than adding them, this shouldn't be too confusing given it can exist alongside the missed standings one.

This is desired but not critical for the Australs tab so let me know if you had any thoughts as to extending vs duplicating @czlee. I can then implement it today/tomorrow.

**Comment by czlee** [comment]
I'd lean towards duplicating. Given how often tabs tend to be asked to support all sorts of different things, if the problem is that we have too many preferences, I feel like the solution isn't to have fewer of them.

**Comment by philipbelesky** [comment]
Ok cool, have done so in 7d135feebcf779288a9cf76fb147759933b93567 if you'd like to review (its been deployed to australs)

**Comment by czlee** [comment]
Cool! (I assume you mean 143cf38778ccbd10fe2c9cfd5e848785ecf74511?)

**Comment by philipbelesky** [comment]
Err yes that's the one, reference would have changed after I force pushed up an ammend.
