### ISSUE TITLE
Public ballot submissions should save which adjudicator's link was used

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#683]
Kind of funny that we haven't thought of this before now, but at the moment it just saves IP address, given that private URLs are the norm it probably makes sense to take note of which adjudicator's URL was used to submit the ballot.

(Doesn't make so much sense for feedback since that's effectively already done.)

**Comment by tienne-B** [comment]
Should this issue be extended to cover feedback forms with the migration of `url_key` towards `Person` and not just `Adjudicator`?

**Comment by czlee** [comment]
In principle yes, though I think the better thing to do is park this till we've figured out #684. It might just be that this whole issue becomes obsolete as the result of the restructure to support notifications and logging of participant actions.
