### ISSUE TITLE
Upgrade to Django 2.1

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#714]
Brief thoughts from skimming release notes:

- [ ] Fix compatibility with Jet
- [ ] IIRC there are a few cases where we awkwardly get the full absolute url that could be switched to using `HttpRequest.get_full_path_info()`

**Comment by czlee** [comment]
Hmm, I think the "view permission" thing requires us to implement #131 to be useful. Our current practice is to make tab directors and CAs superusers, and having superuser access overrides all permissions anyway. ([docs](https://docs.djangoproject.com/en/2.0/ref/contrib/auth/#django.contrib.auth.models.User.is_superuser))

**Comment by philipbelesky** [comment]
Reopening this until [this issue is merged](https://github.com/geex-arts/django-jet/pull/343) and jet updated
