### ISSUE TITLE
Implement prefetching in get_table_by_team

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#727]
Currently the per debate results view employs prefetching. 7e4a21bfcbc49c69cbc05580da9d85cc0b2ee2d9 implements prefetching adjs/institutions which seems to have cut down on the duplicate queries in that view. 

However the per per team view does not employ prefetching as it constructs the list of debates from team scores. I think this should be able to switch to use `debate_set_with_prefetches` if the appropriate filter can be set. 

Relates to #676 but would be good to have in the hotfix as its public-facing.

**Comment by tienne-B** [comment]
Eh, yes it does use prefetching:
https://github.com/TabbycatDebate/tabbycat/blob/e1f83ad8567328af2f6f82c40ffbb54e8656e330/tabbycat/results/views.py#L145-L151
The problem is probably that it does not prefetch `debate_team__debate` specifically. I'll check if that is the case.

**Comment by philipbelesky** [comment]
Sorry, should have been more precise there, by 'does not employ prefetching' I meant to say does not employ the abstracted `debate_set_with_prefetches` that is used elsewhere. I've addressed this in c01f8f3b7375c6906c52321b9f31766ba0ff78bb so will close this but will follow up with a comment on your PR as to why that did not address the issue.
