### ISSUE TITLE
Integrate with Tabbie2 for results querying

### ISSUE THREAD

**Issue by nzervoudis** [TabbycatDebate/tabbycat#734]
One of the major (and few?) advantages Tabbie2 has over TabbyCat is that participants can access a record of all past performances, and more generally look up past tournaments with great ease. 

Given the trend of more tab teams (rightly) switching to TabbyCat over Tabbie2, I was thinking that a relatively quick/inexpensive way of retaining this benefit could be to export TabbyCat results into Tabbie2 after each tournament as an alternative to rebuilding TabbyCat into something similarly centralised. However, I have no idea how feasible that is (and is obviously firmly in 'nice to have' territory)

**Comment by czlee** [comment]
I think you're spot on, and @philipbelesky and I had actually proposed something even broader than this in a [_Monash Debating Review_ article in 2015](http://mdr.monashdebaters.com/volume-13-2015/the-start-of-history/). The gist of it is to define a standard XML-based or JSON-based tab archive format that _all_ tab software would follow, that people could then use for lots of purposes, including (but not limited to) a third-party central results repository.

Sadly, our efforts on that gave way to adding BP support and preparing for WUDC 2019, which now consumes our entire Tabbycat bandwidth. But it's open for anyone else to pick up, and if someone does, we'll gladly work with them to define a format and make Tabbycat compliant with it. 😊

Discussions (currently mostly dormant) are here: https://github.com/TabbycatDebate/dta-spec. We don't intend for this to be a Tabbycat thing though, it's just hosted under that organisation for convenience.

**Comment by philipbelesky** [comment]
Going to close this for now, although continue to comment if you have thoughts. If we want to look at the issues above we could probably do so in the dta-spec repo or as more targeted issues here once its more realistic that we can begin to tackle this problem.
