### ISSUE TITLE
Implement Celery (and use for email notifications)

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#740]
This is one for @tienne-B that hopefully ties in to the existing work on the email app but also adds some infrastructure that can be useful elsewhere.

For context, #590 (has more details) we want the ability to run longer tasks on workers. This is both to escape the 30-second dyno limit and to free up dyno resources that long-running tasks consume. My understanding is that its standard practice to offload the actual emailing process to a worker in this same fashion, so that could be a good starting point for this wider aim/infrastructure.

If you checkout the `celery` branch I've started to set this up although I was having some import path issues. If you were looking something to do getting celery up and going (and using it to implement the email sending) would be super useful. You could then have a crack at implementing it in other areas (say adj allocation) or we could take over at that point.

**Comment by tienne-B** [comment]
Have 12 commits waiting (and #730 in study), guess I could have more :)

Should I continue on `celery` (which is not on `develop`), or cherry-pick to be on `develop`? The notification tasks would be in the `notifications` app (and not their respective applications) IMO, but `eudc` branched off before the app was created.

**Comment by philipbelesky** [comment]
Um feel free to abandon/restart the `celery` branch — I didn't get very far with it. Or feel free to merge develop in to it. The EUDC branch is tournament specific so will be deleted without being merged back in at some point (it exist just to cherry pick specific commits from develop).

**Comment by tienne-B** [comment]
I'm getting a lot of action time-outs with `.delay()`...
```
2018-08-13 03:07:31,876 - WARNING - server - Application instance <Task pending coro=<AsgiHandler.__call__() running at /tabbycat-cloned/venv/lib/python3.6/site-packages/channels/http.py:190> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/futures.py:403, <TaskWakeupMethWrapper object at 0x115034af8>()]>> for connection <WebRequest at 0x115296978 method=POST uri=/demo/admin/privateurls/email/ clientproto=HTTP/1.1> took too long to shut down and was killed.
```
I'll try with some other methods.

**Comment by philipbelesky** [comment]
Hmmm, if you push up your branch I could have a look at it? Is this just when running with `runserver` or is a seperate celery worker also running?

**Comment by tienne-B** [comment]
It's as that PR. It's with running with `runserver`.

**Comment by philipbelesky** [comment]
Hmm I had a play in d92a5ac6ebc2ebbfde085ba9fab3eec630b02fa7 and found similar issues with the .delay() although it worked without it. I suspect this is something to do with the async nature of Daphne/channels itself.

Changing tack here, I wonder if this was slightly misguided to use Celery in the first place. We already have Channels which is capable of [running simple background tasks](https://channels.readthedocs.io/en/latest/topics/worker.html). That would also have the benefit of working the same across local/heroku installs. Thoughts @tienne-B ?

**Comment by philipbelesky** [comment]
I think Celery is, in general, the best/standard tool for this kind of job. However given the problems in its setup and the fact channels is already implemented it provides a means to in effect do the same thing but without the added complexity.

For `messages` I think that should be equally easy (or hard) to do with either celery or channels. Off the top of my head, one way would be to push the message to the next page load using the standard messages framework. The other way to go would be to have a Vue component that subscribes to a new websocket channel dedicated to notifications (or perhaps subscribes to the existing action log stream, like on the tournament dashboard).

**Comment by philipbelesky** [comment]
Going to tentatively consider this closed via #849, thanks again for your help implementing this!

**Comment by tienne-B** [comment]
Is it working on Heroku? It's not sending messages for me (with Redis up and running) on my local install.

**Comment by philipbelesky** [comment]
Ah right if it’s only working for private emails I suspect there is some problem with the information sent from the other methods. Annoyingly the worker process doesn’t seem to report exceptions so I had to do a bunch of ‘print’s to figure out where it was stopping and what was wrong. I'll check those soon unless you'd like to look into it

**Comment by tienne-B** [comment]
As a part of the PR (in a few days)

**Comment by czlee** [comment]
Re why `hasattr()` doesn't work, that's now what you use to check for the presence of a key in a dict, see https://github.com/TabbycatDebate/tabbycat/commit/28f2c108842fa0132daaccd8544439d8ca4b786a#commitcomment-30776006. I'd fix it myself but I'm still working on getting Redis going locally, so I can't test it.

I notice the [Channels docs](https://channels.readthedocs.io/en/latest/topics/worker.html) say:
>The worker/background tasks system in Channels is simple and very fast, and achieves this by not having some features you may find useful, such as retries or return values.
>
>We recommend you use it for work that does not need guarantees around being complete (at-most-once delivery), and for work that needs more guarantees, look into a separate dedicated task queue like Celery.

Do you have a take on the relevance of this for us?

**Comment by philipbelesky** [comment]
The lack of return value was the thing that I noticed and did some digging on. In the case of doing so an adj allocation as a background task this doesn't matter as our 'return' action there is to notify a channel which then pushed the data over a websocket. So because the result of that process is going to be communicated in an async manner we don't need a synchronous return to the function itself. 

In the case of emails its a bit annoying that we can't return a notification at the end of the sending process; at least not unless we rig up some asynchronous alert style system. We could perhaps make an `ActionLog` type action for the cases where the emails fail to send. I don't think Celery would necessary be better here either — handing a task of to a worker means needing to accept an asynchronous outcome from it.

**Comment by philipbelesky** [comment]
Perhaps a useful stop-gap to full async notifications would be to create an action log type for "Successfully finished/failed" sending emails? It would then at least show up on the Overview page and probably a time when there aren't a whole stream of other logs.

**Comment by tienne-B** [comment]
Also, when the records are created, the email buttons (for types activated that way) are disabled, which would serve as an indication that such messages were sent. The success message is there in between the time the emails were actioned and sent out.

**Comment by philipbelesky** [comment]
Closing this as completed in a general sense; feel free to create new issues for specific enhancements
