### ISSUE TITLE
Finish translating strings in Vue templates

### ISSUE THREAD

**Issue by tienne-B** [TabbycatDebate/tabbycat#744]
Strings provided by Vue templates do not seem to be translatable, of which is an omission of the i18n efforts. For consistency, these strings should use `gettext`.

**Comment by philipbelesky** [comment]
There is the capacity to translate strings in Vue — checkout the `DiversityContainer.vue` and the corresponding `djangojs.po` files in the language folders for an example. Note that as per the contributing doc these need to be updated manually. 

At present we've focused only on the public-facing templates but intend to do the later ones at some point. Feel free to start adding them — we could use this issue as a tracker?

**Comment by tienne-B** [comment]
This can be a tracker task. Thanks for telling me the method! I'll be adding some templates strings soon.

**Comment by philipbelesky** [comment]
Yea I definitely looked in to more automated methods - the problem becomes that we want to be able to draw from the mo/po files for this (and transifex) whereas the Vue/is native approaches tend to use distinct formats that don't play nice with that.

Shall we track things file by file perhaps? Up to you. Just a heads up that the adj allocation templates will be redeveloped over the next few months so it might be worth skipping those and I'll add the translations as I refactor.

**Comment by tienne-B** [comment]
By update manually, I assume it is to add entries like:
```
#: templates/tables/CheckboxTables.vue:47
msgid "Copy From Check-Ins"
msgstr ""
```
to `en/.../djangojs.po`, then run the make/compile commands. I don't understand what you mean by "Shall we track things file by file perhaps? Up to you." Could you clarify how it would work (hope it isn't that you pass through the file to add the individual strings). I'll skip adjudicator allocations, but I've already translated all the available strings to French :)

**Comment by tienne-B** [comment]
For reference (without any priority assigned):
- [ ] ~~`AdjAllocation`~~ (ignored)
  - [ ] `EditAjudicatorsContainer.vue`
- [ ] `Availability`
  - [ ] `CheckInScanContainer.vue`
  - [ ] `CheckInStatusContainer.vue`
  - [ ] `PeopleStatusMixin.vue`
  - [ ] `VenuesStatusMixin.vue`
- [ ] `Divisions`
  - [ ] `AllocateDivisionsContainer.vue`
  - [ ] `DivisionDroppable.vue`
- [ ] `Draw`
  - [ ] `EditMatchupsContainer.vue`
- [ ] `Printing`
  - [ ] `PrintableBallotHeader.vue`
  - [ ] `PrintableDebateInfo.vue`
  - [ ] `PrintableFeedback.vue`
  - [ ] `PrintableFeedbackQuestion.vue`
  - [ ] `PrintableScoresheet.vue`
  - [ ] `PrintableTeamScores.vue`
- [ ] `Tournaments`
  - [ ] `TournamentOverviewContainer.vue`

Another thing I hope is that the line numbers are not mandatory; because then there's another thing to keep in mind when making changes.

**Comment by philipbelesky** [comment]
Yea the line numbers shouldn't be mandatory, feel free to omit. The file name is probably important in identifying redundancies in future though.

**Comment by philipbelesky** [comment]
I believe I tried that earlier on, iirc the problem was that it compiles the po files into a JSON file. That then doesn't really work with django's own i18n implementation for js that serves a distinct file based on the current language code. 

In an ideal world we would use something like `vue-gettext` and be able to bundle the translations as part of our other javascript bundles but I didn't have time to figure out how to get it such that a pure vue solution would work with django.

**Comment by tienne-B** [comment]
Is there a separate procedure for compiling messages by Vue? Terms such as "Find in Table" do not translate (even though they are in `djangojs.po`, and was compiled.

**Comment by philipbelesky** [comment]
Were they compiled using `dj compilejsi18n -l fr` (as per the CONTRIBUTING.rst)? I just did so and that seems to have copied the "Find in Table" string over to `jsi18n/fr/djangojs.js`. 

However, note that to show those during development you then need to also run the "cp-i18n" task defined in package.json (normally this is run as part of the build task but not as part of the serve task).

**Comment by tienne-B** [comment]
Yeah, it was the last "cp-18n" that I didn't know about. Good now.

**Comment by tienne-B** [comment]
@philipbelesky (referring to https://github.com/TabbycatDebate/tabbycat/issues/744#issuecomment-412318503): Same for the refactored `draw` Vue templates I hope ;)
