### ISSUE TITLE
Catch UnknownTimeZoneError on start page (BACKEND-VS)

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#753]
This seems to be a pretty rare event, but in the case that someone has entered an incorrect timezone string its not a great experience to have the first page they see totally crash. At the least we should catch the except there, just some arbitrary correct time zone, and notify the user that this has happened.

**Comment by czlee** [comment]
Sentry issue: [BACKEND-VS](https://sentry.io/tabbycat-ig/backend/issues/647477692/)

**Comment by czlee** [comment]
Hmm, this stack trace doesn't go through any of our code. Is this even possible? I'm not sure that you can catch an error due to improper configuration.

**Comment by philipbelesky** [comment]
Ah true. If its not possible or probable it doesn't seem like it is worth the effort — at least not until this becomes more widespread.
