### ISSUE TITLE
Break calculator doesn't update after teams are excluded

### ISSUE THREAD

**Issue by viranweerasekera** [TabbycatDebate/tabbycat#759]
When excluding teams from the break (eg. because they were ineligible, capped, lost a coin toss, etc.), the calculator should:
1. Clear the break rank of the excluded team(s)
2. Adjust the break ranks of the team(s) below the excluded team(s), and
3.  Promote the next team(s) who were previously not in the break such that it's filled.

It currently doesn't appear to do any of those things (ie. adding a remark has no effect on the breaks) so the user has to update each BreakingTeam object manually with the new break ranks, and/or add in new BreakingTeam objects to fill out the break.

**Comment by philipbelesky** [comment]
Closing this as it doesn't seem to be reproducible, let me know if that's not the case though!
