### ISSUE TITLE
2 Motion Impromptu Format Ballots

### ISSUE THREAD

**Issue by 0zlw** [TabbycatDebate/tabbycat#761]
Hi all. I'm preparing for a NZ Easters style impromptu schools tournament (with 2 motions, where motions are not revealed until teams are in the debate room) and I am intending to record motion selection as well as print ballots. (with the 'motion vetos' setting off).

I came across two issues while playing around with the configurations settings. 

1. With 2 motions entered, the printed ballots are not formatting the motion box correctly. 

![image](https://user-images.githubusercontent.com/3196468/44218751-77cc1b00-a1ce-11e8-98b7-2a4c4beeefcc.png)

![image](https://user-images.githubusercontent.com/3196468/44218781-8b778180-a1ce-11e8-9410-939705777f26.png)

2. I was intending to enter the motions into tabbycat in advance of the tournament, however because we do motion selection in the debate room I don't want the ballots to include the motion. This is because adjudicators usually give the ballot to the teams to fill in their names/speaking order first so they would see the motions before they should. I will still enter the motions after we have printed the ballots because we want to collect data on motion selection.

A potential feature here would be to have a setting to select whether or not the motions should be printed on the ballot. I understand that the general expectation is that motions are entered during the tournament flow, but I think this feature would help guarantee that the motions do not get released earlier than intended.

Thanks!

**Comment by philipbelesky** [comment]
Hey @0zlw thanks for the detailed issue. (1) definitely sounds like a bug — I'll check the format settings and confirm/fix. (2) sounds sensible as well and would have a broader use. Both 1 and 2 could be fit into a 2.1.3 release sometime in the next week — would that be in time for your tournament?

**Comment by tienne-B** [comment]
For me, the motion was formatted well, it was the judges list that wasn't :p

With more motion-type preferences, should it be spun off into a new section of configuration?

**Comment by philipbelesky** [comment]
True, could you confirm which version you are on @0zlw? In this case the preference would probably join `ballots_confirm_digits` in `data_entry` given its related to just the ballots themselves. But yea there's definitely a need to split up preferences in general — perhaps splitting off motion-related preferences could be a part of that.

**Comment by 0zlw** [comment]
Thanks for the prompt reply - the tournament is tomorrow and I have a workaround for both issues so no need to urgently push a bug fix. I'm running v2.1.2.

As an aside I tried the 2 motion thing with veto recording on and it displayed fine, only showing 2 circles to select from. (It also obviously showed the veto circles which weren't relevant)
