### ISSUE TITLE
Modularise settings files by environment

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#786]
Ideally our settings would be split per environment so we can reduce overlap, at current count that would mean:

- Core settings
- Local
- Heroku 
- Travis
- Development settings

Each could be imported based on either the presence of the file (local/dev) or environment variables. It would also mean (if we wanted) we could also have sub-settings pages for specific parts of core settings — i.e. caching.

Ideally these settings would live in the root `config` directory but I wouldn't mind a new `settings` directory under `tabbycat` (this does make the path imports easier).

Initially I tried this with [django_split_settings](https://django-split-settings.readthedocs.io/en/latest/) but had some problems working on Heroku, I think due to the transient file system. This would be the ideal method if it did work though — it provides a much cleaner means of importing/splitting.

Failing that I tried just using the current import approach used for local_settings but extending that to additional modules. Heroku was not happy with that, last bit I got to had it failing to import the file due to not being able to follow the import pattern used for local_settings. 

Current progress is on `feature/modularise_settings` branch.

**Comment by sobolevn** [comment]
@philipbelesky Hey, `django_split_settings` author here. 

What kind of issues did you have? I have several project that use `django_split_setting` and `heroku` without any problems. 

Would be glad to help.

**Comment by philipbelesky** [comment]
Hey @sobolevn thanks for reaching out, and for your library. The docs are great and I found it super easy to implement. The problem I mentioned above was definitely lies in something atypical within our app itself or more likely more me overlooking something obvious; not in `django_split_settings` or Heroku. 

In answering this I dug back into that branch to try and figure out what the problem I initially encountered was and in doing so seem to have gotten it to work properly. Thanks for the prompt!

**Comment by philipbelesky** [comment]
@czlee @tienne-B note that this has been merged; the `CHANGELOG` has instructions for how to migrate over your local/development settings. I might split up `core.py` into distinct components at some point also, but feel free to have a crack at that if you find it interesting

**Comment by czlee** [comment]
Currently, I get the following, when set up with `export LOCAL_DEVELOPMENT=True`:

- `development.py` fails at the line `from core import *` because I presume it should be a relative import `.core`, not `core`?
- When I change it to `.core`, settings from `core.py` then overwrite those in `local.py` (because `development.py` is imported after `local.py`, which causes `DEBUG` to be `False`.

Just checking if I'm missing something?

**Comment by tienne-B** [comment]
The sphinx build command is now stuck in a loop, with it stating that "docs/.doctrees/about/authors.doctree changed" in a loop without having changed anything.

**Comment by philipbelesky** [comment]
@czlee sorry there was a difference between the example file and my local file that I missed — that import core should not be there at all (I've pushed a commit to amend this). 

@tienne-B that seemed to be a bug in `sphinx` — updating to the hotfix (also in a commit) has it working fine for me now.

**Comment by tienne-B** [comment]
And the development toolbar does not show (with `LOCAL_DEVELOPMENT` and `ENABLE_DEBUG_TOOLBAR` set to `True`)

**Comment by tienne-B** [comment]
Oh, thought it was a setting. Works now.
