### ISSUE TITLE
Email notifications: add speaker to team assignment

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#791]
Add the ability to email out speakers noting what their team is. It might be good to think about how this could be used in conjunction with team codes.

**Comment by tienne-B** [comment]
A list of "variables" that could be included in the email. Feel free to expand or contract:

Variable | Description
---------|------------
TOURN | tournament name
SHORT | short name
LONG | long name
CODE | code name
EMOJI | attached emoji
INSTITUTION | affiliation
DIVISION | division
BREAK | break categories that the team is eligible for (if they perform well)
SPEAKERS | list of members

Am I missing any (or should remove any)?

**Comment by tienne-B** [comment]
Maybe it could be useful to list entered conflicts/constraints (this could also apply to adjudicators)

**Comment by czlee** [comment]
Hmm, yeah, that's not a bad idea. New issue, if you want?

**Comment by tienne-B** [comment]
Nah, the patch is déjà ready; just waiting now :)
