### ISSUE TITLE
Email notifications should use team code names if applicable

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#804]
Just making a note that currently the "draw released" emails sent to adjudicators use `debate.matchup`, which (always) uses real names. Ideally we'd want to use code names if code names are enabled for the public, and real names if they're not. (That is, we'd want to use the same names as are used in the public draw.)

Unfortunately there's currently no single convenience function for this _within_ `Debate` or `DebateTeam`, because it depends on a tournament preference. I think we'll need to construct the relevant string from within `draw/utils.py`, or do some refactoring. There _is_, however, a convenience function `use_team_code_names()` in `options/utils.py`, that interprets the preference cleanly, because there are five choices for various permutations.

Relevant bits of code (as of 531faa3056bd3892dcf3138a7bf86814a2666471):

https://github.com/TabbycatDebate/tabbycat/blob/531faa3056bd3892dcf3138a7bf86814a2666471/tabbycat/draw/utils.py#L60-L66

Example of existing code for choosing between code name and real name (this is the code used in the tables constructor):
https://github.com/TabbycatDebate/tabbycat/blob/531faa3056bd3892dcf3138a7bf86814a2666471/tabbycat/utils/tables.py#L197-L213

**Comment by czlee** [comment]
I also just realized similarly for ballot receipts (line 281):

https://github.com/TabbycatDebate/tabbycat/blob/531faa3056bd3892dcf3138a7bf86814a2666471/tabbycat/results/utils.py#L280-L284

**Comment by philipbelesky** [comment]
Closed in #805
