### ISSUE TITLE
Notifications: No tick box for "Team Points Message"

### ISSUE THREAD

**Issue by 0zlw** [TabbycatDebate/tabbycat#844]
Messing around with the new notifications feature (woo!). There doesn't appear to be a checkbox for enabling/disabling this notification. 

![image](https://user-images.githubusercontent.com/3196468/46147127-ba4a4280-c2b8-11e8-96e3-ddd88f214f12.png)

![image](https://user-images.githubusercontent.com/3196468/46147138-c33b1400-c2b8-11e8-9560-4f7be6ed412f.png)

Also the checkboxes have increased in size since v2.1.2, but I am guessing this may be intentional for mobile support. 

Produced in v2.2.0, Windows 10, Google Chrome.

**Comment by tienne-B** [comment]
No there is no tick-box to enable/disable team point messages as the notifications are activated manually (through a button labeled "Email ...") in the round advance view. The tickboxes are there for notifications sent automatically.

Ballot receipts had to be integrated in the submission button (and thus automatic) as public submissions should be straight-forward (and not have adjudicators making these sorts of decisions), while adjudicator draws may be more time-sensitive so having it automatic was a plus.

**Comment by 0zlw** [comment]
Ah I see, having it there makes sense. In that case, I think it might be helpful to add this into the configuration notes somewhere as I can see this as being something people would think about when configuring a tournament?

**Comment by tienne-B** [comment]
Good point; I'm currently writing a page in the docs about notifications (https://github.com/TabbycatDebate/tabbycat/blob/develop/docs/features/notifications.rst). It will be in the next release. Anything you think should be added to the page?

**Comment by tienne-B** [comment]
Private URL distribution is currently customizable, but is under "Private URLs" and not "Options -> Notifications." It is moved in 2.2.0. Motion release notifications will be in 2.3.0 (along with other notification types :) )

**Comment by 0zlw** [comment]
Ah that makes sense - thanks.

**Comment by philipbelesky** [comment]
Thanks for the feedback @0zlw and your work on the docs @tienne-B. This seems to be resolved but feel free to reopen/comment if not.
