### ISSUE TITLE
Email notifications: Check recipients before bulk sending

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#875]
Currently, email notifications which are sent in bulk (_e.g._ private URLs, registration information, team points) are sent immediately upon pressing a button. This can be a bit nerve-racking to click, especially when you're trusting the software to correctly "fill in the gaps" with emails that weren't previously sent.

One way to alleviate this was in the old private URL emails system, which had you click through a page where it shows whom it's about to email first. That page didn't allow you to change anything, but at least you knew before you sent them who would receive them.

Now that we have a more comprehensive notifications system (thanks, @tienne-B!), it's probably worth the investment in a more complete, generic solution to providing users with more certainty about what emails they're sending, before it happens. What I have in mind is the following:

- In any bulk email function, you first click into a page that lists potential recipients in a table.
- The table lists everyone eligible to receive the email (all speakers, or all adjudicators, or both).
- The first column of the table is a checkbox column; checked recipients (only) will be emailed.
- The checkboxes are prefilled using the same filter as the status quo: those who have already received an email with the same information as the one they would be about to be sent, are initially unchecked; those who haven't already been emailed or whose information has changed, would be initially checked.
- The table also lists their name, email address, some relevant information (_e.g._ their URL key), and a "status" column indicating whether they've received no such email, or how many emails they've received so far and whether one of them is the exact same one they'd be about to be sent, or whether their email address has changed since they were last sent the email, or whether their information has changed since they were last sent the email.
- Those recipients without an email address _are_ listed, but in faded text and but no checkbox is rendered for them (or the checkbox is disabled).

In terms of implementation:
- Since this idea would be reused with all bulk notifications, there should be some base class and base template from which the specific pages inherit.
- The form would have to be dynamically generated, because it's one checkbox per person in the list.
- The checkboxes don't change a database state, so no need for channels, they should just be posted when the user wants to confirm sending emails.

**Comment by tienne-B** [comment]
The page for sending notifications could be expanded beyond what is being proposed here. The page should not just be a table, but rather have a simple table (checkbox, name, email status/message sent indicator) on the left, with the relevant email template in a Summernote widget (#800) on the right. This widget would be saved in dynamic preferences when the messages are sent. Such messages would no longer have to be in the main preferences.

What would be cool is to be able to have an example of what a message would look like filled out. That could be similar to the "preview" tab on Github, using JS to render. Only one message would have to be constructed and passed. A simple find-replace could then be made in JS for this preview toggle.

I think the base class and template is not just an implementation detail but rather the feature. Accessing the base class could allow officials to directly email participants a custom message, which may be easier than trying to find their addresses. It also has the advantage of being from Tabbycat.

The concern is that it would increase the amount of time to send out the notifications, which may preferably be very rapid for draw notifications (#671). I also take it that ballot receipt emails are not included in the "bulk email" category as they may be actioned by the public, or are hooked up to the submission button.

**Comment by philipbelesky** [comment]
Just a quick note: I think one of the ways to address the bloat of the settings section is to only show 'single use' preferences in the areas of the interface they are actually relevant to — i.e. allocation settings only in the allocator. This would be a good opportunity to do so for email widgets also.

Not super concerned about the time it takes to send out emails — this intermediate page should be 'good to go' with its default options, so people can just quickly scroll down to the bottom and hit send if they know what they're doing.

**Comment by czlee** [comment]
I'm also for having #800 on this page for sending notifications and a preview pane so users can see what is about to be sent. I just didn't want to overload this one issue with all of that too 🙂. Between the preview and this list of recipients, I'd prioritize the list of recipients, but the preview would definitely also be very helpful.

In the table you want whatever information is helpful for a user (tab director) who is familiar with the specifics of their tournament, to be able to verify and make good decisions about whether new emails should go out. That is, they should be able to verify their instincts against what the system thinks. I'm not really sure whether number of messages is useful for this purpose, and I'm happy to leave that for a future iteration of this feature.

I agree that ballot receipt emails don't fall into the "bulk email" category, and that having an intermediate page make the process one page load longer doesn't really bother me.

(By "base class" and "base template" I meant the base class in Python code, and the base Django template in the templates folder of the source code—not things that users see.)
