### ISSUE TITLE
Can't change venues through the new allocation interface

### ISSUE THREAD

**Issue by tienne-B** [TabbycatDebate/tabbycat#889]
When venues are set for a round, they can't be manually altered without resetting all of them. Individual venues can't be dragged back to the "pen," nor can venues be swapped. Doesn't work on Chrome nor Safari.

**Comment by philipbelesky** [comment]
Yup, this is a known limitation and there are many more for the new allocations pages — consider them works in progress. I'll let you know when they are considered feature complete / ready for more thorough testing.

**Comment by tienne-B** [comment]
Thanks! I was wondering about the status of the feature, and whether to post a bug report here, ignore, or send a message. As lots of progress was made on another branch that just got merged to `develop`, I took it as ready. (Although if I were certain; I would have made many more reports :) )

**Comment by philipbelesky** [comment]
No problem! As you noticed the merge in was somewhat difficult to keep track of so I was keen to continue the work in develop to try and minimise divergence.
