### ISSUE TITLE
Private URL landing pages should also contain the information in participant records

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#891]
Most important is the "In This Round" box, but it wouldn't hurt to have past results there as well. (The "About this participant" box probably isn't so useful.)

At the moment, the "home" for a participant on the tab website is both the participant's record page _and_ the private URL landing page. The participant's record page should stay where it is, because it's also useful for the public. But it'd be easier for participants to make the landing page a one-stop shop for the subject of the page.

The implementation should probably involve some sort of template inclusions and view mixins to avoid code duplication.

**Comment by tienne-B** [comment]
One little (but significant for i18n) difference would be in the awkwardness of using the person's name on their individual page.

**Comment by czlee** [comment]
Ah, as in changing the sentence that says, "Chuan-Zheng is the chair in room G03" to be in the second person instead? If so, that's a good point!

**Comment by tienne-B** [comment]
Yes. The problem with using the third person is that the situation seems more "detached" from the participant with the third person (would elicit less response with a less clear link to the participant). The challenge would be two-fold: making the variables the 2nd person pronoun (or to add it), and secondly to correctly conjugate based on this change in person.

**Comment by czlee** [comment]
Would that be hard? Wouldn't we just have a bunch of (completely) different strings, each with an analogy to the third-person version? The conjugation is just in the original string, so you wouldn't need to conjugate programmatically (assuming we don't conjugate for gender).

So e.g. you just choose between the template strings
```
{{ adj_name }} is the <strong>chair</strong> adjudicating in <strong>{{ venue }}</strong>.
%(adj_name)s est le/la <strong>président(e)</strong> du jury à <strong>%(venue)s</strong>.
```
and
```
You are the <strong>chair</strong> adjudicating in <strong>{{ venue }}</strong>.
Vous êtes le/la <strong>président(e)</strong> du jury à <strong>%(venue)s</strong>.
```
