### ISSUE TITLE
CSV API for feedback

### ISSUE THREAD

**Issue by philipbelesky** [TabbycatDebate/tabbycat#910]
This should be relatively simple to setup using Django Rest and a library for CSV output. It probably wouldn't be a huge effort, once the view is setup, to have both JSON and CSV outputs.

**Comment by tienne-B** [comment]
Is this for all feedback submissions? (Like "source","target","score","question1","question2",...)

If so, as an extension to #911, we'd need an end-point for teams as they can submit feedback.

**Comment by czlee** [comment]
Oh, at least for now this would just be a read-only API, if you were thinking about submitting feedback via this? 🙂

**Comment by tienne-B** [comment]
No, just that if we want to include the source, we would have to think about teams. Is it one line per adjudicator or one line per feedback submission?

**Comment by czlee** [comment]
Oh, it's per feedback submission. And I see, yeah, this is true.

For context, our previous makeshift implementation just put the team name there alongside team ID, since that information wasn't essential at the time. But I agree that to do this properly would demand an endpoint for teams.
