### ISSUE TITLE
populate_results tries to populate scores from trainee scoresheets

### ISSUE THREAD

**Issue by czlee** [TabbycatDebate/tabbycat#922]
In the traceback on Sentry, the adjudicator in question is actually a trainee in this debate. So I think when `populate_results` populates the scoresheets, it (correctly) excludes the trainee adjudicator from the `DebateResult` object, but because the trainee's `SpeakerScoreByAdj` instances are still in the database, it tries to add those scores, which causes an error.

The tempting thing to do would be add `.exclude(debate_adjudicator__adjudicator__type=DebateAdjudicator.TYPE_TRAINEE)` to the `SpeakerScoreByAdj` queryset in `populate_results` (in `results/prefetch.py`. But this wouldn't change the underlying data inconsistency: trainee adjudicators aren't meant to have `SpeakerScoreByAdj` objects.

This then raises the question: How did the database get into this state? It's possible that the adjudicator was originally a panellist and therefore had a scoresheet, but then got demoted to trainee. Then, if the result was entered before the demotion, the scores from the original results would hang around the database. If the trainee had been removed, cascade deletions would have deleted the `SpeakerScoreByAdj`s, but because it was just a change of `DebateAdjudicator.type`, the `DebateAdjudicator` was never deleted.

It's still always possible to edit the database to get the database to this state, though, so two things should happen:
1) This error should be caught and should fail more gracefully. I think this isn't trivial: We don't really want to delete data without its being the direct and timely result of a deliberate user action, but at the same time if you discover inconsistent data, we should prompt the user to fix it.
2) When an adjudicator is demoted to trainee, associated `SpeakerScoreByAdj` objects should be deleted.

https://sentry.io/tabbycat-ig/backend/issues/766941290/

```
KeyError: <Adjudicator: [name redacted]>
(18 additional frame(s) were not displayed)
...
  File "utils/views.py", line 127, in get_tables
    return [self.get_table()]
  File "participants/views.py", line 228, in get_table
    populate_confirmed_ballots(debates, motions=True, results=True)
  File "results/prefetch.py", line 66, in populate_confirmed_ballots
    populate_results(confirmed_ballots)
  File "results/prefetch.py", line 155, in populate_results
    ssba.position, ssba.score)
  File "results/result.py", line 540, in set_score
    scoresheet = self.scoresheets[adjudicator]

KeyError: <Adjudicator: [name redacted]>
```

**Comment by czlee** [comment]
Update: Owing to the updates in 070a0eadae9dbc83b3c05165e9a73e72584c3f48 and 0d02a23e4863a814d69de3d7ca831cf8240487ef, this no longer triggers the `KeyError` mentioned about, but an `UnboundLocalError`, as the `scoresheet` assignment is skipped by the first `try...except` block but nonetheless referenced in the second one. We don't seem to have received any error reports for this new error, despite its being live since v2.3.2. But we still seem to be getting more of the original `KeyError` at [BACKEND-12G](https://sentry.io/organizations/tabbycat/issues/766941290/?referrer=github_integration) in the last 90 days, from sites that appear (still?) to be running Khao Manee.

**Comment by czlee** [comment]
Regarding my earlier comment:
> The tempting thing to do would be add `.exclude(debate_adjudicator__adjudicator__type=DebateAdjudicator.TYPE_TRAINEE)` to the `SpeakerScoreByAdj` queryset in `populate_results` (in `results/prefetch.py`. But this wouldn't change the underlying data inconsistency: trainee adjudicators aren't meant to have `SpeakerScoreByAdj` objects.

For now I think I'd rather have `VotingDebateResult` log an exception, than filter out the data inconsistency at the prefetch level. That way we still get exception logs in the short term.

I'm still not really sure what else should be done in this situation. In principle, I guess it should behave the same as removing an adjudicator from a debate, which immediately deletes (by cascade) that adjudicator's scoresheet. So we could add a line to to check for demotions, and delete associated score objects manually. But that's adding a special case that's really not ideal—it's prone to missed maintenance and future errors (since other analogous situations just use deletion cascading, someone has to remember to update this special line if that behavior changes).

More generally, I suppose in an ideal world we wouldn't permit adjudicator changes that cascade-delete results, without first checking the user intends for results to be deleted? Which is a bigger issue…

**Comment by czlee** [comment]
Okay, here's what I've done:
1. Made `VotingDebateResult.set_score()` silently fail if the adjudicator doesn't exist, in a29981d58bc334100cf1cd3946d27a1e5f69ce7c.
2. Added a separate "stopgap" check for trainee scoresheets to the admin results page, in 24c52a2daeef8a29a482dedd6d6e16cbe0b69cad.

This doesn't prevent potential issues, it just alerts the user of them. Note that these two checks aren't intrinsically logically tied to each other in any way—the check in (2) is quite separate from (1). But at least the scenarios we know about that can trigger (1) should be accounted for in (2), hopefully.

@philipbelesky @tienne-B Do you think this is enough to close this issue? I think trying to prevent such mishaps from occurring in the first place is a much bigger problem.

**Comment by philipbelesky** [comment]
Yea, I think that's as good as can be reasonably expected!

**Comment by czlee** [comment]
There's a regression in this as a consequence of the refactor in #1180. It appears that the silent failure that was added in a29981d58bc334100cf1cd3946d27a1e5f69ce7c was removed ([here](https://github.com/TabbycatDebate/tabbycat/pull/1180/files#diff-2635a29d66e0aba0a450f4c00b8139e0d3c9647a367da8c6fca2995bf193e531L539-L550)). As a consequence, if there are trainee scoresheets (i.e., if an adj was demoted after their ballot was entered), the results page crashes.
