### ISSUE TITLE
Allow participants to self-report clashes

### ISSUE THREAD

**Issue by tienne-B** [TabbycatDebate/tabbycat#932]
With the comment that I left in #791 (to send a list of clashes to participants), it should be possible for participants to self-report their conflicts. Or have lists on their page; so that the participant does not lose this info in their emails.

That could be done through private URLs through some new views that only have the subject list (with existing conflicts entered). The problem here would be if clashes are mis-used or are excessive _(I read Valerie's FB note)_ and so should be easily ignorable by adj-cores. Don't think this is much of a problem though.

What would be more complicated is venue constraints. I can only see where a participant would want to ask for an accessible venue, and so it might just be best to keep it in tab-hands. The priority on venue constraints would not be used properly as the range is publicly unknown and there is not a specific "accessible" category; they are all just `VenueCategory` objects, and the participants shouldn't get a list to select from.

**Comment by czlee** [comment]
From a purely technical standpoint, despite my opposition to this concept, I'm fine with including it in software provided it can be disabled (as is standard for all Tabbycat public features).

**Comment by tienne-B** [comment]
I'm on the fence as well to the concept; as determining what counts as a conflict should be up to the adj-core, not the participants, who might misuse (inadvertently or not) the feature. But of course, if it were implemented, it must be easily disabled/enabled.

What could be explored is having the information "read-only" as in a type of "About Me" on their landing page (gives a reason for the box: #891 :) )

**Comment by tienne-B** [comment]
Closing; becoming out-of-scope with external registration systems to fill this gap.

**Comment by czlee** [comment]
Oh, are there concrete plans for widely external registration systems that do this? Or are we imagining that this is our preferred solution?

**Comment by tienne-B** [comment]
Imagining that it would be a preferred solution, like I briefly mentioned on FB: https://www.facebook.com/groups/tabbycat.debate/permalink/1522859577881994/
