### ISSUE TITLE
Venue's Check-In Statuses page crashes

### ISSUE THREAD

**Issue by nickdbush** [TabbycatDebate/tabbycat#950]
The "Venue's Check-In Statuses" page (Check-Ins -> Rooms' status) is empty, apart from the title element. Opening up devtools shows this error:

![image](https://user-images.githubusercontent.com/10998201/49333465-3ada3780-f5b7-11e8-8108-506d81922565.png)

Which points to this line:

![image](https://user-images.githubusercontent.com/10998201/49333471-57766f80-f5b7-11e8-9749-9fbd278a9d38.png)

This is a fresh installation on our own DigitalOcean server, and every other page works as expected. Running TabbyCat 2.2.7 on Ubuntu 18.04

**Comment by tienne-B** [comment]
I've made a patch of which you can cherry-pick which should solve the problem. Check the PR.

**Comment by philipbelesky** [comment]
Hey thanks for the report and for the PR @tienne-B! The fix looks pretty clear but I'll leave this open until I have a second to verify the patch and release the hotfix.
