### ISSUE TITLE
Female Adjudicators

### ISSUE THREAD

**Issue by nickdbush** [TabbycatDebate/tabbycat#952]
I've had a bit of a poke around the source, and it appears that female adjudicators are classified as "non-cis male identifying". Here's a block from ```standings/diversity.py```:

```
return Case(
    When(**{'%s__in' % gender_field: (Person.GENDER_FEMALE, Person.GENDER_OTHER), 'then': Value('N')}),
    When(**{gender_field: Person.GENDER_MALE, 'then': Value('M')}),
    default=Value('-'),
    output_field=CharField(),
)
```

If I understand this correctly, male adjudicators are classified as "M". Female or adjudicators or ones without a specified gender are classed as "N", which in the UI, looks like:

![image](https://user-images.githubusercontent.com/10998201/49340478-428df080-f638-11e8-8d86-107549ed613c.png)

Thanks for an amazing piece of software though, and our competition will definitely be donating!

**Comment by tienne-B** [comment]
It's great that you're poking the code :)

Remember that "other" is not equivalent to un-specified; the latter in effect being a different case. You are correct in your analysis, and to separate them you'd probably just have to change those lines (might be wrong though). I think the grouping of female and minority gender identities is as a reflection of debate tournaments which group them together.

**Comment by nickdbush** [comment]
Ah, I firstly read it as "non-cis, male identifying" and thought that female adjudicators were being identified as trans-men, which is where the confusion occurred. I don't have enough experience with how large competitions are run in order to advocate for any changes (as it was designed with intent by those with presumably much more experience than me).

**Comment by czlee** [comment]
Oh, the reasoning's way simpler than anything identity-related. The "other" category at most tournaments is very small, and if you have (say) five or fewer, you run the risk of individuals in "other" (normally non-binary) being inferred from that information plus other knowledge (which could be bad if they're not out).
