### ISSUE TITLE
Dynamic institutional cap calculations for AIDA break models

### ISSUE THREAD

**Issue by viranweerasekera** [TabbycatDebate/tabbycat#996]
AIDA Council passed a constitutional amendment in 2018 which defined a variable institutional cap size. The calculation model for the Open break sets the institutional cap to be **3 + floor[(n-16)/4]** (so a 16-team break with a 3-team cap as a base, and then the cap expands by 1 team for every 4 additional teams included in the Open break). Other breaks are unchanged.

The static solution is to include more break models with different cap sizes, but it may be worth considering a break model with the above dynamic reference included.

**Comment by viranweerasekera** [comment]
Correction, the cap expands by 1 for every 8 teams - The formula in this case would be **3 + floor[(n-16)/8] instead**.

**Comment by tienne-B** [comment]
Think this has been resolved with #997 (merged). Closing.
